// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: account.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignAccount = `-- name: AssignAccount :one
UPDATE account SET
    worker_id   = $2,
    last_used_at = COALESCE(last_used_at, now())
WHERE id = $1
RETURNING
    id, platform, username, auth_status, handle, last_verified_at,
    proxy_group_id, health_score, status, tags, worker_id, last_used_at,
    last_checked_at, last_error, created_at
`

type AssignAccountParams struct {
	ID       pgtype.UUID `json:"id"`
	WorkerID pgtype.UUID `json:"worker_id"`
}

type AssignAccountRow struct {
	ID             pgtype.UUID        `json:"id"`
	Platform       Platform           `json:"platform"`
	Username       string             `json:"username"`
	AuthStatus     AuthStatus         `json:"auth_status"`
	Handle         *string            `json:"handle"`
	LastVerifiedAt pgtype.Timestamptz `json:"last_verified_at"`
	ProxyGroupID   pgtype.UUID        `json:"proxy_group_id"`
	HealthScore    int32              `json:"health_score"`
	Status         AccountStatus      `json:"status"`
	Tags           []string           `json:"tags"`
	WorkerID       pgtype.UUID        `json:"worker_id"`
	LastUsedAt     pgtype.Timestamptz `json:"last_used_at"`
	LastCheckedAt  pgtype.Timestamptz `json:"last_checked_at"`
	LastError      *string            `json:"last_error"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) AssignAccount(ctx context.Context, arg AssignAccountParams) (AssignAccountRow, error) {
	row := q.db.QueryRow(ctx, assignAccount, arg.ID, arg.WorkerID)
	var i AssignAccountRow
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Username,
		&i.AuthStatus,
		&i.Handle,
		&i.LastVerifiedAt,
		&i.ProxyGroupID,
		&i.HealthScore,
		&i.Status,
		&i.Tags,
		&i.WorkerID,
		&i.LastUsedAt,
		&i.LastCheckedAt,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const countAccountsByWorker = `-- name: CountAccountsByWorker :one
SELECT count(*) FROM account WHERE worker_id = $1
`

func (q *Queries) CountAccountsByWorker(ctx context.Context, workerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAccountsByWorker, workerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO account (
    platform, username, password_enc, auth_status, proxy_group_id,
    status, tags, worker_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING
    id, platform, username, auth_status, handle, last_verified_at,
    proxy_group_id, health_score, status, tags, worker_id, last_used_at,
    last_checked_at, last_error, created_at
`

type CreateAccountParams struct {
	Platform     Platform      `json:"platform"`
	Username     string        `json:"username"`
	PasswordEnc  []byte        `json:"password_enc"`
	AuthStatus   AuthStatus    `json:"auth_status"`
	ProxyGroupID pgtype.UUID   `json:"proxy_group_id"`
	Status       AccountStatus `json:"status"`
	Tags         []string      `json:"tags"`
	WorkerID     pgtype.UUID   `json:"worker_id"`
}

type CreateAccountRow struct {
	ID             pgtype.UUID        `json:"id"`
	Platform       Platform           `json:"platform"`
	Username       string             `json:"username"`
	AuthStatus     AuthStatus         `json:"auth_status"`
	Handle         *string            `json:"handle"`
	LastVerifiedAt pgtype.Timestamptz `json:"last_verified_at"`
	ProxyGroupID   pgtype.UUID        `json:"proxy_group_id"`
	HealthScore    int32              `json:"health_score"`
	Status         AccountStatus      `json:"status"`
	Tags           []string           `json:"tags"`
	WorkerID       pgtype.UUID        `json:"worker_id"`
	LastUsedAt     pgtype.Timestamptz `json:"last_used_at"`
	LastCheckedAt  pgtype.Timestamptz `json:"last_checked_at"`
	LastError      *string            `json:"last_error"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.Platform,
		arg.Username,
		arg.PasswordEnc,
		arg.AuthStatus,
		arg.ProxyGroupID,
		arg.Status,
		arg.Tags,
		arg.WorkerID,
	)
	var i CreateAccountRow
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Username,
		&i.AuthStatus,
		&i.Handle,
		&i.LastVerifiedAt,
		&i.ProxyGroupID,
		&i.HealthScore,
		&i.Status,
		&i.Tags,
		&i.WorkerID,
		&i.LastUsedAt,
		&i.LastCheckedAt,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM account WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAccount, id)
	return err
}

const getAccountByID = `-- name: GetAccountByID :one

SELECT
    id, platform, username, auth_status, handle, last_verified_at,
    proxy_group_id, health_score, status, tags, worker_id, last_used_at,
    last_checked_at, last_error, created_at
FROM account
WHERE id = $1
`

type GetAccountByIDRow struct {
	ID             pgtype.UUID        `json:"id"`
	Platform       Platform           `json:"platform"`
	Username       string             `json:"username"`
	AuthStatus     AuthStatus         `json:"auth_status"`
	Handle         *string            `json:"handle"`
	LastVerifiedAt pgtype.Timestamptz `json:"last_verified_at"`
	ProxyGroupID   pgtype.UUID        `json:"proxy_group_id"`
	HealthScore    int32              `json:"health_score"`
	Status         AccountStatus      `json:"status"`
	Tags           []string           `json:"tags"`
	WorkerID       pgtype.UUID        `json:"worker_id"`
	LastUsedAt     pgtype.Timestamptz `json:"last_used_at"`
	LastCheckedAt  pgtype.Timestamptz `json:"last_checked_at"`
	LastError      *string            `json:"last_error"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

// Account (executor identity) queries. password_enc is WRITE-ONLY: no query
// here ever selects it. UNIQUE(platform, username) + UNIQUE(worker_id, platform).
func (q *Queries) GetAccountByID(ctx context.Context, id pgtype.UUID) (GetAccountByIDRow, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i GetAccountByIDRow
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Username,
		&i.AuthStatus,
		&i.Handle,
		&i.LastVerifiedAt,
		&i.ProxyGroupID,
		&i.HealthScore,
		&i.Status,
		&i.Tags,
		&i.WorkerID,
		&i.LastUsedAt,
		&i.LastCheckedAt,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT
    id, platform, username, auth_status, handle, last_verified_at,
    proxy_group_id, health_score, status, tags, worker_id, last_used_at,
    last_checked_at, last_error, created_at
FROM account
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAccountsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAccountsRow struct {
	ID             pgtype.UUID        `json:"id"`
	Platform       Platform           `json:"platform"`
	Username       string             `json:"username"`
	AuthStatus     AuthStatus         `json:"auth_status"`
	Handle         *string            `json:"handle"`
	LastVerifiedAt pgtype.Timestamptz `json:"last_verified_at"`
	ProxyGroupID   pgtype.UUID        `json:"proxy_group_id"`
	HealthScore    int32              `json:"health_score"`
	Status         AccountStatus      `json:"status"`
	Tags           []string           `json:"tags"`
	WorkerID       pgtype.UUID        `json:"worker_id"`
	LastUsedAt     pgtype.Timestamptz `json:"last_used_at"`
	LastCheckedAt  pgtype.Timestamptz `json:"last_checked_at"`
	LastError      *string            `json:"last_error"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]ListAccountsRow, error) {
	rows, err := q.db.Query(ctx, listAccounts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountsRow{}
	for rows.Next() {
		var i ListAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.Username,
			&i.AuthStatus,
			&i.Handle,
			&i.LastVerifiedAt,
			&i.ProxyGroupID,
			&i.HealthScore,
			&i.Status,
			&i.Tags,
			&i.WorkerID,
			&i.LastUsedAt,
			&i.LastCheckedAt,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountsByWorker = `-- name: ListAccountsByWorker :many
SELECT
    id, platform, username, auth_status, handle, last_verified_at,
    proxy_group_id, health_score, status, tags, worker_id, last_used_at,
    last_checked_at, last_error, created_at
FROM account
WHERE worker_id = $1
ORDER BY platform
`

type ListAccountsByWorkerRow struct {
	ID             pgtype.UUID        `json:"id"`
	Platform       Platform           `json:"platform"`
	Username       string             `json:"username"`
	AuthStatus     AuthStatus         `json:"auth_status"`
	Handle         *string            `json:"handle"`
	LastVerifiedAt pgtype.Timestamptz `json:"last_verified_at"`
	ProxyGroupID   pgtype.UUID        `json:"proxy_group_id"`
	HealthScore    int32              `json:"health_score"`
	Status         AccountStatus      `json:"status"`
	Tags           []string           `json:"tags"`
	WorkerID       pgtype.UUID        `json:"worker_id"`
	LastUsedAt     pgtype.Timestamptz `json:"last_used_at"`
	LastCheckedAt  pgtype.Timestamptz `json:"last_checked_at"`
	LastError      *string            `json:"last_error"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAccountsByWorker(ctx context.Context, workerID pgtype.UUID) ([]ListAccountsByWorkerRow, error) {
	rows, err := q.db.Query(ctx, listAccountsByWorker, workerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountsByWorkerRow{}
	for rows.Next() {
		var i ListAccountsByWorkerRow
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.Username,
			&i.AuthStatus,
			&i.Handle,
			&i.LastVerifiedAt,
			&i.ProxyGroupID,
			&i.HealthScore,
			&i.Status,
			&i.Tags,
			&i.WorkerID,
			&i.LastUsedAt,
			&i.LastCheckedAt,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unassignAccount = `-- name: UnassignAccount :one
UPDATE account SET worker_id = NULL
WHERE id = $1
RETURNING
    id, platform, username, auth_status, handle, last_verified_at,
    proxy_group_id, health_score, status, tags, worker_id, last_used_at,
    last_checked_at, last_error, created_at
`

type UnassignAccountRow struct {
	ID             pgtype.UUID        `json:"id"`
	Platform       Platform           `json:"platform"`
	Username       string             `json:"username"`
	AuthStatus     AuthStatus         `json:"auth_status"`
	Handle         *string            `json:"handle"`
	LastVerifiedAt pgtype.Timestamptz `json:"last_verified_at"`
	ProxyGroupID   pgtype.UUID        `json:"proxy_group_id"`
	HealthScore    int32              `json:"health_score"`
	Status         AccountStatus      `json:"status"`
	Tags           []string           `json:"tags"`
	WorkerID       pgtype.UUID        `json:"worker_id"`
	LastUsedAt     pgtype.Timestamptz `json:"last_used_at"`
	LastCheckedAt  pgtype.Timestamptz `json:"last_checked_at"`
	LastError      *string            `json:"last_error"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UnassignAccount(ctx context.Context, id pgtype.UUID) (UnassignAccountRow, error) {
	row := q.db.QueryRow(ctx, unassignAccount, id)
	var i UnassignAccountRow
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Username,
		&i.AuthStatus,
		&i.Handle,
		&i.LastVerifiedAt,
		&i.ProxyGroupID,
		&i.HealthScore,
		&i.Status,
		&i.Tags,
		&i.WorkerID,
		&i.LastUsedAt,
		&i.LastCheckedAt,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE account SET
    auth_status      = $2,
    handle           = $3,
    last_verified_at = $4,
    proxy_group_id   = $5,
    health_score     = $6,
    status           = $7,
    tags             = $8,
    worker_id        = $9,
    last_used_at     = $10,
    last_checked_at  = $11,
    last_error       = $12
WHERE id = $1
RETURNING
    id, platform, username, auth_status, handle, last_verified_at,
    proxy_group_id, health_score, status, tags, worker_id, last_used_at,
    last_checked_at, last_error, created_at
`

type UpdateAccountParams struct {
	ID             pgtype.UUID        `json:"id"`
	AuthStatus     AuthStatus         `json:"auth_status"`
	Handle         *string            `json:"handle"`
	LastVerifiedAt pgtype.Timestamptz `json:"last_verified_at"`
	ProxyGroupID   pgtype.UUID        `json:"proxy_group_id"`
	HealthScore    int32              `json:"health_score"`
	Status         AccountStatus      `json:"status"`
	Tags           []string           `json:"tags"`
	WorkerID       pgtype.UUID        `json:"worker_id"`
	LastUsedAt     pgtype.Timestamptz `json:"last_used_at"`
	LastCheckedAt  pgtype.Timestamptz `json:"last_checked_at"`
	LastError      *string            `json:"last_error"`
}

type UpdateAccountRow struct {
	ID             pgtype.UUID        `json:"id"`
	Platform       Platform           `json:"platform"`
	Username       string             `json:"username"`
	AuthStatus     AuthStatus         `json:"auth_status"`
	Handle         *string            `json:"handle"`
	LastVerifiedAt pgtype.Timestamptz `json:"last_verified_at"`
	ProxyGroupID   pgtype.UUID        `json:"proxy_group_id"`
	HealthScore    int32              `json:"health_score"`
	Status         AccountStatus      `json:"status"`
	Tags           []string           `json:"tags"`
	WorkerID       pgtype.UUID        `json:"worker_id"`
	LastUsedAt     pgtype.Timestamptz `json:"last_used_at"`
	LastCheckedAt  pgtype.Timestamptz `json:"last_checked_at"`
	LastError      *string            `json:"last_error"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (UpdateAccountRow, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.ID,
		arg.AuthStatus,
		arg.Handle,
		arg.LastVerifiedAt,
		arg.ProxyGroupID,
		arg.HealthScore,
		arg.Status,
		arg.Tags,
		arg.WorkerID,
		arg.LastUsedAt,
		arg.LastCheckedAt,
		arg.LastError,
	)
	var i UpdateAccountRow
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Username,
		&i.AuthStatus,
		&i.Handle,
		&i.LastVerifiedAt,
		&i.ProxyGroupID,
		&i.HealthScore,
		&i.Status,
		&i.Tags,
		&i.WorkerID,
		&i.LastUsedAt,
		&i.LastCheckedAt,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}
