// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: action.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextActionJob = `-- name: ClaimNextActionJob :one
UPDATE action_job
SET status     = 'RUNNING',
    started_at = now(),
    attempts   = attempts + 1,
    worker_id  = $2
WHERE id = (
    SELECT aj.id
    FROM action_job AS aj
    WHERE aj.account_id = $1
      AND aj.status     = 'PENDING'
      AND aj.scheduled_at <= now()
    ORDER BY aj.scheduled_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, type, target_id, account_id, worker_id, status, scheduled_at,
          started_at, finished_at, attempts, error, created_at
`

type ClaimNextActionJobParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	WorkerID  pgtype.UUID `json:"worker_id"`
}

// Atomic FIFO claim for one account: PENDING + scheduled_at <= now() ordered by
// scheduled_at, bumped to RUNNING, and stamped with the claiming worker. The
// worker id is written here (not at enqueue time) because a job is assigned to
// whichever worker owns the account's queue at claim time.
func (q *Queries) ClaimNextActionJob(ctx context.Context, arg ClaimNextActionJobParams) (ActionJob, error) {
	row := q.db.QueryRow(ctx, claimNextActionJob, arg.AccountID, arg.WorkerID)
	var i ActionJob
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.TargetID,
		&i.AccountID,
		&i.WorkerID,
		&i.Status,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Attempts,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const completeActionJob = `-- name: CompleteActionJob :one
UPDATE action_job
SET status      = $2,
    finished_at = now(),
    error       = $3
WHERE id = $1
RETURNING id, type, target_id, account_id, worker_id, status, scheduled_at,
          started_at, finished_at, attempts, error, created_at
`

type CompleteActionJobParams struct {
	ID     pgtype.UUID `json:"id"`
	Status JobStatus   `json:"status"`
	Error  *string     `json:"error"`
}

// Terminal transition. The caller has already written the ActionLog row; this
// only projects the verdict onto the job so the queue can be listed without
// joining the log.
func (q *Queries) CompleteActionJob(ctx context.Context, arg CompleteActionJobParams) (ActionJob, error) {
	row := q.db.QueryRow(ctx, completeActionJob, arg.ID, arg.Status, arg.Error)
	var i ActionJob
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.TargetID,
		&i.AccountID,
		&i.WorkerID,
		&i.Status,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Attempts,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const createActionJob = `-- name: CreateActionJob :one

INSERT INTO action_job (type, target_id, account_id, worker_id, status, scheduled_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, type, target_id, account_id, worker_id, status, scheduled_at,
          started_at, finished_at, attempts, error, created_at
`

type CreateActionJobParams struct {
	Type        JobType            `json:"type"`
	TargetID    pgtype.UUID        `json:"target_id"`
	AccountID   pgtype.UUID        `json:"account_id"`
	WorkerID    pgtype.UUID        `json:"worker_id"`
	Status      JobStatus          `json:"status"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
}

// ActionJob + ActionLog (P3-01): the action engine's bookkeeping.
//
// ActionJob mirrors ScrapeJob's claim shape on purpose (same FIFO per-account
// claim via (account_id, status, scheduled_at)); the worker callback and the
// dashboard treat both uniformly. ActionLog is the verdict source of truth;
// ActionJob.status is only a projection of the latest attempt.
func (q *Queries) CreateActionJob(ctx context.Context, arg CreateActionJobParams) (ActionJob, error) {
	row := q.db.QueryRow(ctx, createActionJob,
		arg.Type,
		arg.TargetID,
		arg.AccountID,
		arg.WorkerID,
		arg.Status,
		arg.ScheduledAt,
	)
	var i ActionJob
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.TargetID,
		&i.AccountID,
		&i.WorkerID,
		&i.Status,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Attempts,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const getActionJobByID = `-- name: GetActionJobByID :one
SELECT id, type, target_id, account_id, worker_id, status, scheduled_at,
       started_at, finished_at, attempts, error, created_at
FROM action_job
WHERE id = $1
`

func (q *Queries) GetActionJobByID(ctx context.Context, id pgtype.UUID) (ActionJob, error) {
	row := q.db.QueryRow(ctx, getActionJobByID, id)
	var i ActionJob
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.TargetID,
		&i.AccountID,
		&i.WorkerID,
		&i.Status,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Attempts,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const getActionLog = `-- name: GetActionLog :one
SELECT id, action_job_id, attempt, status, verified, worker_id, rendered_text,
       response_excerpt, error_class, screenshot_url, duration_ms, ts
FROM action_log
WHERE action_job_id = $1 AND attempt = $2
`

type GetActionLogParams struct {
	ActionJobID pgtype.UUID `json:"action_job_id"`
	Attempt     int32       `json:"attempt"`
}

// The latest attempt of a job, by (job, attempt).
func (q *Queries) GetActionLog(ctx context.Context, arg GetActionLogParams) (ActionLog, error) {
	row := q.db.QueryRow(ctx, getActionLog, arg.ActionJobID, arg.Attempt)
	var i ActionLog
	err := row.Scan(
		&i.ID,
		&i.ActionJobID,
		&i.Attempt,
		&i.Status,
		&i.Verified,
		&i.WorkerID,
		&i.RenderedText,
		&i.ResponseExcerpt,
		&i.ErrorClass,
		&i.ScreenshotUrl,
		&i.DurationMs,
		&i.Ts,
	)
	return i, err
}

const listActionJobs = `-- name: ListActionJobs :many
SELECT id, type, target_id, account_id, worker_id, status, scheduled_at,
       started_at, finished_at, attempts, error, created_at
FROM action_job
ORDER BY scheduled_at DESC
LIMIT $1 OFFSET $2
`

type ListActionJobsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListActionJobs(ctx context.Context, arg ListActionJobsParams) ([]ActionJob, error) {
	rows, err := q.db.Query(ctx, listActionJobs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionJob{}
	for rows.Next() {
		var i ActionJob
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.TargetID,
			&i.AccountID,
			&i.WorkerID,
			&i.Status,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Attempts,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActionJobsByAccount = `-- name: ListActionJobsByAccount :many
SELECT id, type, target_id, account_id, worker_id, status, scheduled_at,
       started_at, finished_at, attempts, error, created_at
FROM action_job
WHERE account_id = $1
ORDER BY scheduled_at DESC
LIMIT $2 OFFSET $3
`

type ListActionJobsByAccountParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListActionJobsByAccount(ctx context.Context, arg ListActionJobsByAccountParams) ([]ActionJob, error) {
	rows, err := q.db.Query(ctx, listActionJobsByAccount, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionJob{}
	for rows.Next() {
		var i ActionJob
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.TargetID,
			&i.AccountID,
			&i.WorkerID,
			&i.Status,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Attempts,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActionJobsByStatus = `-- name: ListActionJobsByStatus :many
SELECT id, type, target_id, account_id, worker_id, status, scheduled_at,
       started_at, finished_at, attempts, error, created_at
FROM action_job
WHERE status = $1
ORDER BY scheduled_at
LIMIT $2 OFFSET $3
`

type ListActionJobsByStatusParams struct {
	Status JobStatus `json:"status"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListActionJobsByStatus(ctx context.Context, arg ListActionJobsByStatusParams) ([]ActionJob, error) {
	rows, err := q.db.Query(ctx, listActionJobsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionJob{}
	for rows.Next() {
		var i ActionJob
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.TargetID,
			&i.AccountID,
			&i.WorkerID,
			&i.Status,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Attempts,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActionLogsByErrorClass = `-- name: ListActionLogsByErrorClass :many
SELECT id, action_job_id, attempt, status, verified, worker_id, rendered_text,
       response_excerpt, error_class, screenshot_url, duration_ms, ts
FROM action_log
WHERE error_class = $1
ORDER BY ts DESC
LIMIT $2 OFFSET $3
`

type ListActionLogsByErrorClassParams struct {
	ErrorClass *string `json:"error_class"`
	Limit      int32   `json:"limit"`
	Offset     int32   `json:"offset"`
}

// The failure-class view (P3-12): counts and samples per class come from here.
func (q *Queries) ListActionLogsByErrorClass(ctx context.Context, arg ListActionLogsByErrorClassParams) ([]ActionLog, error) {
	rows, err := q.db.Query(ctx, listActionLogsByErrorClass, arg.ErrorClass, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionLog{}
	for rows.Next() {
		var i ActionLog
		if err := rows.Scan(
			&i.ID,
			&i.ActionJobID,
			&i.Attempt,
			&i.Status,
			&i.Verified,
			&i.WorkerID,
			&i.RenderedText,
			&i.ResponseExcerpt,
			&i.ErrorClass,
			&i.ScreenshotUrl,
			&i.DurationMs,
			&i.Ts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActionLogsByJob = `-- name: ListActionLogsByJob :many
SELECT id, action_job_id, attempt, status, verified, worker_id, rendered_text,
       response_excerpt, error_class, screenshot_url, duration_ms, ts
FROM action_log
WHERE action_job_id = $1
ORDER BY attempt DESC
`

// Every attempt of a job, newest first: the dashboard drawer that debugs one
// action (P4-02) reads this.
func (q *Queries) ListActionLogsByJob(ctx context.Context, actionJobID pgtype.UUID) ([]ActionLog, error) {
	rows, err := q.db.Query(ctx, listActionLogsByJob, actionJobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionLog{}
	for rows.Next() {
		var i ActionLog
		if err := rows.Scan(
			&i.ID,
			&i.ActionJobID,
			&i.Attempt,
			&i.Status,
			&i.Verified,
			&i.WorkerID,
			&i.RenderedText,
			&i.ResponseExcerpt,
			&i.ErrorClass,
			&i.ScreenshotUrl,
			&i.DurationMs,
			&i.Ts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rescheduleActionJob = `-- name: RescheduleActionJob :one
UPDATE action_job
SET status       = 'PENDING',
    scheduled_at = $2,
    finished_at  = NULL
WHERE id = $1
RETURNING id, type, target_id, account_id, worker_id, status, scheduled_at,
          started_at, finished_at, attempts, error, created_at
`

type RescheduleActionJobParams struct {
	ID          pgtype.UUID        `json:"id"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
}

// Backoff/jitter path (P3-11): the attempt failed with a retryable class, so
// the job goes back to PENDING at a future scheduled_at for the next tick.
func (q *Queries) RescheduleActionJob(ctx context.Context, arg RescheduleActionJobParams) (ActionJob, error) {
	row := q.db.QueryRow(ctx, rescheduleActionJob, arg.ID, arg.ScheduledAt)
	var i ActionJob
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.TargetID,
		&i.AccountID,
		&i.WorkerID,
		&i.Status,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Attempts,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const upsertActionLog = `-- name: UpsertActionLog :one
INSERT INTO action_log (
    action_job_id, attempt, status, verified, worker_id, rendered_text,
    response_excerpt, error_class, screenshot_url, duration_ms
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (action_job_id, attempt) DO UPDATE
SET status           = EXCLUDED.status,
    verified         = EXCLUDED.verified,
    worker_id        = COALESCE(EXCLUDED.worker_id, action_log.worker_id),
    response_excerpt = COALESCE(EXCLUDED.response_excerpt, action_log.response_excerpt),
    error_class      = COALESCE(EXCLUDED.error_class, action_log.error_class),
    screenshot_url   = COALESCE(EXCLUDED.screenshot_url, action_log.screenshot_url),
    duration_ms      = EXCLUDED.duration_ms,
    ts               = now()
RETURNING id, action_job_id, attempt, status, verified, worker_id, rendered_text,
          response_excerpt, error_class, screenshot_url, duration_ms, ts
`

type UpsertActionLogParams struct {
	ActionJobID     pgtype.UUID   `json:"action_job_id"`
	Attempt         int32         `json:"attempt"`
	Status          AttemptStatus `json:"status"`
	Verified        bool          `json:"verified"`
	WorkerID        pgtype.UUID   `json:"worker_id"`
	RenderedText    string        `json:"rendered_text"`
	ResponseExcerpt *string       `json:"response_excerpt"`
	ErrorClass      *string       `json:"error_class"`
	ScreenshotUrl   *string       `json:"screenshot_url"`
	DurationMs      int32         `json:"duration_ms"`
}

// The upsert heart of the callback path. A worker first reports RUNNING (no
// screenshot yet, no verdict) and later the terminal verdict on the SAME row:
// UNIQUE (action_job_id, attempt) makes the pair one row.
// screenshot_url and response_excerpt use COALESCE so a terminal callback that
// omits them never erases what the RUNNING callback or an earlier attempt
// captured; rendered_text is the commanded input and is always authoritative.
func (q *Queries) UpsertActionLog(ctx context.Context, arg UpsertActionLogParams) (ActionLog, error) {
	row := q.db.QueryRow(ctx, upsertActionLog,
		arg.ActionJobID,
		arg.Attempt,
		arg.Status,
		arg.Verified,
		arg.WorkerID,
		arg.RenderedText,
		arg.ResponseExcerpt,
		arg.ErrorClass,
		arg.ScreenshotUrl,
		arg.DurationMs,
	)
	var i ActionLog
	err := row.Scan(
		&i.ID,
		&i.ActionJobID,
		&i.Attempt,
		&i.Status,
		&i.Verified,
		&i.WorkerID,
		&i.RenderedText,
		&i.ResponseExcerpt,
		&i.ErrorClass,
		&i.ScreenshotUrl,
		&i.DurationMs,
		&i.Ts,
	)
	return i, err
}
