// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: analytics_snapshot.sql

package sqlcgen

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const analyticsOverviewByPlatform = `-- name: AnalyticsOverviewByPlatform :many
SELECT
    official_account_id,
    last(followers, ts)     AS followers,
    last(reach, ts)         AS reach,
    last(views, ts)         AS views,
    last(mentions, ts)      AS mentions,
    last(engagements, ts)   AS engagements,
    last(profile_views, ts) AS profile_views,
    max(ts)                 AS ts
FROM analytics_snapshot
WHERE platform = $1
  AND ts      >= now() - $2::interval
  AND ts      <  now()
GROUP BY official_account_id
`

type AnalyticsOverviewByPlatformParams struct {
	Platform Platform        `json:"platform"`
	Column2  pgtype.Interval `json:"column_2"`
}

type AnalyticsOverviewByPlatformRow struct {
	OfficialAccountID pgtype.UUID `json:"official_account_id"`
	Followers         interface{} `json:"followers"`
	Reach             interface{} `json:"reach"`
	Views             interface{} `json:"views"`
	Mentions          interface{} `json:"mentions"`
	Engagements       interface{} `json:"engagements"`
	ProfileViews      interface{} `json:"profile_views"`
	Ts                interface{} `json:"ts"`
}

// KPI strip per platform: latest value of each scalar metric per account on
// that platform over the trailing window. `last(x, ts)` over the bucket gives
// the most recent sample per account without a window-function round trip.
func (q *Queries) AnalyticsOverviewByPlatform(ctx context.Context, arg AnalyticsOverviewByPlatformParams) ([]AnalyticsOverviewByPlatformRow, error) {
	rows, err := q.db.Query(ctx, analyticsOverviewByPlatform, arg.Platform, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsOverviewByPlatformRow{}
	for rows.Next() {
		var i AnalyticsOverviewByPlatformRow
		if err := rows.Scan(
			&i.OfficialAccountID,
			&i.Followers,
			&i.Reach,
			&i.Views,
			&i.Mentions,
			&i.Engagements,
			&i.ProfileViews,
			&i.Ts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsTrendByAccount = `-- name: AnalyticsTrendByAccount :many
SELECT
    time_bucket_gapfill('1 day', ts, now() - $3::interval, now()) AS bucket,
    COALESCE(sum(CASE $2::text
            WHEN 'followers'     THEN followers
            WHEN 'reach'         THEN COALESCE(reach, 0)
            WHEN 'views'         THEN COALESCE(views, 0)
            WHEN 'mentions'      THEN COALESCE(mentions, 0)
            WHEN 'engagements'   THEN COALESCE(engagements, 0)
            WHEN 'profile_views' THEN COALESCE(profile_views, 0)
            ELSE 0::bigint
        END), 0)::bigint AS value
FROM analytics_snapshot
WHERE official_account_id = $1
  AND ts      >= now() - $3::interval
  AND ts      <  now()
GROUP BY bucket
ORDER BY bucket
`

type AnalyticsTrendByAccountParams struct {
	OfficialAccountID pgtype.UUID     `json:"official_account_id"`
	Column2           string          `json:"column_2"`
	Column3           pgtype.Interval `json:"column_3"`
}

type AnalyticsTrendByAccountRow struct {
	Bucket interface{} `json:"bucket"`
	Value  int64       `json:"value"`
}

// Same shape, scoped to one account (the per-account drill-down view).
func (q *Queries) AnalyticsTrendByAccount(ctx context.Context, arg AnalyticsTrendByAccountParams) ([]AnalyticsTrendByAccountRow, error) {
	rows, err := q.db.Query(ctx, analyticsTrendByAccount, arg.OfficialAccountID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsTrendByAccountRow{}
	for rows.Next() {
		var i AnalyticsTrendByAccountRow
		if err := rows.Scan(&i.Bucket, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsTrendByPlatform = `-- name: AnalyticsTrendByPlatform :many
SELECT
    time_bucket_gapfill('1 day', ts, now() - $3::interval, now()) AS bucket,
    COALESCE(sum(CASE $2::text
            WHEN 'followers'     THEN followers
            WHEN 'reach'         THEN COALESCE(reach, 0)
            WHEN 'views'         THEN COALESCE(views, 0)
            WHEN 'mentions'      THEN COALESCE(mentions, 0)
            WHEN 'engagements'   THEN COALESCE(engagements, 0)
            WHEN 'profile_views' THEN COALESCE(profile_views, 0)
            ELSE 0::bigint
        END), 0)::bigint AS value
FROM analytics_snapshot
WHERE platform = $1
  AND ts      >= now() - $3::interval
  AND ts      <  now()
GROUP BY bucket
ORDER BY bucket
`

type AnalyticsTrendByPlatformParams struct {
	Platform Platform        `json:"platform"`
	Column2  string          `json:"column_2"`
	Column3  pgtype.Interval `json:"column_3"`
}

type AnalyticsTrendByPlatformRow struct {
	Bucket interface{} `json:"bucket"`
	Value  int64       `json:"value"`
}

// Daily series of one metric summed across all accounts on a platform. The
// metric is picked by name so one query serves every KPI card; every branch is
// bigint so the CASE is type-homogeneous. gapfill needs both time bounds, which
// the WHERE supplies.
func (q *Queries) AnalyticsTrendByPlatform(ctx context.Context, arg AnalyticsTrendByPlatformParams) ([]AnalyticsTrendByPlatformRow, error) {
	rows, err := q.db.Query(ctx, analyticsTrendByPlatform, arg.Platform, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsTrendByPlatformRow{}
	for rows.Next() {
		var i AnalyticsTrendByPlatformRow
		if err := rows.Scan(&i.Bucket, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnalyticsSnapshotsByAccount = `-- name: ListAnalyticsSnapshotsByAccount :many
SELECT id, official_account_id, platform, ts, followers, reach, views, mentions,
       engagements, profile_views, metrics, provider, provider_run_id, fetched_at
FROM analytics_snapshot
WHERE official_account_id = $1
  AND ts >= $2
  AND ts <  $3
ORDER BY ts
`

type ListAnalyticsSnapshotsByAccountParams struct {
	OfficialAccountID pgtype.UUID        `json:"official_account_id"`
	Ts                pgtype.Timestamptz `json:"ts"`
	Ts_2              pgtype.Timestamptz `json:"ts_2"`
}

func (q *Queries) ListAnalyticsSnapshotsByAccount(ctx context.Context, arg ListAnalyticsSnapshotsByAccountParams) ([]AnalyticsSnapshot, error) {
	rows, err := q.db.Query(ctx, listAnalyticsSnapshotsByAccount, arg.OfficialAccountID, arg.Ts, arg.Ts_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsSnapshot{}
	for rows.Next() {
		var i AnalyticsSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.OfficialAccountID,
			&i.Platform,
			&i.Ts,
			&i.Followers,
			&i.Reach,
			&i.Views,
			&i.Mentions,
			&i.Engagements,
			&i.ProfileViews,
			&i.Metrics,
			&i.Provider,
			&i.ProviderRunID,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAnalyticsSnapshot = `-- name: UpsertAnalyticsSnapshot :one

INSERT INTO analytics_snapshot (
    official_account_id, platform, ts, followers, reach, views, mentions,
    engagements, profile_views, metrics, provider, provider_run_id, fetched_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, now())
ON CONFLICT (official_account_id, ts, provider) DO UPDATE
SET followers       = EXCLUDED.followers,
    reach           = EXCLUDED.reach,
    views           = EXCLUDED.views,
    mentions        = EXCLUDED.mentions,
    engagements     = EXCLUDED.engagements,
    profile_views   = EXCLUDED.profile_views,
    metrics         = EXCLUDED.metrics,
    provider_run_id = EXCLUDED.provider_run_id,
    fetched_at      = now()
RETURNING id, official_account_id, platform, ts, followers, reach, views,
          mentions, engagements, profile_views, metrics, provider,
          provider_run_id, fetched_at
`

type UpsertAnalyticsSnapshotParams struct {
	OfficialAccountID pgtype.UUID        `json:"official_account_id"`
	Platform          Platform           `json:"platform"`
	Ts                pgtype.Timestamptz `json:"ts"`
	Followers         *int64             `json:"followers"`
	Reach             *int64             `json:"reach"`
	Views             *int64             `json:"views"`
	Mentions          *int64             `json:"mentions"`
	Engagements       *int64             `json:"engagements"`
	ProfileViews      *int64             `json:"profile_views"`
	Metrics           json.RawMessage    `json:"metrics"`
	Provider          AnalyticsProvider  `json:"provider"`
	ProviderRunID     *string            `json:"provider_run_id"`
}

// AnalyticsSnapshot: official-account metric time-series (Timescale hypertable).
// Idempotent upsert on (official_account_id, ts, provider) so a retried ingest
// run refreshes the same row instead of duplicating it.
//
// `ts` is the hypertable partition column, so every query filters on it (a
// filter on `ts >= X` alone is enough for chunk exclusion; the upper bound is
// stated explicitly so `time_bucket_gapfill` can infer its range).
func (q *Queries) UpsertAnalyticsSnapshot(ctx context.Context, arg UpsertAnalyticsSnapshotParams) (AnalyticsSnapshot, error) {
	row := q.db.QueryRow(ctx, upsertAnalyticsSnapshot,
		arg.OfficialAccountID,
		arg.Platform,
		arg.Ts,
		arg.Followers,
		arg.Reach,
		arg.Views,
		arg.Mentions,
		arg.Engagements,
		arg.ProfileViews,
		arg.Metrics,
		arg.Provider,
		arg.ProviderRunID,
	)
	var i AnalyticsSnapshot
	err := row.Scan(
		&i.ID,
		&i.OfficialAccountID,
		&i.Platform,
		&i.Ts,
		&i.Followers,
		&i.Reach,
		&i.Views,
		&i.Mentions,
		&i.Engagements,
		&i.ProfileViews,
		&i.Metrics,
		&i.Provider,
		&i.ProviderRunID,
		&i.FetchedAt,
	)
	return i, err
}
