// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: analytics_run.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAnalyticsIngestRun = `-- name: CreateAnalyticsIngestRun :one
INSERT INTO analytics_ingest_run (provider, scope, status)
VALUES ($1, $2, 'RUNNING')
RETURNING id, provider, scope, status, started_at, finished_at, accounts_ok,
          accounts_err, error_class, error
`

type CreateAnalyticsIngestRunParams struct {
	Provider AnalyticsProvider `json:"provider"`
	Scope    string            `json:"scope"`
}

func (q *Queries) CreateAnalyticsIngestRun(ctx context.Context, arg CreateAnalyticsIngestRunParams) (AnalyticsIngestRun, error) {
	row := q.db.QueryRow(ctx, createAnalyticsIngestRun, arg.Provider, arg.Scope)
	var i AnalyticsIngestRun
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Scope,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.AccountsOk,
		&i.AccountsErr,
		&i.ErrorClass,
		&i.Error,
	)
	return i, err
}

const getLatestAnalyticsIngestRun = `-- name: GetLatestAnalyticsIngestRun :one
SELECT id, provider, scope, status, started_at, finished_at, accounts_ok,
       accounts_err, error_class, error
FROM analytics_ingest_run
WHERE status IN ('SUCCESS', 'PARTIAL', 'FAILED')
ORDER BY started_at DESC
LIMIT 1
`

// backs the dashboard's freshness badge: the most recent terminal run tells the
// operator whether the analytics view they are reading is current or stale.
func (q *Queries) GetLatestAnalyticsIngestRun(ctx context.Context) (AnalyticsIngestRun, error) {
	row := q.db.QueryRow(ctx, getLatestAnalyticsIngestRun)
	var i AnalyticsIngestRun
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Scope,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.AccountsOk,
		&i.AccountsErr,
		&i.ErrorClass,
		&i.Error,
	)
	return i, err
}

const listAnalyticsIngestRuns = `-- name: ListAnalyticsIngestRuns :many
SELECT id, provider, scope, status, started_at, finished_at, accounts_ok,
       accounts_err, error_class, error
FROM analytics_ingest_run
ORDER BY started_at DESC
LIMIT $1 OFFSET $2
`

type ListAnalyticsIngestRunsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAnalyticsIngestRuns(ctx context.Context, arg ListAnalyticsIngestRunsParams) ([]AnalyticsIngestRun, error) {
	rows, err := q.db.Query(ctx, listAnalyticsIngestRuns, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsIngestRun{}
	for rows.Next() {
		var i AnalyticsIngestRun
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Scope,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.AccountsOk,
			&i.AccountsErr,
			&i.ErrorClass,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnalyticsMentionsByAccount = `-- name: ListAnalyticsMentionsByAccount :many
SELECT id, official_account_id, platform, external_id, author_handle, text, url,
       posted_at, sentiment, fetched_at
FROM analytics_mention
WHERE official_account_id = $1
ORDER BY posted_at DESC
LIMIT $2 OFFSET $3
`

type ListAnalyticsMentionsByAccountParams struct {
	OfficialAccountID pgtype.UUID `json:"official_account_id"`
	Limit             int32       `json:"limit"`
	Offset            int32       `json:"offset"`
}

func (q *Queries) ListAnalyticsMentionsByAccount(ctx context.Context, arg ListAnalyticsMentionsByAccountParams) ([]AnalyticsMention, error) {
	rows, err := q.db.Query(ctx, listAnalyticsMentionsByAccount, arg.OfficialAccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsMention{}
	for rows.Next() {
		var i AnalyticsMention
		if err := rows.Scan(
			&i.ID,
			&i.OfficialAccountID,
			&i.Platform,
			&i.ExternalID,
			&i.AuthorHandle,
			&i.Text,
			&i.Url,
			&i.PostedAt,
			&i.Sentiment,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnalyticsMentionsByPlatform = `-- name: ListAnalyticsMentionsByPlatform :many
SELECT id, official_account_id, platform, external_id, author_handle, text, url,
       posted_at, sentiment, fetched_at
FROM analytics_mention
WHERE platform = $1
ORDER BY posted_at DESC
LIMIT $2 OFFSET $3
`

type ListAnalyticsMentionsByPlatformParams struct {
	Platform Platform `json:"platform"`
	Limit    int32    `json:"limit"`
	Offset   int32    `json:"offset"`
}

func (q *Queries) ListAnalyticsMentionsByPlatform(ctx context.Context, arg ListAnalyticsMentionsByPlatformParams) ([]AnalyticsMention, error) {
	rows, err := q.db.Query(ctx, listAnalyticsMentionsByPlatform, arg.Platform, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsMention{}
	for rows.Next() {
		var i AnalyticsMention
		if err := rows.Scan(
			&i.ID,
			&i.OfficialAccountID,
			&i.Platform,
			&i.ExternalID,
			&i.AuthorHandle,
			&i.Text,
			&i.Url,
			&i.PostedAt,
			&i.Sentiment,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnalyticsIngestRun = `-- name: UpdateAnalyticsIngestRun :one
UPDATE analytics_ingest_run
SET status       = $2,
    accounts_ok  = $3,
    accounts_err = $4,
    error_class  = $5,
    error        = $6,
    finished_at  = now()
WHERE id = $1
RETURNING id, provider, scope, status, started_at, finished_at, accounts_ok,
          accounts_err, error_class, error
`

type UpdateAnalyticsIngestRunParams struct {
	ID          pgtype.UUID  `json:"id"`
	Status      IngestStatus `json:"status"`
	AccountsOk  int32        `json:"accounts_ok"`
	AccountsErr int32        `json:"accounts_err"`
	ErrorClass  *string      `json:"error_class"`
	Error       *string      `json:"error"`
}

func (q *Queries) UpdateAnalyticsIngestRun(ctx context.Context, arg UpdateAnalyticsIngestRunParams) (AnalyticsIngestRun, error) {
	row := q.db.QueryRow(ctx, updateAnalyticsIngestRun,
		arg.ID,
		arg.Status,
		arg.AccountsOk,
		arg.AccountsErr,
		arg.ErrorClass,
		arg.Error,
	)
	var i AnalyticsIngestRun
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Scope,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.AccountsOk,
		&i.AccountsErr,
		&i.ErrorClass,
		&i.Error,
	)
	return i, err
}

const upsertAnalyticsMention = `-- name: UpsertAnalyticsMention :one

INSERT INTO analytics_mention (
    official_account_id, platform, external_id, author_handle, text, url,
    posted_at, sentiment, fetched_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now())
ON CONFLICT (platform, external_id) DO UPDATE
SET author_handle = EXCLUDED.author_handle,
    text          = EXCLUDED.text,
    url           = EXCLUDED.url,
    posted_at     = EXCLUDED.posted_at,
    sentiment     = EXCLUDED.sentiment,
    fetched_at    = now()
RETURNING id, official_account_id, platform, external_id, author_handle, text,
          url, posted_at, sentiment, fetched_at
`

type UpsertAnalyticsMentionParams struct {
	OfficialAccountID pgtype.UUID        `json:"official_account_id"`
	Platform          Platform           `json:"platform"`
	ExternalID        string             `json:"external_id"`
	AuthorHandle      *string            `json:"author_handle"`
	Text              string             `json:"text"`
	Url               string             `json:"url"`
	PostedAt          pgtype.Timestamptz `json:"posted_at"`
	Sentiment         *string            `json:"sentiment"`
}

// AnalyticsMention + AnalyticsIngestRun: provider-sourced mentions and the
// audit trail for the analytics ingest path (mirrors provision_log for workers).
func (q *Queries) UpsertAnalyticsMention(ctx context.Context, arg UpsertAnalyticsMentionParams) (AnalyticsMention, error) {
	row := q.db.QueryRow(ctx, upsertAnalyticsMention,
		arg.OfficialAccountID,
		arg.Platform,
		arg.ExternalID,
		arg.AuthorHandle,
		arg.Text,
		arg.Url,
		arg.PostedAt,
		arg.Sentiment,
	)
	var i AnalyticsMention
	err := row.Scan(
		&i.ID,
		&i.OfficialAccountID,
		&i.Platform,
		&i.ExternalID,
		&i.AuthorHandle,
		&i.Text,
		&i.Url,
		&i.PostedAt,
		&i.Sentiment,
		&i.FetchedAt,
	)
	return i, err
}
