// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: audit.sql

package sqlcgen

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogsFiltered = `-- name: CountAuditLogsFiltered :one
SELECT count(*)
FROM audit_log a
WHERE ($1::uuid         IS NULL OR a.actor_id = $1)
  AND ($2::text         IS NULL OR $2 = '' OR a.action   = $2)
  AND ($3::text         IS NULL OR $3 = '' OR a.entity   = $3)
  AND ($4::timestamptz  IS NULL OR a.ts >= $4)
  AND ($5::timestamptz  IS NULL OR a.ts <  $5)
`

type CountAuditLogsFilteredParams struct {
	Column1 pgtype.UUID        `json:"column_1"`
	Column2 string             `json:"column_2"`
	Column3 string             `json:"column_3"`
	Column4 pgtype.Timestamptz `json:"column_4"`
	Column5 pgtype.Timestamptz `json:"column_5"`
}

func (q *Queries) CountAuditLogsFiltered(ctx context.Context, arg CountAuditLogsFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogsFiltered,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertAuditLog = `-- name: InsertAuditLog :one

INSERT INTO audit_log (actor_id, action, entity, entity_id, diff, ip, result)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, actor_id, action, entity, entity_id, diff, ip, result, ts
`

type InsertAuditLogParams struct {
	ActorID  pgtype.UUID `json:"actor_id"`
	Action   string      `json:"action"`
	Entity   string      `json:"entity"`
	EntityID string      `json:"entity_id"`
	Diff     []byte      `json:"diff"`
	Ip       *netip.Addr `json:"ip"`
	Result   string      `json:"result"`
}

type InsertAuditLogRow struct {
	ID       pgtype.UUID        `json:"id"`
	ActorID  pgtype.UUID        `json:"actor_id"`
	Action   string             `json:"action"`
	Entity   string             `json:"entity"`
	EntityID string             `json:"entity_id"`
	Diff     []byte             `json:"diff"`
	Ip       *netip.Addr        `json:"ip"`
	Result   string             `json:"result"`
	Ts       pgtype.Timestamptz `json:"ts"`
}

// Audit trail queries (P6-10). The read path joins app_user so the dashboard
// gets a human-readable actor (email + name) without a second round trip; the
// actor is NULL for system-initiated rows, hence the LEFT JOIN.
//
// Optional filters follow the report.sql convention: an unset bound is passed
// as an empty value, so each clause also treats ” as "no filter" (the
// `::type IS NULL` arm stays for a real NULL if a caller ever sends one).
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (InsertAuditLogRow, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.ActorID,
		arg.Action,
		arg.Entity,
		arg.EntityID,
		arg.Diff,
		arg.Ip,
		arg.Result,
	)
	var i InsertAuditLogRow
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.Action,
		&i.Entity,
		&i.EntityID,
		&i.Diff,
		&i.Ip,
		&i.Result,
		&i.Ts,
	)
	return i, err
}

const listAuditLogsFiltered = `-- name: ListAuditLogsFiltered :many
SELECT
    a.id,
    a.actor_id,
    a.action,
    a.entity,
    a.entity_id,
    a.result,
    a.ip,
    a.ts,
    u.email  AS actor_email,
    u.name   AS actor_name
FROM audit_log a
LEFT JOIN app_user u ON u.id = a.actor_id
WHERE ($1::uuid         IS NULL OR a.actor_id = $1)
  AND ($2::text         IS NULL OR $2 = '' OR a.action   = $2)
  AND ($3::text         IS NULL OR $3 = '' OR a.entity   = $3)
  AND ($4::timestamptz  IS NULL OR a.ts >= $4)
  AND ($5::timestamptz  IS NULL OR a.ts <  $5)
ORDER BY a.ts DESC
LIMIT $6 OFFSET $7
`

type ListAuditLogsFilteredParams struct {
	Column1 pgtype.UUID        `json:"column_1"`
	Column2 string             `json:"column_2"`
	Column3 string             `json:"column_3"`
	Column4 pgtype.Timestamptz `json:"column_4"`
	Column5 pgtype.Timestamptz `json:"column_5"`
	Limit   int32              `json:"limit"`
	Offset  int32              `json:"offset"`
}

type ListAuditLogsFilteredRow struct {
	ID         pgtype.UUID        `json:"id"`
	ActorID    pgtype.UUID        `json:"actor_id"`
	Action     string             `json:"action"`
	Entity     string             `json:"entity"`
	EntityID   string             `json:"entity_id"`
	Result     string             `json:"result"`
	Ip         *netip.Addr        `json:"ip"`
	Ts         pgtype.Timestamptz `json:"ts"`
	ActorEmail *string            `json:"actor_email"`
	ActorName  *string            `json:"actor_name"`
}

func (q *Queries) ListAuditLogsFiltered(ctx context.Context, arg ListAuditLogsFilteredParams) ([]ListAuditLogsFilteredRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogsFiltered,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsFilteredRow{}
	for rows.Next() {
		var i ListAuditLogsFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Action,
			&i.Entity,
			&i.EntityID,
			&i.Result,
			&i.Ip,
			&i.Ts,
			&i.ActorEmail,
			&i.ActorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
