// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: auth.sql

package sqlcgen

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthSession = `-- name: CreateAuthSession :one
INSERT INTO auth_session (user_id, token_hash, user_agent, ip, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, expires_at, created_at
`

type CreateAuthSessionParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	UserAgent *string            `json:"user_agent"`
	Ip        *netip.Addr        `json:"ip"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type CreateAuthSessionRow struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (CreateAuthSessionRow, error) {
	row := q.db.QueryRow(ctx, createAuthSession,
		arg.UserID,
		arg.TokenHash,
		arg.UserAgent,
		arg.Ip,
		arg.ExpiresAt,
	)
	var i CreateAuthSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredAuthSessions = `-- name: DeleteExpiredAuthSessions :execrows
DELETE FROM auth_session
WHERE expires_at < now()
   OR (revoked_at IS NOT NULL AND revoked_at < now() - interval '7 days')
`

func (q *Queries) DeleteExpiredAuthSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredAuthSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveAuthSession = `-- name: GetActiveAuthSession :one
SELECT s.id, s.user_id, s.expires_at, s.revoked_at,
       u.email, u.name, u.role
FROM auth_session s
JOIN app_user u ON u.id = s.user_id
WHERE s.token_hash = $1
  AND s.revoked_at IS NULL
  AND s.expires_at > now()
`

type GetActiveAuthSessionRow struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	Role      Role               `json:"role"`
}

func (q *Queries) GetActiveAuthSession(ctx context.Context, tokenHash []byte) (GetActiveAuthSessionRow, error) {
	row := q.db.QueryRow(ctx, getActiveAuthSession, tokenHash)
	var i GetActiveAuthSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.Email,
		&i.Name,
		&i.Role,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one

SELECT id, email, name, password_hash, role, created_at
FROM app_user
WHERE id = $1
`

// Auth queries (P0-06).
func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (AppUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE auth_session
SET revoked_at = now(), revoked_reason = $2
WHERE user_id = $1 AND revoked_at IS NULL
`

type RevokeAllUserSessionsParams struct {
	UserID        pgtype.UUID                  `json:"user_id"`
	RevokedReason NullAuthSessionRevokedReason `json:"revoked_reason"`
}

func (q *Queries) RevokeAllUserSessions(ctx context.Context, arg RevokeAllUserSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, arg.UserID, arg.RevokedReason)
	return err
}

const revokeAuthSession = `-- name: RevokeAuthSession :exec
UPDATE auth_session
SET revoked_at = now(), revoked_reason = $2
WHERE token_hash = $1 AND revoked_at IS NULL
`

type RevokeAuthSessionParams struct {
	TokenHash     []byte                       `json:"token_hash"`
	RevokedReason NullAuthSessionRevokedReason `json:"revoked_reason"`
}

func (q *Queries) RevokeAuthSession(ctx context.Context, arg RevokeAuthSessionParams) error {
	_, err := q.db.Exec(ctx, revokeAuthSession, arg.TokenHash, arg.RevokedReason)
	return err
}

const touchAuthSession = `-- name: TouchAuthSession :exec
UPDATE auth_session SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAuthSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchAuthSession, id)
	return err
}
