// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: content.sql

package sqlcgen

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCommentsByPost = `-- name: CountCommentsByPost :one
SELECT count(*) FROM comment WHERE post_id = $1
`

func (q *Queries) CountCommentsByPost(ctx context.Context, postID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCommentsByPost, postID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, post_id, platform, external_id, author_handle, text, metrics,
       scraped_at, parent_id
FROM comment
WHERE id = $1
`

func (q *Queries) GetCommentByID(ctx context.Context, id pgtype.UUID) (Comment, error) {
	row := q.db.QueryRow(ctx, getCommentByID, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.Platform,
		&i.ExternalID,
		&i.AuthorHandle,
		&i.Text,
		&i.Metrics,
		&i.ScrapedAt,
		&i.ParentID,
	)
	return i, err
}

const getCommentByPlatformExternalID = `-- name: GetCommentByPlatformExternalID :one
SELECT id, post_id, platform, external_id, author_handle, text, metrics,
       scraped_at, parent_id
FROM comment
WHERE platform = $1 AND external_id = $2
`

type GetCommentByPlatformExternalIDParams struct {
	Platform   Platform `json:"platform"`
	ExternalID string   `json:"external_id"`
}

func (q *Queries) GetCommentByPlatformExternalID(ctx context.Context, arg GetCommentByPlatformExternalIDParams) (Comment, error) {
	row := q.db.QueryRow(ctx, getCommentByPlatformExternalID, arg.Platform, arg.ExternalID)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.Platform,
		&i.ExternalID,
		&i.AuthorHandle,
		&i.Text,
		&i.Metrics,
		&i.ScrapedAt,
		&i.ParentID,
	)
	return i, err
}

const getPostByID = `-- name: GetPostByID :one

SELECT id, platform, external_id, author_handle, author_id, text, media_urls,
       metrics, scraped_at, author_account_id
FROM post
WHERE id = $1
`

// Post + Comment: scraped content. Both dedupe by (platform, external_id) so a
// re-scrape refreshes metrics instead of duplicating rows (idempotent ingest).
// The columns selected here mirror the Upsert RETURNING clause exactly.
func (q *Queries) GetPostByID(ctx context.Context, id pgtype.UUID) (Post, error) {
	row := q.db.QueryRow(ctx, getPostByID, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.ExternalID,
		&i.AuthorHandle,
		&i.AuthorID,
		&i.Text,
		&i.MediaUrls,
		&i.Metrics,
		&i.ScrapedAt,
		&i.AuthorAccountID,
	)
	return i, err
}

const getPostByPlatformExternalID = `-- name: GetPostByPlatformExternalID :one
SELECT id, platform, external_id, author_handle, author_id, text, media_urls,
       metrics, scraped_at, author_account_id
FROM post
WHERE platform = $1 AND external_id = $2
`

type GetPostByPlatformExternalIDParams struct {
	Platform   Platform `json:"platform"`
	ExternalID string   `json:"external_id"`
}

func (q *Queries) GetPostByPlatformExternalID(ctx context.Context, arg GetPostByPlatformExternalIDParams) (Post, error) {
	row := q.db.QueryRow(ctx, getPostByPlatformExternalID, arg.Platform, arg.ExternalID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.ExternalID,
		&i.AuthorHandle,
		&i.AuthorID,
		&i.Text,
		&i.MediaUrls,
		&i.Metrics,
		&i.ScrapedAt,
		&i.AuthorAccountID,
	)
	return i, err
}

const listCommentsByPost = `-- name: ListCommentsByPost :many
SELECT id, post_id, platform, external_id, author_handle, text, metrics,
       scraped_at, parent_id
FROM comment
WHERE post_id = $1
ORDER BY scraped_at DESC
LIMIT $2 OFFSET $3
`

type ListCommentsByPostParams struct {
	PostID pgtype.UUID `json:"post_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListCommentsByPost(ctx context.Context, arg ListCommentsByPostParams) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listCommentsByPost, arg.PostID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.Platform,
			&i.ExternalID,
			&i.AuthorHandle,
			&i.Text,
			&i.Metrics,
			&i.ScrapedAt,
			&i.ParentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPosts = `-- name: ListPosts :many
SELECT id, platform, external_id, author_handle, author_id, text, media_urls,
       metrics, scraped_at, author_account_id
FROM post
ORDER BY scraped_at DESC
LIMIT $1 OFFSET $2
`

type ListPostsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.ExternalID,
			&i.AuthorHandle,
			&i.AuthorID,
			&i.Text,
			&i.MediaUrls,
			&i.Metrics,
			&i.ScrapedAt,
			&i.AuthorAccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentPostsByPlatform = `-- name: ListRecentPostsByPlatform :many
SELECT id, platform, external_id, author_handle, author_id, text, media_urls,
       metrics, scraped_at, author_account_id
FROM post
WHERE platform = $1
ORDER BY scraped_at DESC
LIMIT $2
`

type ListRecentPostsByPlatformParams struct {
	Platform Platform `json:"platform"`
	Limit    int32    `json:"limit"`
}

// Posts on a platform, newest scrape first. The keyword-scrape read-back uses
// it (this run's rows just got the freshest scraped_at), not a metric ranking.
func (q *Queries) ListRecentPostsByPlatform(ctx context.Context, arg ListRecentPostsByPlatformParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listRecentPostsByPlatform, arg.Platform, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.ExternalID,
			&i.AuthorHandle,
			&i.AuthorID,
			&i.Text,
			&i.MediaUrls,
			&i.Metrics,
			&i.ScrapedAt,
			&i.AuthorAccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopPostsByPlatform = `-- name: ListTopPostsByPlatform :many
SELECT id, platform, external_id, author_handle, author_id, text, media_urls,
       metrics, scraped_at, author_account_id
FROM post
WHERE platform = $1
ORDER BY (metrics->>$2::text)::bigint DESC NULLS LAST
LIMIT $3
`

type ListTopPostsByPlatformParams struct {
	Platform Platform `json:"platform"`
	Column2  string   `json:"column_2"`
	Limit    int32    `json:"limit"`
}

// Top-N posts by a single metric on a platform, for the P2-05 aggregation and
// the dashboard's "top posts" table. metric_key must be a jsonb text field;
// `->>` keeps the bind a plain text parameter (no jsonb literal assembly).
func (q *Queries) ListTopPostsByPlatform(ctx context.Context, arg ListTopPostsByPlatformParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listTopPostsByPlatform, arg.Platform, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.ExternalID,
			&i.AuthorHandle,
			&i.AuthorID,
			&i.Text,
			&i.MediaUrls,
			&i.Metrics,
			&i.ScrapedAt,
			&i.AuthorAccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertComment = `-- name: UpsertComment :one
INSERT INTO comment (
    post_id, platform, external_id, author_handle, text, metrics, parent_id
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (platform, external_id) DO UPDATE
SET text       = EXCLUDED.text,
    metrics    = EXCLUDED.metrics,
    scraped_at = now(),
    parent_id  = EXCLUDED.parent_id
RETURNING id, post_id, platform, external_id, author_handle, text, metrics,
          scraped_at, parent_id
`

type UpsertCommentParams struct {
	PostID       pgtype.UUID     `json:"post_id"`
	Platform     Platform        `json:"platform"`
	ExternalID   string          `json:"external_id"`
	AuthorHandle string          `json:"author_handle"`
	Text         string          `json:"text"`
	Metrics      json.RawMessage `json:"metrics"`
	ParentID     pgtype.UUID     `json:"parent_id"`
}

func (q *Queries) UpsertComment(ctx context.Context, arg UpsertCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, upsertComment,
		arg.PostID,
		arg.Platform,
		arg.ExternalID,
		arg.AuthorHandle,
		arg.Text,
		arg.Metrics,
		arg.ParentID,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.Platform,
		&i.ExternalID,
		&i.AuthorHandle,
		&i.Text,
		&i.Metrics,
		&i.ScrapedAt,
		&i.ParentID,
	)
	return i, err
}

const upsertPost = `-- name: UpsertPost :one
INSERT INTO post (
    platform, external_id, author_handle, author_id, text, media_urls, metrics,
    author_account_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (platform, external_id) DO UPDATE
SET text               = EXCLUDED.text,
    media_urls         = EXCLUDED.media_urls,
    metrics            = EXCLUDED.metrics,
    scraped_at         = now(),
    author_account_id  = EXCLUDED.author_account_id
RETURNING id, platform, external_id, author_handle, author_id, text, media_urls,
          metrics, scraped_at, author_account_id
`

type UpsertPostParams struct {
	Platform        Platform        `json:"platform"`
	ExternalID      string          `json:"external_id"`
	AuthorHandle    string          `json:"author_handle"`
	AuthorID        string          `json:"author_id"`
	Text            *string         `json:"text"`
	MediaUrls       []string        `json:"media_urls"`
	Metrics         json.RawMessage `json:"metrics"`
	AuthorAccountID pgtype.UUID     `json:"author_account_id"`
}

func (q *Queries) UpsertPost(ctx context.Context, arg UpsertPostParams) (Post, error) {
	row := q.db.QueryRow(ctx, upsertPost,
		arg.Platform,
		arg.ExternalID,
		arg.AuthorHandle,
		arg.AuthorID,
		arg.Text,
		arg.MediaUrls,
		arg.Metrics,
		arg.AuthorAccountID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.ExternalID,
		&i.AuthorHandle,
		&i.AuthorID,
		&i.Text,
		&i.MediaUrls,
		&i.Metrics,
		&i.ScrapedAt,
		&i.AuthorAccountID,
	)
	return i, err
}
