// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: core.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO app_user (email, name, password_hash, role)
VALUES (lower($1), $2, $3, $4)
RETURNING id, email, name, role, created_at
`

type CreateUserParams struct {
	Lower        string `json:"lower"`
	Name         string `json:"name"`
	PasswordHash string `json:"password_hash"`
	Role         Role   `json:"role"`
}

type CreateUserRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	Role      Role               `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Lower,
		arg.Name,
		arg.PasswordHash,
		arg.Role,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getTeamConfig = `-- name: GetTeamConfig :one

SELECT id, name, created_at
FROM team_config
LIMIT 1
`

// Example queries exercising the sqlc pipeline (P0-05).
// Real per-domain query files land with their tables in later phases.
func (q *Queries) GetTeamConfig(ctx context.Context) (TeamConfig, error) {
	row := q.db.QueryRow(ctx, getTeamConfig)
	var i TeamConfig
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password_hash, role, created_at
FROM app_user
WHERE email = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (AppUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO audit_log (actor_id, action, entity, entity_id, diff)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, actor_id, action, entity, entity_id, diff, ts
`

type InsertAuditLogParams struct {
	ActorID  pgtype.UUID `json:"actor_id"`
	Action   string      `json:"action"`
	Entity   string      `json:"entity"`
	EntityID string      `json:"entity_id"`
	Diff     []byte      `json:"diff"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.ActorID,
		arg.Action,
		arg.Entity,
		arg.EntityID,
		arg.Diff,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.Action,
		&i.Entity,
		&i.EntityID,
		&i.Diff,
		&i.Ts,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, actor_id, action, entity, entity_id, diff, ts
FROM audit_log
ORDER BY ts DESC
LIMIT $1
`

func (q *Queries) ListAuditLogs(ctx context.Context, limit int32) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Action,
			&i.Entity,
			&i.EntityID,
			&i.Diff,
			&i.Ts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, role, created_at
FROM app_user
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUsersRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	Role      Role               `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTeamConfig = `-- name: UpsertTeamConfig :one
INSERT INTO team_config (name)
VALUES ($1)
ON CONFLICT ((true)) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name, created_at
`

func (q *Queries) UpsertTeamConfig(ctx context.Context, name string) (TeamConfig, error) {
	row := q.db.QueryRow(ctx, upsertTeamConfig, name)
	var i TeamConfig
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
