// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: core.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOwnersExcept = `-- name: CountOwnersExcept :one
SELECT count(*) FROM app_user WHERE role = 'OWNER' AND id <> $1
`

func (q *Queries) CountOwnersExcept(ctx context.Context, id pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOwnersExcept, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM app_user
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO app_user (email, name, password_hash, role)
VALUES (lower($1), $2, $3, $4)
RETURNING id, email, name, role, created_at
`

type CreateUserParams struct {
	Lower        string `json:"lower"`
	Name         string `json:"name"`
	PasswordHash string `json:"password_hash"`
	Role         Role   `json:"role"`
}

type CreateUserRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	Role      Role               `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Lower,
		arg.Name,
		arg.PasswordHash,
		arg.Role,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM app_user WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getTeamConfig = `-- name: GetTeamConfig :one

SELECT id, name, created_at
FROM team_config
LIMIT 1
`

// Example queries exercising the sqlc pipeline (P0-05).
// Real per-domain query files land with their tables in later phases.
func (q *Queries) GetTeamConfig(ctx context.Context) (TeamConfig, error) {
	row := q.db.QueryRow(ctx, getTeamConfig)
	var i TeamConfig
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password_hash, role, created_at
FROM app_user
WHERE email = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (AppUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, role, created_at
FROM app_user
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUsersRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	Role      Role               `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE app_user
SET name = $2, role = $3
WHERE id = $1
RETURNING id, email, name, role, created_at
`

type UpdateUserParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
	Role Role        `json:"role"`
}

type UpdateUserRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	Role      Role               `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.Name, arg.Role)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const upsertTeamConfig = `-- name: UpsertTeamConfig :one
INSERT INTO team_config (name)
VALUES ($1)
ON CONFLICT ((true)) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name, created_at
`

func (q *Queries) UpsertTeamConfig(ctx context.Context, name string) (TeamConfig, error) {
	row := q.db.QueryRow(ctx, upsertTeamConfig, name)
	var i TeamConfig
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
