// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: keyword_batch.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createKeywordBatch = `-- name: CreateKeywordBatch :one

INSERT INTO keyword_batch (platform, keywords, window_from, window_to, max_posts, actor_id, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, platform, keywords, window_from, window_to, max_posts, actor_id, status, apify_run_id, items_read, posts_count, comments_count, error, created_by, created_at, finished_at
`

type CreateKeywordBatchParams struct {
	Platform   Platform           `json:"platform"`
	Keywords   []string           `json:"keywords"`
	WindowFrom pgtype.Timestamptz `json:"window_from"`
	WindowTo   pgtype.Timestamptz `json:"window_to"`
	MaxPosts   int32              `json:"max_posts"`
	ActorID    string             `json:"actor_id"`
	Status     string             `json:"status"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
}

// Keyword batch (background scrape): one async run per keyword search.
// POST /api/scrape/keywords inserts PENDING then a goroutine drives RUNNING→SUCCEEDED/FAILED.
func (q *Queries) CreateKeywordBatch(ctx context.Context, arg CreateKeywordBatchParams) (KeywordBatch, error) {
	row := q.db.QueryRow(ctx, createKeywordBatch,
		arg.Platform,
		arg.Keywords,
		arg.WindowFrom,
		arg.WindowTo,
		arg.MaxPosts,
		arg.ActorID,
		arg.Status,
		arg.CreatedBy,
	)
	var i KeywordBatch
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Keywords,
		&i.WindowFrom,
		&i.WindowTo,
		&i.MaxPosts,
		&i.ActorID,
		&i.Status,
		&i.ApifyRunID,
		&i.ItemsRead,
		&i.PostsCount,
		&i.CommentsCount,
		&i.Error,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createKeywordBatchPost = `-- name: CreateKeywordBatchPost :exec
INSERT INTO keyword_batch_post (keyword_batch_id, post_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type CreateKeywordBatchPostParams struct {
	KeywordBatchID pgtype.UUID `json:"keyword_batch_id"`
	PostID         pgtype.UUID `json:"post_id"`
}

func (q *Queries) CreateKeywordBatchPost(ctx context.Context, arg CreateKeywordBatchPostParams) error {
	_, err := q.db.Exec(ctx, createKeywordBatchPost, arg.KeywordBatchID, arg.PostID)
	return err
}

const getKeywordBatchByID = `-- name: GetKeywordBatchByID :one
SELECT id, platform, keywords, window_from, window_to, max_posts, actor_id, status, apify_run_id, items_read, posts_count, comments_count, error, created_by, created_at, finished_at
FROM keyword_batch
WHERE id = $1
`

func (q *Queries) GetKeywordBatchByID(ctx context.Context, id pgtype.UUID) (KeywordBatch, error) {
	row := q.db.QueryRow(ctx, getKeywordBatchByID, id)
	var i KeywordBatch
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Keywords,
		&i.WindowFrom,
		&i.WindowTo,
		&i.MaxPosts,
		&i.ActorID,
		&i.Status,
		&i.ApifyRunID,
		&i.ItemsRead,
		&i.PostsCount,
		&i.CommentsCount,
		&i.Error,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listKeywordBatchPosts = `-- name: ListKeywordBatchPosts :many
SELECT p.id, p.platform, p.external_id, p.author_handle, p.author_id, p.text, p.media_urls, p.metrics, p.scraped_at, p.author_account_id
FROM post p
JOIN keyword_batch_post kbp ON kbp.post_id = p.id
WHERE kbp.keyword_batch_id = $1
ORDER BY p.scraped_at DESC
LIMIT $2 OFFSET $3
`

type ListKeywordBatchPostsParams struct {
	KeywordBatchID pgtype.UUID `json:"keyword_batch_id"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

func (q *Queries) ListKeywordBatchPosts(ctx context.Context, arg ListKeywordBatchPostsParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listKeywordBatchPosts, arg.KeywordBatchID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.ExternalID,
			&i.AuthorHandle,
			&i.AuthorID,
			&i.Text,
			&i.MediaUrls,
			&i.Metrics,
			&i.ScrapedAt,
			&i.AuthorAccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKeywordBatches = `-- name: ListKeywordBatches :many
SELECT id, platform, keywords, window_from, window_to, max_posts, actor_id, status, apify_run_id, items_read, posts_count, comments_count, error, created_by, created_at, finished_at
FROM keyword_batch
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListKeywordBatchesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListKeywordBatches(ctx context.Context, arg ListKeywordBatchesParams) ([]KeywordBatch, error) {
	rows, err := q.db.Query(ctx, listKeywordBatches, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KeywordBatch{}
	for rows.Next() {
		var i KeywordBatch
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.Keywords,
			&i.WindowFrom,
			&i.WindowTo,
			&i.MaxPosts,
			&i.ActorID,
			&i.Status,
			&i.ApifyRunID,
			&i.ItemsRead,
			&i.PostsCount,
			&i.CommentsCount,
			&i.Error,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateKeywordBatchStatus = `-- name: UpdateKeywordBatchStatus :one
UPDATE keyword_batch
SET status = $2, apify_run_id = COALESCE($3, apify_run_id), items_read = $4, posts_count = $5, comments_count = $6, error = $7, finished_at = $8
WHERE id = $1
RETURNING id, platform, keywords, window_from, window_to, max_posts, actor_id, status, apify_run_id, items_read, posts_count, comments_count, error, created_by, created_at, finished_at
`

type UpdateKeywordBatchStatusParams struct {
	ID            pgtype.UUID        `json:"id"`
	Status        string             `json:"status"`
	ApifyRunID    pgtype.UUID        `json:"apify_run_id"`
	ItemsRead     int32              `json:"items_read"`
	PostsCount    int32              `json:"posts_count"`
	CommentsCount int32              `json:"comments_count"`
	Error         *string            `json:"error"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
}

// Drives PENDING→RUNNING→SUCCEEDED/FAILED. finished_at set only on terminal.
func (q *Queries) UpdateKeywordBatchStatus(ctx context.Context, arg UpdateKeywordBatchStatusParams) (KeywordBatch, error) {
	row := q.db.QueryRow(ctx, updateKeywordBatchStatus,
		arg.ID,
		arg.Status,
		arg.ApifyRunID,
		arg.ItemsRead,
		arg.PostsCount,
		arg.CommentsCount,
		arg.Error,
		arg.FinishedAt,
	)
	var i KeywordBatch
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Keywords,
		&i.WindowFrom,
		&i.WindowTo,
		&i.MaxPosts,
		&i.ActorID,
		&i.Status,
		&i.ApifyRunID,
		&i.ItemsRead,
		&i.PostsCount,
		&i.CommentsCount,
		&i.Error,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}
