// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: metric_snapshot.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMetricSnapshot = `-- name: CreateMetricSnapshot :exec

INSERT INTO metric_snapshot (post_id, views, likes, comments, shares, reach, reels_views)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateMetricSnapshotParams struct {
	PostID     pgtype.UUID `json:"post_id"`
	Views      int64       `json:"views"`
	Likes      int64       `json:"likes"`
	Comments   int64       `json:"comments"`
	Shares     int64       `json:"shares"`
	Reach      *int64      `json:"reach"`
	ReelsViews *int64      `json:"reels_views"`
}

// MetricSnapshot: per-post metric time-series (Timescale hypertable).
// PK is (id, ts) because Timescale requires the partition column in every
// unique index, so every query filters on `ts` to hit a chunk range.
func (q *Queries) CreateMetricSnapshot(ctx context.Context, arg CreateMetricSnapshotParams) error {
	_, err := q.db.Exec(ctx, createMetricSnapshot,
		arg.PostID,
		arg.Views,
		arg.Likes,
		arg.Comments,
		arg.Shares,
		arg.Reach,
		arg.ReelsViews,
	)
	return err
}

const latestMetricSnapshotsByPost = `-- name: LatestMetricSnapshotsByPost :many
SELECT
    post_id,
    last(views, ts)        AS views,
    last(likes, ts)        AS likes,
    last(comments, ts)     AS comments,
    last(shares, ts)       AS shares,
    last(reach, ts)        AS reach,
    last(reels_views, ts)  AS reels_views,
    max(ts)                AS ts
FROM metric_snapshot
WHERE ts >= now() - INTERVAL '90 days'
GROUP BY post_id
`

type LatestMetricSnapshotsByPostRow struct {
	PostID     pgtype.UUID `json:"post_id"`
	Views      interface{} `json:"views"`
	Likes      interface{} `json:"likes"`
	Comments   interface{} `json:"comments"`
	Shares     interface{} `json:"shares"`
	Reach      interface{} `json:"reach"`
	ReelsViews interface{} `json:"reels_views"`
	Ts         interface{} `json:"ts"`
}

// `last()` picks the value of the final row in the bucket; with a 1-day bucket
// over a hypertable this collapses to "the most recent sample per post".
func (q *Queries) LatestMetricSnapshotsByPost(ctx context.Context) ([]LatestMetricSnapshotsByPostRow, error) {
	rows, err := q.db.Query(ctx, latestMetricSnapshotsByPost)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LatestMetricSnapshotsByPostRow{}
	for rows.Next() {
		var i LatestMetricSnapshotsByPostRow
		if err := rows.Scan(
			&i.PostID,
			&i.Views,
			&i.Likes,
			&i.Comments,
			&i.Shares,
			&i.Reach,
			&i.ReelsViews,
			&i.Ts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetricSnapshotsByPost = `-- name: ListMetricSnapshotsByPost :many
SELECT id, post_id, ts, views, likes, comments, shares, reach, reels_views
FROM metric_snapshot
WHERE post_id = $1
  AND ts      >= $2
  AND ts      <  $3
ORDER BY ts
`

type ListMetricSnapshotsByPostParams struct {
	PostID pgtype.UUID        `json:"post_id"`
	Ts     pgtype.Timestamptz `json:"ts"`
	Ts_2   pgtype.Timestamptz `json:"ts_2"`
}

func (q *Queries) ListMetricSnapshotsByPost(ctx context.Context, arg ListMetricSnapshotsByPostParams) ([]MetricSnapshot, error) {
	rows, err := q.db.Query(ctx, listMetricSnapshotsByPost, arg.PostID, arg.Ts, arg.Ts_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetricSnapshot{}
	for rows.Next() {
		var i MetricSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.Ts,
			&i.Views,
			&i.Likes,
			&i.Comments,
			&i.Shares,
			&i.Reach,
			&i.ReelsViews,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topPostsByMetric = `-- name: TopPostsByMetric :many
SELECT
    post_id,
    last(views, ts)       AS views,
    last(likes, ts)       AS likes,
    last(comments, ts)    AS comments,
    last(shares, ts)      AS shares,
    last(reach, ts)       AS reach,
    last(reels_views, ts) AS reels_views,
    max(ts)               AS ts
FROM metric_snapshot
WHERE ts >= now() - INTERVAL '90 days'
GROUP BY post_id
ORDER BY (CASE $1::text
            WHEN 'views'       THEN last(views, ts)
            WHEN 'likes'       THEN last(likes, ts)
            WHEN 'comments'    THEN last(comments, ts)
            WHEN 'shares'      THEN last(shares, ts)
            WHEN 'reach'       THEN COALESCE(last(reach, ts), 0)
            WHEN 'reels_views' THEN COALESCE(last(reels_views, ts), 0)
          END) DESC NULLS LAST
LIMIT $2
`

type TopPostsByMetricParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
}

type TopPostsByMetricRow struct {
	PostID     pgtype.UUID `json:"post_id"`
	Views      interface{} `json:"views"`
	Likes      interface{} `json:"likes"`
	Comments   interface{} `json:"comments"`
	Shares     interface{} `json:"shares"`
	Reach      interface{} `json:"reach"`
	ReelsViews interface{} `json:"reels_views"`
	Ts         interface{} `json:"ts"`
}

// P2-05 aggregation: top-100 posts by a metric over a trailing window, via a
// continuous-look-alike query on the latest snapshot per post.
func (q *Queries) TopPostsByMetric(ctx context.Context, arg TopPostsByMetricParams) ([]TopPostsByMetricRow, error) {
	rows, err := q.db.Query(ctx, topPostsByMetric, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopPostsByMetricRow{}
	for rows.Next() {
		var i TopPostsByMetricRow
		if err := rows.Scan(
			&i.PostID,
			&i.Views,
			&i.Likes,
			&i.Comments,
			&i.Shares,
			&i.Reach,
			&i.ReelsViews,
			&i.Ts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
