// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcgen

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuthSessionRevokedReason string

const (
	AuthSessionRevokedReasonLogout  AuthSessionRevokedReason = "logout"
	AuthSessionRevokedReasonRotated AuthSessionRevokedReason = "rotated"
	AuthSessionRevokedReasonReuse   AuthSessionRevokedReason = "reuse"
)

func (e *AuthSessionRevokedReason) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthSessionRevokedReason(s)
	case string:
		*e = AuthSessionRevokedReason(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthSessionRevokedReason: %T", src)
	}
	return nil
}

type NullAuthSessionRevokedReason struct {
	AuthSessionRevokedReason AuthSessionRevokedReason `json:"auth_session_revoked_reason"`
	Valid                    bool                     `json:"valid"` // Valid is true if AuthSessionRevokedReason is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthSessionRevokedReason) Scan(value interface{}) error {
	if value == nil {
		ns.AuthSessionRevokedReason, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthSessionRevokedReason.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthSessionRevokedReason) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthSessionRevokedReason), nil
}

type Role string

const (
	RoleOWNER      Role = "OWNER"
	RoleSTRATEGIST Role = "STRATEGIST"
	RoleOPERATOR   Role = "OPERATOR"
	RoleANALYST    Role = "ANALYST"
)

func (e *Role) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Role(s)
	case string:
		*e = Role(s)
	default:
		return fmt.Errorf("unsupported scan type for Role: %T", src)
	}
	return nil
}

type NullRole struct {
	Role  Role `json:"role"`
	Valid bool `json:"valid"` // Valid is true if Role is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRole) Scan(value interface{}) error {
	if value == nil {
		ns.Role, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Role.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Role), nil
}

type AppUser struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	Name         string             `json:"name"`
	PasswordHash string             `json:"password_hash"`
	Role         Role               `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type AuditLog struct {
	ID       pgtype.UUID        `json:"id"`
	ActorID  pgtype.UUID        `json:"actor_id"`
	Action   string             `json:"action"`
	Entity   string             `json:"entity"`
	EntityID string             `json:"entity_id"`
	Diff     []byte             `json:"diff"`
	Ts       pgtype.Timestamptz `json:"ts"`
}

type AuthSession struct {
	ID            pgtype.UUID                  `json:"id"`
	UserID        pgtype.UUID                  `json:"user_id"`
	TokenHash     []byte                       `json:"token_hash"`
	UserAgent     *string                      `json:"user_agent"`
	Ip            *netip.Addr                  `json:"ip"`
	ExpiresAt     pgtype.Timestamptz           `json:"expires_at"`
	CreatedAt     pgtype.Timestamptz           `json:"created_at"`
	LastUsedAt    pgtype.Timestamptz           `json:"last_used_at"`
	RevokedAt     pgtype.Timestamptz           `json:"revoked_at"`
	RevokedReason NullAuthSessionRevokedReason `json:"revoked_reason"`
}

type TeamConfig struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
