// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcgen

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AccountStatus string

const (
	AccountStatusPENDING     AccountStatus = "PENDING"
	AccountStatusACTIVE      AccountStatus = "ACTIVE"
	AccountStatusPAUSED      AccountStatus = "PAUSED"
	AccountStatusQUARANTINED AccountStatus = "QUARANTINED"
	AccountStatusDEAD        AccountStatus = "DEAD"
	AccountStatusARCHIVED    AccountStatus = "ARCHIVED"
)

func (e *AccountStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountStatus(s)
	case string:
		*e = AccountStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountStatus: %T", src)
	}
	return nil
}

type NullAccountStatus struct {
	AccountStatus AccountStatus `json:"account_status"`
	Valid         bool          `json:"valid"` // Valid is true if AccountStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AccountStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountStatus), nil
}

type AnalyticsProvider string

const (
	AnalyticsProviderTHIRDPARTYA AnalyticsProvider = "THIRDPARTY_A"
	AnalyticsProviderTHIRDPARTYB AnalyticsProvider = "THIRDPARTY_B"
)

func (e *AnalyticsProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AnalyticsProvider(s)
	case string:
		*e = AnalyticsProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for AnalyticsProvider: %T", src)
	}
	return nil
}

type NullAnalyticsProvider struct {
	AnalyticsProvider AnalyticsProvider `json:"analytics_provider"`
	Valid             bool              `json:"valid"` // Valid is true if AnalyticsProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAnalyticsProvider) Scan(value interface{}) error {
	if value == nil {
		ns.AnalyticsProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AnalyticsProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAnalyticsProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AnalyticsProvider), nil
}

type AttemptStatus string

const (
	AttemptStatusRUNNING   AttemptStatus = "RUNNING"
	AttemptStatusSUCCESS   AttemptStatus = "SUCCESS"
	AttemptStatusFAILED    AttemptStatus = "FAILED"
	AttemptStatusRETRY     AttemptStatus = "RETRY"
	AttemptStatusCANCELLED AttemptStatus = "CANCELLED"
)

func (e *AttemptStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AttemptStatus(s)
	case string:
		*e = AttemptStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AttemptStatus: %T", src)
	}
	return nil
}

type NullAttemptStatus struct {
	AttemptStatus AttemptStatus `json:"attempt_status"`
	Valid         bool          `json:"valid"` // Valid is true if AttemptStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAttemptStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AttemptStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AttemptStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAttemptStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AttemptStatus), nil
}

type AuthSessionRevokedReason string

const (
	AuthSessionRevokedReasonLogout  AuthSessionRevokedReason = "logout"
	AuthSessionRevokedReasonRotated AuthSessionRevokedReason = "rotated"
	AuthSessionRevokedReasonReuse   AuthSessionRevokedReason = "reuse"
)

func (e *AuthSessionRevokedReason) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthSessionRevokedReason(s)
	case string:
		*e = AuthSessionRevokedReason(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthSessionRevokedReason: %T", src)
	}
	return nil
}

type NullAuthSessionRevokedReason struct {
	AuthSessionRevokedReason AuthSessionRevokedReason `json:"auth_session_revoked_reason"`
	Valid                    bool                     `json:"valid"` // Valid is true if AuthSessionRevokedReason is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthSessionRevokedReason) Scan(value interface{}) error {
	if value == nil {
		ns.AuthSessionRevokedReason, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthSessionRevokedReason.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthSessionRevokedReason) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthSessionRevokedReason), nil
}

type AuthStatus string

const (
	AuthStatusAUTHENTICATING AuthStatus = "AUTHENTICATING"
	AuthStatusNEEDSINPUT     AuthStatus = "NEEDS_INPUT"
	AuthStatusAUTHENTICATED  AuthStatus = "AUTHENTICATED"
	AuthStatusFAILED         AuthStatus = "FAILED"
)

func (e *AuthStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthStatus(s)
	case string:
		*e = AuthStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthStatus: %T", src)
	}
	return nil
}

type NullAuthStatus struct {
	AuthStatus AuthStatus `json:"auth_status"`
	Valid      bool       `json:"valid"` // Valid is true if AuthStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AuthStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthStatus), nil
}

type DesiredState string

const (
	DesiredStateRUNNING DesiredState = "RUNNING"
	DesiredStateSTOPPED DesiredState = "STOPPED"
)

func (e *DesiredState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DesiredState(s)
	case string:
		*e = DesiredState(s)
	default:
		return fmt.Errorf("unsupported scan type for DesiredState: %T", src)
	}
	return nil
}

type NullDesiredState struct {
	DesiredState DesiredState `json:"desired_state"`
	Valid        bool         `json:"valid"` // Valid is true if DesiredState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDesiredState) Scan(value interface{}) error {
	if value == nil {
		ns.DesiredState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DesiredState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDesiredState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DesiredState), nil
}

type IngestStatus string

const (
	IngestStatusPENDING IngestStatus = "PENDING"
	IngestStatusRUNNING IngestStatus = "RUNNING"
	IngestStatusSUCCESS IngestStatus = "SUCCESS"
	IngestStatusFAILED  IngestStatus = "FAILED"
	IngestStatusPARTIAL IngestStatus = "PARTIAL"
)

func (e *IngestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IngestStatus(s)
	case string:
		*e = IngestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for IngestStatus: %T", src)
	}
	return nil
}

type NullIngestStatus struct {
	IngestStatus IngestStatus `json:"ingest_status"`
	Valid        bool         `json:"valid"` // Valid is true if IngestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIngestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.IngestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IngestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIngestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IngestStatus), nil
}

type JobStatus string

const (
	JobStatusPENDING   JobStatus = "PENDING"
	JobStatusRUNNING   JobStatus = "RUNNING"
	JobStatusSUCCESS   JobStatus = "SUCCESS"
	JobStatusFAILED    JobStatus = "FAILED"
	JobStatusRETRY     JobStatus = "RETRY"
	JobStatusCANCELLED JobStatus = "CANCELLED"
)

func (e *JobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStatus(s)
	case string:
		*e = JobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStatus: %T", src)
	}
	return nil
}

type NullJobStatus struct {
	JobStatus JobStatus `json:"job_status"`
	Valid     bool      `json:"valid"` // Valid is true if JobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.JobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobStatus), nil
}

type JobType string

const (
	JobTypeSCRAPELIKE     JobType = "SCRAPE_LIKE"
	JobTypeSCRAPECOMMENT  JobType = "SCRAPE_COMMENT"
	JobTypeSCRAPEMETRIC   JobType = "SCRAPE_METRIC"
	JobTypeSESSIONREFRESH JobType = "SESSION_REFRESH"
	JobTypeACTIONLIKE     JobType = "ACTION_LIKE"
	JobTypeACTIONCOMMENT  JobType = "ACTION_COMMENT"
)

func (e *JobType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobType(s)
	case string:
		*e = JobType(s)
	default:
		return fmt.Errorf("unsupported scan type for JobType: %T", src)
	}
	return nil
}

type NullJobType struct {
	JobType JobType `json:"job_type"`
	Valid   bool    `json:"valid"` // Valid is true if JobType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobType) Scan(value interface{}) error {
	if value == nil {
		ns.JobType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobType), nil
}

type OfficialAccountStatus string

const (
	OfficialAccountStatusACTIVE   OfficialAccountStatus = "ACTIVE"
	OfficialAccountStatusPAUSED   OfficialAccountStatus = "PAUSED"
	OfficialAccountStatusARCHIVED OfficialAccountStatus = "ARCHIVED"
)

func (e *OfficialAccountStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OfficialAccountStatus(s)
	case string:
		*e = OfficialAccountStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OfficialAccountStatus: %T", src)
	}
	return nil
}

type NullOfficialAccountStatus struct {
	OfficialAccountStatus OfficialAccountStatus `json:"official_account_status"`
	Valid                 bool                  `json:"valid"` // Valid is true if OfficialAccountStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOfficialAccountStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OfficialAccountStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OfficialAccountStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOfficialAccountStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OfficialAccountStatus), nil
}

type Platform string

const (
	PlatformINSTAGRAM Platform = "INSTAGRAM"
	PlatformTHREADS   Platform = "THREADS"
	PlatformFACEBOOK  Platform = "FACEBOOK"
	PlatformTIKTOK    Platform = "TIKTOK"
	PlatformLINKEDIN  Platform = "LINKEDIN"
	PlatformX         Platform = "X"
	PlatformYOUTUBE   Platform = "YOUTUBE"
)

func (e *Platform) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Platform(s)
	case string:
		*e = Platform(s)
	default:
		return fmt.Errorf("unsupported scan type for Platform: %T", src)
	}
	return nil
}

type NullPlatform struct {
	Platform Platform `json:"platform"`
	Valid    bool     `json:"valid"` // Valid is true if Platform is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlatform) Scan(value interface{}) error {
	if value == nil {
		ns.Platform, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Platform.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlatform) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Platform), nil
}

type ProvisionOp string

const (
	ProvisionOpCREATE ProvisionOp = "CREATE"
	ProvisionOpDELETE ProvisionOp = "DELETE"
)

func (e *ProvisionOp) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProvisionOp(s)
	case string:
		*e = ProvisionOp(s)
	default:
		return fmt.Errorf("unsupported scan type for ProvisionOp: %T", src)
	}
	return nil
}

type NullProvisionOp struct {
	ProvisionOp ProvisionOp `json:"provision_op"`
	Valid       bool        `json:"valid"` // Valid is true if ProvisionOp is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProvisionOp) Scan(value interface{}) error {
	if value == nil {
		ns.ProvisionOp, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProvisionOp.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProvisionOp) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProvisionOp), nil
}

type Role string

const (
	RoleOWNER      Role = "OWNER"
	RoleSTRATEGIST Role = "STRATEGIST"
	RoleOPERATOR   Role = "OPERATOR"
	RoleANALYST    Role = "ANALYST"
)

func (e *Role) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Role(s)
	case string:
		*e = Role(s)
	default:
		return fmt.Errorf("unsupported scan type for Role: %T", src)
	}
	return nil
}

type NullRole struct {
	Role  Role `json:"role"`
	Valid bool `json:"valid"` // Valid is true if Role is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRole) Scan(value interface{}) error {
	if value == nil {
		ns.Role, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Role.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Role), nil
}

type TargetKind string

const (
	TargetKindPOST    TargetKind = "POST"
	TargetKindCOMMENT TargetKind = "COMMENT"
)

func (e *TargetKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TargetKind(s)
	case string:
		*e = TargetKind(s)
	default:
		return fmt.Errorf("unsupported scan type for TargetKind: %T", src)
	}
	return nil
}

type NullTargetKind struct {
	TargetKind TargetKind `json:"target_kind"`
	Valid      bool       `json:"valid"` // Valid is true if TargetKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTargetKind) Scan(value interface{}) error {
	if value == nil {
		ns.TargetKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TargetKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTargetKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TargetKind), nil
}

type WorkerSource string

const (
	WorkerSourceMANUAL WorkerSource = "MANUAL"
	WorkerSourceAUTO   WorkerSource = "AUTO"
)

func (e *WorkerSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorkerSource(s)
	case string:
		*e = WorkerSource(s)
	default:
		return fmt.Errorf("unsupported scan type for WorkerSource: %T", src)
	}
	return nil
}

type NullWorkerSource struct {
	WorkerSource WorkerSource `json:"worker_source"`
	Valid        bool         `json:"valid"` // Valid is true if WorkerSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorkerSource) Scan(value interface{}) error {
	if value == nil {
		ns.WorkerSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorkerSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorkerSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorkerSource), nil
}

type WorkerStatus string

const (
	WorkerStatusPENDING     WorkerStatus = "PENDING"
	WorkerStatusREADY       WorkerStatus = "READY"
	WorkerStatusIDLE        WorkerStatus = "IDLE"
	WorkerStatusBUSY        WorkerStatus = "BUSY"
	WorkerStatusDRAINING    WorkerStatus = "DRAINING"
	WorkerStatusERROR       WorkerStatus = "ERROR"
	WorkerStatusDEAD        WorkerStatus = "DEAD"
	WorkerStatusQUARANTINED WorkerStatus = "QUARANTINED"
)

func (e *WorkerStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorkerStatus(s)
	case string:
		*e = WorkerStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WorkerStatus: %T", src)
	}
	return nil
}

type NullWorkerStatus struct {
	WorkerStatus WorkerStatus `json:"worker_status"`
	Valid        bool         `json:"valid"` // Valid is true if WorkerStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorkerStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WorkerStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorkerStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorkerStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorkerStatus), nil
}

type Account struct {
	ID             pgtype.UUID        `json:"id"`
	Platform       Platform           `json:"platform"`
	Username       string             `json:"username"`
	PasswordEnc    []byte             `json:"password_enc"`
	AuthStatus     AuthStatus         `json:"auth_status"`
	Handle         *string            `json:"handle"`
	LastVerifiedAt pgtype.Timestamptz `json:"last_verified_at"`
	Credentials    []byte             `json:"credentials"`
	CookieExpiryAt pgtype.Timestamptz `json:"cookie_expiry_at"`
	ProxyGroupID   pgtype.UUID        `json:"proxy_group_id"`
	HealthScore    int32              `json:"health_score"`
	Status         AccountStatus      `json:"status"`
	Tags           []string           `json:"tags"`
	WorkerID       pgtype.UUID        `json:"worker_id"`
	LastUsedAt     pgtype.Timestamptz `json:"last_used_at"`
	LastCheckedAt  pgtype.Timestamptz `json:"last_checked_at"`
	LastError      *string            `json:"last_error"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ActionJob struct {
	ID          pgtype.UUID        `json:"id"`
	Type        JobType            `json:"type"`
	TargetID    pgtype.UUID        `json:"target_id"`
	AccountID   pgtype.UUID        `json:"account_id"`
	WorkerID    pgtype.UUID        `json:"worker_id"`
	Status      JobStatus          `json:"status"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
	Attempts    int32              `json:"attempts"`
	Error       *string            `json:"error"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	TemplateID  pgtype.UUID        `json:"template_id"`
}

type ActionLog struct {
	ID              pgtype.UUID        `json:"id"`
	ActionJobID     pgtype.UUID        `json:"action_job_id"`
	Attempt         int32              `json:"attempt"`
	Status          AttemptStatus      `json:"status"`
	Verified        bool               `json:"verified"`
	WorkerID        pgtype.UUID        `json:"worker_id"`
	RenderedText    string             `json:"rendered_text"`
	ResponseExcerpt *string            `json:"response_excerpt"`
	ErrorClass      *string            `json:"error_class"`
	ScreenshotUrl   *string            `json:"screenshot_url"`
	DurationMs      int32              `json:"duration_ms"`
	Ts              pgtype.Timestamptz `json:"ts"`
	TemplateID      pgtype.UUID        `json:"template_id"`
}

type AnalyticsIngestRun struct {
	ID          pgtype.UUID        `json:"id"`
	Provider    AnalyticsProvider  `json:"provider"`
	Scope       string             `json:"scope"`
	Status      IngestStatus       `json:"status"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
	AccountsOk  int32              `json:"accounts_ok"`
	AccountsErr int32              `json:"accounts_err"`
	ErrorClass  *string            `json:"error_class"`
	Error       *string            `json:"error"`
}

type AnalyticsMention struct {
	ID                pgtype.UUID        `json:"id"`
	OfficialAccountID pgtype.UUID        `json:"official_account_id"`
	Platform          Platform           `json:"platform"`
	ExternalID        string             `json:"external_id"`
	AuthorHandle      *string            `json:"author_handle"`
	Text              string             `json:"text"`
	Url               string             `json:"url"`
	PostedAt          pgtype.Timestamptz `json:"posted_at"`
	Sentiment         *string            `json:"sentiment"`
	FetchedAt         pgtype.Timestamptz `json:"fetched_at"`
}

type AnalyticsSnapshot struct {
	ID                pgtype.UUID        `json:"id"`
	OfficialAccountID pgtype.UUID        `json:"official_account_id"`
	Platform          Platform           `json:"platform"`
	Ts                pgtype.Timestamptz `json:"ts"`
	Followers         *int64             `json:"followers"`
	Reach             *int64             `json:"reach"`
	Views             *int64             `json:"views"`
	Mentions          *int64             `json:"mentions"`
	Engagements       *int64             `json:"engagements"`
	ProfileViews      *int64             `json:"profile_views"`
	Metrics           json.RawMessage    `json:"metrics"`
	Provider          AnalyticsProvider  `json:"provider"`
	ProviderRunID     *string            `json:"provider_run_id"`
	FetchedAt         pgtype.Timestamptz `json:"fetched_at"`
}

type ApifyRun struct {
	ID          pgtype.UUID        `json:"id"`
	ScrapeJobID pgtype.UUID        `json:"scrape_job_id"`
	ActorID     string             `json:"actor_id"`
	RunID       string             `json:"run_id"`
	Status      string             `json:"status"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
}

type AppUser struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	Name         string             `json:"name"`
	PasswordHash string             `json:"password_hash"`
	Role         Role               `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type AuditLog struct {
	ID       pgtype.UUID        `json:"id"`
	ActorID  pgtype.UUID        `json:"actor_id"`
	Action   string             `json:"action"`
	Entity   string             `json:"entity"`
	EntityID string             `json:"entity_id"`
	Diff     []byte             `json:"diff"`
	Ts       pgtype.Timestamptz `json:"ts"`
}

type AuthSession struct {
	ID            pgtype.UUID                  `json:"id"`
	UserID        pgtype.UUID                  `json:"user_id"`
	TokenHash     []byte                       `json:"token_hash"`
	UserAgent     *string                      `json:"user_agent"`
	Ip            *netip.Addr                  `json:"ip"`
	ExpiresAt     pgtype.Timestamptz           `json:"expires_at"`
	CreatedAt     pgtype.Timestamptz           `json:"created_at"`
	LastUsedAt    pgtype.Timestamptz           `json:"last_used_at"`
	RevokedAt     pgtype.Timestamptz           `json:"revoked_at"`
	RevokedReason NullAuthSessionRevokedReason `json:"revoked_reason"`
}

type Comment struct {
	ID           pgtype.UUID        `json:"id"`
	PostID       pgtype.UUID        `json:"post_id"`
	Platform     Platform           `json:"platform"`
	ExternalID   string             `json:"external_id"`
	AuthorHandle string             `json:"author_handle"`
	Text         string             `json:"text"`
	Metrics      json.RawMessage    `json:"metrics"`
	ScrapedAt    pgtype.Timestamptz `json:"scraped_at"`
	ParentID     pgtype.UUID        `json:"parent_id"`
}

type CommentTemplate struct {
	ID          pgtype.UUID        `json:"id"`
	Platform    Platform           `json:"platform"`
	Text        string             `json:"text"`
	Vars        []string           `json:"vars"`
	Weight      int32              `json:"weight"`
	BannedWords []string           `json:"banned_words"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Heartbeat struct {
	ID       pgtype.UUID        `json:"id"`
	WorkerID pgtype.UUID        `json:"worker_id"`
	Ts       pgtype.Timestamptz `json:"ts"`
	Cpu      float64            `json:"cpu"`
	Mem      float64            `json:"mem"`
	JobsDone int32              `json:"jobs_done"`
}

type MetricSnapshot struct {
	ID         pgtype.UUID        `json:"id"`
	PostID     pgtype.UUID        `json:"post_id"`
	Ts         pgtype.Timestamptz `json:"ts"`
	Views      int64              `json:"views"`
	Likes      int64              `json:"likes"`
	Comments   int64              `json:"comments"`
	Shares     int64              `json:"shares"`
	Reach      *int64             `json:"reach"`
	ReelsViews *int64             `json:"reels_views"`
}

type OfficialAccount struct {
	ID            pgtype.UUID           `json:"id"`
	Platform      Platform              `json:"platform"`
	Handle        string                `json:"handle"`
	DisplayName   *string               `json:"display_name"`
	ProfileUrl    *string               `json:"profile_url"`
	AvatarUrl     *string               `json:"avatar_url"`
	Status        OfficialAccountStatus `json:"status"`
	Provider      AnalyticsProvider     `json:"provider"`
	ProviderRef   *string               `json:"provider_ref"`
	Tags          []string              `json:"tags"`
	LastFetchedAt pgtype.Timestamptz    `json:"last_fetched_at"`
	CreatedAt     pgtype.Timestamptz    `json:"created_at"`
}

type Post struct {
	ID              pgtype.UUID        `json:"id"`
	Platform        Platform           `json:"platform"`
	ExternalID      string             `json:"external_id"`
	AuthorHandle    string             `json:"author_handle"`
	AuthorID        string             `json:"author_id"`
	Text            *string            `json:"text"`
	MediaUrls       []string           `json:"media_urls"`
	Metrics         json.RawMessage    `json:"metrics"`
	ScrapedAt       pgtype.Timestamptz `json:"scraped_at"`
	AuthorAccountID pgtype.UUID        `json:"author_account_id"`
}

type ProvisionLog struct {
	ID         pgtype.UUID        `json:"id"`
	WorkerID   pgtype.UUID        `json:"worker_id"`
	Op         ProvisionOp        `json:"op"`
	Generation int32              `json:"generation"`
	K8sRef     *string            `json:"k8s_ref"`
	Status     string             `json:"status"`
	Error      *string            `json:"error"`
	Ts         pgtype.Timestamptz `json:"ts"`
}

type ProxyGroup struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Region         string             `json:"region"`
	Provider       string             `json:"provider"`
	PoolKey        []byte             `json:"pool_key"`
	MaxConcurrency int32              `json:"max_concurrency"`
	DailyBudgetMb  int32              `json:"daily_budget_mb"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type RawPayload struct {
	ID         pgtype.UUID        `json:"id"`
	ApifyRunID pgtype.UUID        `json:"apify_run_id"`
	S3Key      string             `json:"s3_key"`
	Bytes      int64              `json:"bytes"`
	ReceivedAt pgtype.Timestamptz `json:"received_at"`
}

type ScrapeJob struct {
	ID          pgtype.UUID        `json:"id"`
	Type        JobType            `json:"type"`
	TargetID    pgtype.UUID        `json:"target_id"`
	AccountID   pgtype.UUID        `json:"account_id"`
	WorkerID    pgtype.UUID        `json:"worker_id"`
	Status      JobStatus          `json:"status"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
	Attempts    int32              `json:"attempts"`
	Error       *string            `json:"error"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Target struct {
	ID         pgtype.UUID        `json:"id"`
	Kind       TargetKind         `json:"kind"`
	Platform   Platform           `json:"platform"`
	ExternalID string             `json:"external_id"`
	Url        string             `json:"url"`
	Meta       json.RawMessage    `json:"meta"`
	PostID     pgtype.UUID        `json:"post_id"`
	CommentID  pgtype.UUID        `json:"comment_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type TeamConfig struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Worker struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	ContainerID    *string            `json:"container_id"`
	ControlChannel *string            `json:"control_channel"`
	ActionQueue    *string            `json:"action_queue"`
	SessionPvc     *string            `json:"session_pvc"`
	NovncService   *string            `json:"novnc_service"`
	DesiredState   DesiredState       `json:"desired_state"`
	Source         WorkerSource       `json:"source"`
	Region         string             `json:"region"`
	Status         WorkerStatus       `json:"status"`
	Generation     int32              `json:"generation"`
	ObservedGen    *int32             `json:"observed_gen"`
	ProvisionErr   *string            `json:"provision_err"`
	BrowserStatus  string             `json:"browser_status"`
	CurrentJobID   pgtype.UUID        `json:"current_job_id"`
	LastHeartbeat  pgtype.Timestamptz `json:"last_heartbeat"`
	LastActionAt   pgtype.Timestamptz `json:"last_action_at"`
	LastError      *string            `json:"last_error"`
	QueueDepth     int32              `json:"queue_depth"`
	RestartCount   int32              `json:"restart_count"`
	ImageVersion   string             `json:"image_version"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
