// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: official_account.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveOfficialAccount = `-- name: ArchiveOfficialAccount :one
UPDATE official_account SET status = 'ARCHIVED'
WHERE id = $1
RETURNING id, platform, handle, display_name, profile_url, avatar_url, status,
          provider, provider_ref, tags, last_fetched_at, created_at
`

func (q *Queries) ArchiveOfficialAccount(ctx context.Context, id pgtype.UUID) (OfficialAccount, error) {
	row := q.db.QueryRow(ctx, archiveOfficialAccount, id)
	var i OfficialAccount
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Handle,
		&i.DisplayName,
		&i.ProfileUrl,
		&i.AvatarUrl,
		&i.Status,
		&i.Provider,
		&i.ProviderRef,
		&i.Tags,
		&i.LastFetchedAt,
		&i.CreatedAt,
	)
	return i, err
}

const countOfficialAccountsByPlatform = `-- name: CountOfficialAccountsByPlatform :one
SELECT count(*) FROM official_account WHERE platform = $1
`

func (q *Queries) CountOfficialAccountsByPlatform(ctx context.Context, platform Platform) (int64, error) {
	row := q.db.QueryRow(ctx, countOfficialAccountsByPlatform, platform)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOfficialAccount = `-- name: CreateOfficialAccount :one
INSERT INTO official_account (
    platform, handle, display_name, profile_url, avatar_url, status, provider,
    provider_ref, tags
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, platform, handle, display_name, profile_url, avatar_url, status,
          provider, provider_ref, tags, last_fetched_at, created_at
`

type CreateOfficialAccountParams struct {
	Platform    Platform              `json:"platform"`
	Handle      string                `json:"handle"`
	DisplayName *string               `json:"display_name"`
	ProfileUrl  *string               `json:"profile_url"`
	AvatarUrl   *string               `json:"avatar_url"`
	Status      OfficialAccountStatus `json:"status"`
	Provider    AnalyticsProvider     `json:"provider"`
	ProviderRef *string               `json:"provider_ref"`
	Tags        []string              `json:"tags"`
}

func (q *Queries) CreateOfficialAccount(ctx context.Context, arg CreateOfficialAccountParams) (OfficialAccount, error) {
	row := q.db.QueryRow(ctx, createOfficialAccount,
		arg.Platform,
		arg.Handle,
		arg.DisplayName,
		arg.ProfileUrl,
		arg.AvatarUrl,
		arg.Status,
		arg.Provider,
		arg.ProviderRef,
		arg.Tags,
	)
	var i OfficialAccount
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Handle,
		&i.DisplayName,
		&i.ProfileUrl,
		&i.AvatarUrl,
		&i.Status,
		&i.Provider,
		&i.ProviderRef,
		&i.Tags,
		&i.LastFetchedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOfficialAccountByID = `-- name: GetOfficialAccountByID :one

SELECT id, platform, handle, display_name, profile_url, avatar_url, status,
       provider, provider_ref, tags, last_fetched_at, created_at
FROM official_account
WHERE id = $1
`

// OfficialAccount: a monitored brand/client account (read-only). NOT an
// `account` (executor) — no credentials, no login, no actions. Metrics come
// from a 3rd-party provider and land in analytics_snapshot/analytics_mention.
func (q *Queries) GetOfficialAccountByID(ctx context.Context, id pgtype.UUID) (OfficialAccount, error) {
	row := q.db.QueryRow(ctx, getOfficialAccountByID, id)
	var i OfficialAccount
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Handle,
		&i.DisplayName,
		&i.ProfileUrl,
		&i.AvatarUrl,
		&i.Status,
		&i.Provider,
		&i.ProviderRef,
		&i.Tags,
		&i.LastFetchedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listOfficialAccounts = `-- name: ListOfficialAccounts :many
SELECT id, platform, handle, display_name, profile_url, avatar_url, status,
       provider, provider_ref, tags, last_fetched_at, created_at
FROM official_account
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListOfficialAccountsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListOfficialAccounts(ctx context.Context, arg ListOfficialAccountsParams) ([]OfficialAccount, error) {
	rows, err := q.db.Query(ctx, listOfficialAccounts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OfficialAccount{}
	for rows.Next() {
		var i OfficialAccount
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.Handle,
			&i.DisplayName,
			&i.ProfileUrl,
			&i.AvatarUrl,
			&i.Status,
			&i.Provider,
			&i.ProviderRef,
			&i.Tags,
			&i.LastFetchedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOfficialAccountsByPlatform = `-- name: ListOfficialAccountsByPlatform :many
SELECT id, platform, handle, display_name, profile_url, avatar_url, status,
       provider, provider_ref, tags, last_fetched_at, created_at
FROM official_account
WHERE platform = $1
ORDER BY handle
LIMIT $2 OFFSET $3
`

type ListOfficialAccountsByPlatformParams struct {
	Platform Platform `json:"platform"`
	Limit    int32    `json:"limit"`
	Offset   int32    `json:"offset"`
}

func (q *Queries) ListOfficialAccountsByPlatform(ctx context.Context, arg ListOfficialAccountsByPlatformParams) ([]OfficialAccount, error) {
	rows, err := q.db.Query(ctx, listOfficialAccountsByPlatform, arg.Platform, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OfficialAccount{}
	for rows.Next() {
		var i OfficialAccount
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.Handle,
			&i.DisplayName,
			&i.ProfileUrl,
			&i.AvatarUrl,
			&i.Status,
			&i.Provider,
			&i.ProviderRef,
			&i.Tags,
			&i.LastFetchedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOfficialAccountsForIngest = `-- name: ListOfficialAccountsForIngest :many
SELECT id, platform, handle, display_name, profile_url, avatar_url, status,
       provider, provider_ref, tags, last_fetched_at, created_at
FROM official_account
WHERE status   = 'ACTIVE'
  AND provider = $1
ORDER BY last_fetched_at NULLS FIRST, handle
LIMIT $2
`

type ListOfficialAccountsForIngestParams struct {
	Provider AnalyticsProvider `json:"provider"`
	Limit    int32             `json:"limit"`
}

// every ACTIVE account for a provider, walked by the ingestor cron tick.
func (q *Queries) ListOfficialAccountsForIngest(ctx context.Context, arg ListOfficialAccountsForIngestParams) ([]OfficialAccount, error) {
	rows, err := q.db.Query(ctx, listOfficialAccountsForIngest, arg.Provider, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OfficialAccount{}
	for rows.Next() {
		var i OfficialAccount
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.Handle,
			&i.DisplayName,
			&i.ProfileUrl,
			&i.AvatarUrl,
			&i.Status,
			&i.Provider,
			&i.ProviderRef,
			&i.Tags,
			&i.LastFetchedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchOfficialAccountFetched = `-- name: TouchOfficialAccountFetched :exec
UPDATE official_account SET last_fetched_at = now() WHERE id = $1
`

// written by the ingestor only after a successful snapshot write, so
// last_fetched_at always means "data present", not "attempt ran".
func (q *Queries) TouchOfficialAccountFetched(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchOfficialAccountFetched, id)
	return err
}

const updateOfficialAccount = `-- name: UpdateOfficialAccount :one
UPDATE official_account SET
    platform       = $2,
    handle         = $3,
    display_name   = $4,
    profile_url    = $5,
    avatar_url     = $6,
    status         = $7,
    provider       = $8,
    provider_ref   = $9,
    tags           = $10
WHERE id = $1
RETURNING id, platform, handle, display_name, profile_url, avatar_url, status,
          provider, provider_ref, tags, last_fetched_at, created_at
`

type UpdateOfficialAccountParams struct {
	ID          pgtype.UUID           `json:"id"`
	Platform    Platform              `json:"platform"`
	Handle      string                `json:"handle"`
	DisplayName *string               `json:"display_name"`
	ProfileUrl  *string               `json:"profile_url"`
	AvatarUrl   *string               `json:"avatar_url"`
	Status      OfficialAccountStatus `json:"status"`
	Provider    AnalyticsProvider     `json:"provider"`
	ProviderRef *string               `json:"provider_ref"`
	Tags        []string              `json:"tags"`
}

func (q *Queries) UpdateOfficialAccount(ctx context.Context, arg UpdateOfficialAccountParams) (OfficialAccount, error) {
	row := q.db.QueryRow(ctx, updateOfficialAccount,
		arg.ID,
		arg.Platform,
		arg.Handle,
		arg.DisplayName,
		arg.ProfileUrl,
		arg.AvatarUrl,
		arg.Status,
		arg.Provider,
		arg.ProviderRef,
		arg.Tags,
	)
	var i OfficialAccount
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Handle,
		&i.DisplayName,
		&i.ProfileUrl,
		&i.AvatarUrl,
		&i.Status,
		&i.Provider,
		&i.ProviderRef,
		&i.Tags,
		&i.LastFetchedAt,
		&i.CreatedAt,
	)
	return i, err
}
