// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: provision_log.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendProvisionLog = `-- name: AppendProvisionLog :exec

INSERT INTO provision_log (worker_id, op, generation, k8s_ref, status, error)
VALUES ($1, $2, $3, $4, $5, $6)
`

type AppendProvisionLogParams struct {
	WorkerID   pgtype.UUID `json:"worker_id"`
	Op         ProvisionOp `json:"op"`
	Generation int32       `json:"generation"`
	K8sRef     *string     `json:"k8s_ref"`
	Status     string      `json:"status"`
	Error      *string     `json:"error"`
}

// provision_log queries: append-only audit of every provisioner op.
func (q *Queries) AppendProvisionLog(ctx context.Context, arg AppendProvisionLogParams) error {
	_, err := q.db.Exec(ctx, appendProvisionLog,
		arg.WorkerID,
		arg.Op,
		arg.Generation,
		arg.K8sRef,
		arg.Status,
		arg.Error,
	)
	return err
}

const listProvisionLogsByWorker = `-- name: ListProvisionLogsByWorker :many
SELECT id, worker_id, op, generation, k8s_ref, status, error, ts FROM provision_log
WHERE worker_id = $1
ORDER BY ts DESC
LIMIT $2
`

type ListProvisionLogsByWorkerParams struct {
	WorkerID pgtype.UUID `json:"worker_id"`
	Limit    int32       `json:"limit"`
}

func (q *Queries) ListProvisionLogsByWorker(ctx context.Context, arg ListProvisionLogsByWorkerParams) ([]ProvisionLog, error) {
	rows, err := q.db.Query(ctx, listProvisionLogsByWorker, arg.WorkerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProvisionLog{}
	for rows.Next() {
		var i ProvisionLog
		if err := rows.Scan(
			&i.ID,
			&i.WorkerID,
			&i.Op,
			&i.Generation,
			&i.K8sRef,
			&i.Status,
			&i.Error,
			&i.Ts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
