// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: proxy_group.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProxyGroup = `-- name: CreateProxyGroup :one
INSERT INTO proxy_group (
    id, name, region, provider, pool_key, max_concurrency, daily_budget_mb
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, region, provider, pool_key, max_concurrency, daily_budget_mb, created_at
`

type CreateProxyGroupParams struct {
	ID             pgtype.UUID `json:"id"`
	Name           string      `json:"name"`
	Region         string      `json:"region"`
	Provider       string      `json:"provider"`
	PoolKey        []byte      `json:"pool_key"`
	MaxConcurrency int32       `json:"max_concurrency"`
	DailyBudgetMb  int32       `json:"daily_budget_mb"`
}

func (q *Queries) CreateProxyGroup(ctx context.Context, arg CreateProxyGroupParams) (ProxyGroup, error) {
	row := q.db.QueryRow(ctx, createProxyGroup,
		arg.ID,
		arg.Name,
		arg.Region,
		arg.Provider,
		arg.PoolKey,
		arg.MaxConcurrency,
		arg.DailyBudgetMb,
	)
	var i ProxyGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Region,
		&i.Provider,
		&i.PoolKey,
		&i.MaxConcurrency,
		&i.DailyBudgetMb,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProxyGroup = `-- name: DeleteProxyGroup :exec
DELETE FROM proxy_group WHERE id = $1
`

func (q *Queries) DeleteProxyGroup(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProxyGroup, id)
	return err
}

const getProxyGroupByID = `-- name: GetProxyGroupByID :one

SELECT id, name, region, provider, pool_key, max_concurrency, daily_budget_mb, created_at FROM proxy_group WHERE id = $1
`

// proxy_group queries. pool_key is encrypted at rest (AES-256-GCM, P1-07) and
// is only ever written by the credential-aware service, never decrypted here.
func (q *Queries) GetProxyGroupByID(ctx context.Context, id pgtype.UUID) (ProxyGroup, error) {
	row := q.db.QueryRow(ctx, getProxyGroupByID, id)
	var i ProxyGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Region,
		&i.Provider,
		&i.PoolKey,
		&i.MaxConcurrency,
		&i.DailyBudgetMb,
		&i.CreatedAt,
	)
	return i, err
}

const listProxyGroups = `-- name: ListProxyGroups :many
SELECT id, name, region, provider, pool_key, max_concurrency, daily_budget_mb, created_at FROM proxy_group ORDER BY created_at DESC
`

func (q *Queries) ListProxyGroups(ctx context.Context) ([]ProxyGroup, error) {
	rows, err := q.db.Query(ctx, listProxyGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProxyGroup{}
	for rows.Next() {
		var i ProxyGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Region,
			&i.Provider,
			&i.PoolKey,
			&i.MaxConcurrency,
			&i.DailyBudgetMb,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProxyGroup = `-- name: UpdateProxyGroup :one
UPDATE proxy_group SET
    name            = $2,
    region          = $3,
    provider        = $4,
    max_concurrency = $5,
    daily_budget_mb = $6
WHERE id = $1
RETURNING id, name, region, provider, pool_key, max_concurrency, daily_budget_mb, created_at
`

type UpdateProxyGroupParams struct {
	ID             pgtype.UUID `json:"id"`
	Name           string      `json:"name"`
	Region         string      `json:"region"`
	Provider       string      `json:"provider"`
	MaxConcurrency int32       `json:"max_concurrency"`
	DailyBudgetMb  int32       `json:"daily_budget_mb"`
}

func (q *Queries) UpdateProxyGroup(ctx context.Context, arg UpdateProxyGroupParams) (ProxyGroup, error) {
	row := q.db.QueryRow(ctx, updateProxyGroup,
		arg.ID,
		arg.Name,
		arg.Region,
		arg.Provider,
		arg.MaxConcurrency,
		arg.DailyBudgetMb,
	)
	var i ProxyGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Region,
		&i.Provider,
		&i.PoolKey,
		&i.MaxConcurrency,
		&i.DailyBudgetMb,
		&i.CreatedAt,
	)
	return i, err
}
