// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	// Example queries exercising the sqlc pipeline (P0-05).
	// Real per-domain query files land with their tables in later phases.
	GetTeamConfig(ctx context.Context) (TeamConfig, error)
	GetUserByEmail(ctx context.Context, lower string) (AppUser, error)
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error)
	ListAuditLogs(ctx context.Context, limit int32) ([]AuditLog, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	UpsertTeamConfig(ctx context.Context, name string) (TeamConfig, error)
}

var _ Querier = (*Queries)(nil)
