// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: report.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const actionRollupDaily = `-- name: ActionRollupDaily :many

SELECT
    date_trunc('day', aj.scheduled_at)::date                AS day,
    aj.account_id,
    a.username,
    a.platform,
    aj.type,
    count(*)                                                AS total,
    count(*) FILTER (WHERE aj.status = 'SUCCESS')           AS succeeded,
    count(*) FILTER (WHERE aj.status = 'FAILED')            AS failed
FROM action_job AS aj
JOIN account AS a ON a.id = aj.account_id
WHERE ($1::date IS NULL OR aj.scheduled_at >= $1)
  AND ($2::date IS NULL OR aj.scheduled_at < ($2::date + interval '1 day'))
  AND ($3::text IS NULL OR a.platform::text = $3)
  AND ($4::uuid IS NULL OR aj.account_id = $4)
GROUP BY day, aj.account_id, a.username, a.platform, aj.type
ORDER BY day, a.username, aj.type
`

type ActionRollupDailyParams struct {
	Column1 pgtype.Date `json:"column_1"`
	Column2 pgtype.Date `json:"column_2"`
	Column3 string      `json:"column_3"`
	Column4 pgtype.UUID `json:"column_4"`
}

type ActionRollupDailyRow struct {
	Day       pgtype.Date `json:"day"`
	AccountID pgtype.UUID `json:"account_id"`
	Username  string      `json:"username"`
	Platform  Platform    `json:"platform"`
	Type      JobType     `json:"type"`
	Total     int64       `json:"total"`
	Succeeded int64       `json:"succeeded"`
	Failed    int64       `json:"failed"`
}

// Report builder (P4-04 / P4-05). The dashboard's report view is a pivot over
// existing tables, not a new write path: everything here is a read that sums
// the action or analytics history the platform already stores.
// One row per (day, account, action type): the operator's "what did we do"
// report. status is projected from the job (the queue's own projection), so a
// re-run after a retry converges without double counting. NULL filters are the
// "all" case — the caller passes NULL, not an empty string.
func (q *Queries) ActionRollupDaily(ctx context.Context, arg ActionRollupDailyParams) ([]ActionRollupDailyRow, error) {
	rows, err := q.db.Query(ctx, actionRollupDaily,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionRollupDailyRow{}
	for rows.Next() {
		var i ActionRollupDailyRow
		if err := rows.Scan(
			&i.Day,
			&i.AccountID,
			&i.Username,
			&i.Platform,
			&i.Type,
			&i.Total,
			&i.Succeeded,
			&i.Failed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const actionTargetRollup = `-- name: ActionTargetRollup :many
SELECT
    t.id,
    t.url,
    t.platform,
    count(DISTINCT aj.id)                                   AS total,
    count(DISTINCT aj.id) FILTER (WHERE aj.status = 'SUCCESS') AS succeeded,
    count(DISTINCT aj.id) FILTER (WHERE aj.status = 'FAILED')  AS failed
FROM action_job AS aj
JOIN target AS t ON t.id = aj.target_id
WHERE ($1::date IS NULL OR aj.scheduled_at >= $1)
  AND ($2::date IS NULL OR aj.scheduled_at < ($2::date + interval '1 day'))
  AND ($3::text IS NULL OR t.platform::text = $3)
GROUP BY t.id, t.url, t.platform
ORDER BY total DESC
LIMIT 200
`

type ActionTargetRollupParams struct {
	Column1 pgtype.Date `json:"column_1"`
	Column2 pgtype.Date `json:"column_2"`
	Column3 string      `json:"column_3"`
}

type ActionTargetRollupRow struct {
	ID        pgtype.UUID `json:"id"`
	Url       string      `json:"url"`
	Platform  Platform    `json:"platform"`
	Total     int64       `json:"total"`
	Succeeded int64       `json:"succeeded"`
	Failed    int64       `json:"failed"`
}

// The per-target (post) view: the same jobs grouped by what they were aimed
// at, so a strategist can see which content attracted engagement.
func (q *Queries) ActionTargetRollup(ctx context.Context, arg ActionTargetRollupParams) ([]ActionTargetRollupRow, error) {
	rows, err := q.db.Query(ctx, actionTargetRollup, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionTargetRollupRow{}
	for rows.Next() {
		var i ActionTargetRollupRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Platform,
			&i.Total,
			&i.Succeeded,
			&i.Failed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
