// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: scrape_job.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextScrapeJob = `-- name: ClaimNextScrapeJob :one
UPDATE scrape_job
SET status     = 'RUNNING',
    started_at = now(),
    attempts   = attempts + 1
WHERE id = (
    SELECT sj.id
    FROM scrape_job AS sj
    WHERE sj.account_id = $1
      AND sj.status     = 'PENDING'
      AND sj.scheduled_at <= now()
    ORDER BY sj.scheduled_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, type, target_id, account_id, worker_id, status, scheduled_at,
          started_at, finished_at, attempts, error, created_at
`

// Atomic FIFO claim for one account: PENDING + scheduled_at <= now() ordered by
// scheduled_at, bumped to RUNNING. The account index makes this cheap.
func (q *Queries) ClaimNextScrapeJob(ctx context.Context, accountID pgtype.UUID) (ScrapeJob, error) {
	row := q.db.QueryRow(ctx, claimNextScrapeJob, accountID)
	var i ScrapeJob
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.TargetID,
		&i.AccountID,
		&i.WorkerID,
		&i.Status,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Attempts,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const completeScrapeJob = `-- name: CompleteScrapeJob :one
UPDATE scrape_job
SET status      = $2,
    finished_at = now(),
    error       = $3
WHERE id = $1
RETURNING id, type, target_id, account_id, worker_id, status, scheduled_at,
          started_at, finished_at, attempts, error, created_at
`

type CompleteScrapeJobParams struct {
	ID     pgtype.UUID `json:"id"`
	Status JobStatus   `json:"status"`
	Error  *string     `json:"error"`
}

func (q *Queries) CompleteScrapeJob(ctx context.Context, arg CompleteScrapeJobParams) (ScrapeJob, error) {
	row := q.db.QueryRow(ctx, completeScrapeJob, arg.ID, arg.Status, arg.Error)
	var i ScrapeJob
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.TargetID,
		&i.AccountID,
		&i.WorkerID,
		&i.Status,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Attempts,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const createApifyRun = `-- name: CreateApifyRun :one
INSERT INTO apify_run (scrape_job_id, actor_id, run_id, status)
VALUES ($1, $2, $3, $4)
RETURNING id, scrape_job_id, actor_id, run_id, status, started_at, finished_at
`

type CreateApifyRunParams struct {
	ScrapeJobID pgtype.UUID `json:"scrape_job_id"`
	ActorID     string      `json:"actor_id"`
	RunID       string      `json:"run_id"`
	Status      string      `json:"status"`
}

func (q *Queries) CreateApifyRun(ctx context.Context, arg CreateApifyRunParams) (ApifyRun, error) {
	row := q.db.QueryRow(ctx, createApifyRun,
		arg.ScrapeJobID,
		arg.ActorID,
		arg.RunID,
		arg.Status,
	)
	var i ApifyRun
	err := row.Scan(
		&i.ID,
		&i.ScrapeJobID,
		&i.ActorID,
		&i.RunID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createRawPayload = `-- name: CreateRawPayload :one
INSERT INTO raw_payload (apify_run_id, s3_key, bytes)
VALUES ($1, $2, $3)
RETURNING id, apify_run_id, s3_key, bytes, received_at
`

type CreateRawPayloadParams struct {
	ApifyRunID pgtype.UUID `json:"apify_run_id"`
	S3Key      string      `json:"s3_key"`
	Bytes      int64       `json:"bytes"`
}

func (q *Queries) CreateRawPayload(ctx context.Context, arg CreateRawPayloadParams) (RawPayload, error) {
	row := q.db.QueryRow(ctx, createRawPayload, arg.ApifyRunID, arg.S3Key, arg.Bytes)
	var i RawPayload
	err := row.Scan(
		&i.ID,
		&i.ApifyRunID,
		&i.S3Key,
		&i.Bytes,
		&i.ReceivedAt,
	)
	return i, err
}

const createScrapeJob = `-- name: CreateScrapeJob :one

INSERT INTO scrape_job (type, target_id, account_id, worker_id, status, scheduled_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, type, target_id, account_id, worker_id, status, scheduled_at,
          started_at, finished_at, attempts, error, created_at
`

type CreateScrapeJobParams struct {
	Type        JobType            `json:"type"`
	TargetID    pgtype.UUID        `json:"target_id"`
	AccountID   pgtype.UUID        `json:"account_id"`
	WorkerID    pgtype.UUID        `json:"worker_id"`
	Status      JobStatus          `json:"status"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
}

// ScrapeJob + ApifyRun + RawPayload: the scrape pipeline bookkeeping.
// ScrapeJob is claimed by a scheduler tick (FIFO per account via the index on
// (account_id, status, scheduled_at)); no unique constraint enqueues order.
func (q *Queries) CreateScrapeJob(ctx context.Context, arg CreateScrapeJobParams) (ScrapeJob, error) {
	row := q.db.QueryRow(ctx, createScrapeJob,
		arg.Type,
		arg.TargetID,
		arg.AccountID,
		arg.WorkerID,
		arg.Status,
		arg.ScheduledAt,
	)
	var i ScrapeJob
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.TargetID,
		&i.AccountID,
		&i.WorkerID,
		&i.Status,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Attempts,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const getScrapeJobByID = `-- name: GetScrapeJobByID :one
SELECT id, type, target_id, account_id, worker_id, status, scheduled_at,
       started_at, finished_at, attempts, error, created_at
FROM scrape_job
WHERE id = $1
`

func (q *Queries) GetScrapeJobByID(ctx context.Context, id pgtype.UUID) (ScrapeJob, error) {
	row := q.db.QueryRow(ctx, getScrapeJobByID, id)
	var i ScrapeJob
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.TargetID,
		&i.AccountID,
		&i.WorkerID,
		&i.Status,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Attempts,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingScrapeJobsByAccount = `-- name: ListPendingScrapeJobsByAccount :many
SELECT id, type, target_id, account_id, worker_id, status, scheduled_at,
       started_at, finished_at, attempts, error, created_at
FROM scrape_job
WHERE account_id = $1
  AND status     = 'PENDING'
ORDER BY scheduled_at
LIMIT $2
`

type ListPendingScrapeJobsByAccountParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) ListPendingScrapeJobsByAccount(ctx context.Context, arg ListPendingScrapeJobsByAccountParams) ([]ScrapeJob, error) {
	rows, err := q.db.Query(ctx, listPendingScrapeJobsByAccount, arg.AccountID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScrapeJob{}
	for rows.Next() {
		var i ScrapeJob
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.TargetID,
			&i.AccountID,
			&i.WorkerID,
			&i.Status,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Attempts,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRawPayloadsByRun = `-- name: ListRawPayloadsByRun :many
SELECT s3_key
FROM raw_payload
WHERE apify_run_id = $1
ORDER BY received_at
`

func (q *Queries) ListRawPayloadsByRun(ctx context.Context, apifyRunID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listRawPayloadsByRun, apifyRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var s3_key string
		if err := rows.Scan(&s3_key); err != nil {
			return nil, err
		}
		items = append(items, s3_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScrapeJobs = `-- name: ListScrapeJobs :many
SELECT id, type, target_id, account_id, worker_id, status, scheduled_at,
       started_at, finished_at, attempts, error, created_at
FROM scrape_job
ORDER BY scheduled_at DESC
LIMIT $1 OFFSET $2
`

type ListScrapeJobsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListScrapeJobs(ctx context.Context, arg ListScrapeJobsParams) ([]ScrapeJob, error) {
	rows, err := q.db.Query(ctx, listScrapeJobs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScrapeJob{}
	for rows.Next() {
		var i ScrapeJob
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.TargetID,
			&i.AccountID,
			&i.WorkerID,
			&i.Status,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Attempts,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScrapeJobsByStatus = `-- name: ListScrapeJobsByStatus :many
SELECT id, type, target_id, account_id, worker_id, status, scheduled_at,
       started_at, finished_at, attempts, error, created_at
FROM scrape_job
WHERE status = $1
ORDER BY scheduled_at
LIMIT $2 OFFSET $3
`

type ListScrapeJobsByStatusParams struct {
	Status JobStatus `json:"status"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListScrapeJobsByStatus(ctx context.Context, arg ListScrapeJobsByStatusParams) ([]ScrapeJob, error) {
	rows, err := q.db.Query(ctx, listScrapeJobsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScrapeJob{}
	for rows.Next() {
		var i ScrapeJob
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.TargetID,
			&i.AccountID,
			&i.WorkerID,
			&i.Status,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Attempts,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rescheduleScrapeJob = `-- name: RescheduleScrapeJob :one
UPDATE scrape_job
SET status       = 'PENDING',
    scheduled_at = $2,
    finished_at  = NULL
WHERE id = $1
RETURNING id, type, target_id, account_id, worker_id, status, scheduled_at,
          started_at, finished_at, attempts, error, created_at
`

type RescheduleScrapeJobParams struct {
	ID          pgtype.UUID        `json:"id"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
}

// Moves a job back into the queue at a later time. Used by the scheduler's
// backoff/jitter path: the job is set PENDING and its scheduled_at pushed out,
// so the next eligible tick claims it again.
func (q *Queries) RescheduleScrapeJob(ctx context.Context, arg RescheduleScrapeJobParams) (ScrapeJob, error) {
	row := q.db.QueryRow(ctx, rescheduleScrapeJob, arg.ID, arg.ScheduledAt)
	var i ScrapeJob
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.TargetID,
		&i.AccountID,
		&i.WorkerID,
		&i.Status,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Attempts,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const updateApifyRun = `-- name: UpdateApifyRun :one
UPDATE apify_run
SET status      = $2,
    finished_at = $3
WHERE id = $1
RETURNING id, scrape_job_id, actor_id, run_id, status, started_at, finished_at
`

type UpdateApifyRunParams struct {
	ID         pgtype.UUID        `json:"id"`
	Status     string             `json:"status"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}

// finished_at is passed in (NULL while the run is still in flight) so the caller
// controls the terminal stamp without a CASE in SQL.
func (q *Queries) UpdateApifyRun(ctx context.Context, arg UpdateApifyRunParams) (ApifyRun, error) {
	row := q.db.QueryRow(ctx, updateApifyRun, arg.ID, arg.Status, arg.FinishedAt)
	var i ApifyRun
	err := row.Scan(
		&i.ID,
		&i.ScrapeJobID,
		&i.ActorID,
		&i.RunID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}
