// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: target.sql

package sqlcgen

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTargetByID = `-- name: GetTargetByID :one

SELECT id, kind, platform, external_id, url, meta, post_id, comment_id, created_at
FROM target
WHERE id = $1
`

// Target: the scrape/action join point. Deduped by (platform, external_id).
// Upsert returns the canonical row so callers get an id whether it existed or
// not; the resolution columns (post_id/comment_id) are filled in by the ingest
// pipeline once the entity exists, not at target-create time.
func (q *Queries) GetTargetByID(ctx context.Context, id pgtype.UUID) (Target, error) {
	row := q.db.QueryRow(ctx, getTargetByID, id)
	var i Target
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Platform,
		&i.ExternalID,
		&i.Url,
		&i.Meta,
		&i.PostID,
		&i.CommentID,
		&i.CreatedAt,
	)
	return i, err
}

const getTargetByPlatformExternalID = `-- name: GetTargetByPlatformExternalID :one
SELECT id, kind, platform, external_id, url, meta, post_id, comment_id, created_at
FROM target
WHERE platform = $1 AND external_id = $2
`

type GetTargetByPlatformExternalIDParams struct {
	Platform   Platform `json:"platform"`
	ExternalID string   `json:"external_id"`
}

func (q *Queries) GetTargetByPlatformExternalID(ctx context.Context, arg GetTargetByPlatformExternalIDParams) (Target, error) {
	row := q.db.QueryRow(ctx, getTargetByPlatformExternalID, arg.Platform, arg.ExternalID)
	var i Target
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Platform,
		&i.ExternalID,
		&i.Url,
		&i.Meta,
		&i.PostID,
		&i.CommentID,
		&i.CreatedAt,
	)
	return i, err
}

const linkTargetComment = `-- name: LinkTargetComment :exec
UPDATE target SET comment_id = $2 WHERE id = $1
`

type LinkTargetCommentParams struct {
	ID        pgtype.UUID `json:"id"`
	CommentID pgtype.UUID `json:"comment_id"`
}

func (q *Queries) LinkTargetComment(ctx context.Context, arg LinkTargetCommentParams) error {
	_, err := q.db.Exec(ctx, linkTargetComment, arg.ID, arg.CommentID)
	return err
}

const linkTargetPost = `-- name: LinkTargetPost :exec
UPDATE target SET post_id = $2 WHERE id = $1
`

type LinkTargetPostParams struct {
	ID     pgtype.UUID `json:"id"`
	PostID pgtype.UUID `json:"post_id"`
}

func (q *Queries) LinkTargetPost(ctx context.Context, arg LinkTargetPostParams) error {
	_, err := q.db.Exec(ctx, linkTargetPost, arg.ID, arg.PostID)
	return err
}

const listTargets = `-- name: ListTargets :many
SELECT id, kind, platform, external_id, url, meta, post_id, comment_id, created_at
FROM target
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListTargetsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTargets(ctx context.Context, arg ListTargetsParams) ([]Target, error) {
	rows, err := q.db.Query(ctx, listTargets, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Target{}
	for rows.Next() {
		var i Target
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Platform,
			&i.ExternalID,
			&i.Url,
			&i.Meta,
			&i.PostID,
			&i.CommentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTarget = `-- name: UpsertTarget :one
INSERT INTO target (kind, platform, external_id, url, meta)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (platform, external_id) DO UPDATE
SET url = EXCLUDED.url,
    meta = EXCLUDED.meta
RETURNING id, kind, platform, external_id, url, meta, post_id, comment_id, created_at
`

type UpsertTargetParams struct {
	Kind       TargetKind      `json:"kind"`
	Platform   Platform        `json:"platform"`
	ExternalID string          `json:"external_id"`
	Url        string          `json:"url"`
	Meta       json.RawMessage `json:"meta"`
}

func (q *Queries) UpsertTarget(ctx context.Context, arg UpsertTargetParams) (Target, error) {
	row := q.db.QueryRow(ctx, upsertTarget,
		arg.Kind,
		arg.Platform,
		arg.ExternalID,
		arg.Url,
		arg.Meta,
	)
	var i Target
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Platform,
		&i.ExternalID,
		&i.Url,
		&i.Meta,
		&i.PostID,
		&i.CommentID,
		&i.CreatedAt,
	)
	return i, err
}
