// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: template.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCommentTemplate = `-- name: CreateCommentTemplate :one

INSERT INTO comment_template (platform, text, vars, weight, banned_words, is_active)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, platform, text, vars, weight, banned_words, is_active, created_at
`

type CreateCommentTemplateParams struct {
	Platform    Platform `json:"platform"`
	Text        string   `json:"text"`
	Vars        []string `json:"vars"`
	Weight      int32    `json:"weight"`
	BannedWords []string `json:"banned_words"`
	IsActive    bool     `json:"is_active"`
}

// CommentTemplate (P3-02): the comment pool. A template is platform-scoped,
// declares the vars its text may reference ({topic}), carries a pick weight and
// a per-template denylist, and can be soft-disabled without deleting the rows
// that explain past action_logs.
//
// Dedupe: PickForTarget excludes any template already used against THIS target
// in the last 7 days, so the same variant does not repeat on one post. It is a
// query, not a constraint: a CHECK cannot express a temporal join, and dedupe
// is a pool property (which variants are still fresh), not a row property.
func (q *Queries) CreateCommentTemplate(ctx context.Context, arg CreateCommentTemplateParams) (CommentTemplate, error) {
	row := q.db.QueryRow(ctx, createCommentTemplate,
		arg.Platform,
		arg.Text,
		arg.Vars,
		arg.Weight,
		arg.BannedWords,
		arg.IsActive,
	)
	var i CommentTemplate
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Text,
		&i.Vars,
		&i.Weight,
		&i.BannedWords,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCommentTemplate = `-- name: DeleteCommentTemplate :exec
DELETE FROM comment_template WHERE id = $1
`

// Hard delete is allowed: ON DELETE SET NULL keeps the history readable, it
// only loses the link to the variant's definition.
func (q *Queries) DeleteCommentTemplate(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCommentTemplate, id)
	return err
}

const getCommentTemplateByID = `-- name: GetCommentTemplateByID :one
SELECT id, platform, text, vars, weight, banned_words, is_active, created_at
FROM comment_template
WHERE id = $1
`

func (q *Queries) GetCommentTemplateByID(ctx context.Context, id pgtype.UUID) (CommentTemplate, error) {
	row := q.db.QueryRow(ctx, getCommentTemplateByID, id)
	var i CommentTemplate
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Text,
		&i.Vars,
		&i.Weight,
		&i.BannedWords,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listCommentTemplates = `-- name: ListCommentTemplates :many
SELECT id, platform, text, vars, weight, banned_words, is_active, created_at
FROM comment_template
WHERE platform = $1
  AND ($2::boolean OR is_active = TRUE)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListCommentTemplatesParams struct {
	Platform Platform `json:"platform"`
	Column2  bool     `json:"column_2"`
	Limit    int32    `json:"limit"`
	Offset   int32    `json:"offset"`
}

// The pool view for one platform. include_inactive is the dashboard's
// "show paused variants" toggle; the pool a pick draws from is always active-only
// (see PickForTarget).
func (q *Queries) ListCommentTemplates(ctx context.Context, arg ListCommentTemplatesParams) ([]CommentTemplate, error) {
	rows, err := q.db.Query(ctx, listCommentTemplates,
		arg.Platform,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CommentTemplate{}
	for rows.Next() {
		var i CommentTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.Text,
			&i.Vars,
			&i.Weight,
			&i.BannedWords,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pickForTarget = `-- name: PickForTarget :many
SELECT t.id, t.platform, t.text, t.vars, t.weight, t.banned_words, t.is_active,
       t.created_at
FROM comment_template AS t
WHERE t.platform  = $1
  AND t.is_active = TRUE
  AND NOT EXISTS (
      SELECT 1
      FROM action_log AS al
      WHERE al.template_id = t.id
        AND al.action_job_id IN (
            SELECT aj.id
            FROM action_job AS aj
            WHERE aj.target_id = $2
        )
        AND al.ts >= now() - INTERVAL '7 days'
  )
ORDER BY t.weight DESC, t.created_at
`

type PickForTargetParams struct {
	Platform Platform    `json:"platform"`
	TargetID pgtype.UUID `json:"target_id"`
}

// The dedupe pool for one (platform, target): every active template that has
// NOT been used against this target in the last 7 days, heaviest first. The
// caller does the weighted random pick over this candidate set (see the
// template service) — weighting in SQL needs a seed and is harder to test.
func (q *Queries) PickForTarget(ctx context.Context, arg PickForTargetParams) ([]CommentTemplate, error) {
	rows, err := q.db.Query(ctx, pickForTarget, arg.Platform, arg.TargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CommentTemplate{}
	for rows.Next() {
		var i CommentTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.Text,
			&i.Vars,
			&i.Weight,
			&i.BannedWords,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCommentTemplate = `-- name: UpdateCommentTemplate :one
UPDATE comment_template
SET text         = $2,
    vars         = $3,
    weight       = $4,
    banned_words = $5,
    is_active    = $6
WHERE id = $1
RETURNING id, platform, text, vars, weight, banned_words, is_active, created_at
`

type UpdateCommentTemplateParams struct {
	ID          pgtype.UUID `json:"id"`
	Text        string      `json:"text"`
	Vars        []string    `json:"vars"`
	Weight      int32       `json:"weight"`
	BannedWords []string    `json:"banned_words"`
	IsActive    bool        `json:"is_active"`
}

// Full-row update: weight/vars/banned_words/is_active all change together from
// the composer, so a partial-update builder would only hide a missed field.
func (q *Queries) UpdateCommentTemplate(ctx context.Context, arg UpdateCommentTemplateParams) (CommentTemplate, error) {
	row := q.db.QueryRow(ctx, updateCommentTemplate,
		arg.ID,
		arg.Text,
		arg.Vars,
		arg.Weight,
		arg.BannedWords,
		arg.IsActive,
	)
	var i CommentTemplate
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Text,
		&i.Vars,
		&i.Weight,
		&i.BannedWords,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
