// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: worker.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorker = `-- name: CreateWorker :one
INSERT INTO worker (
    name, container_id, control_channel, action_queue, session_pvc,
    novnc_service, desired_state, source, region, status, generation,
    image_version, location, latitude, longitude
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
RETURNING id, name, container_id, control_channel, action_queue, session_pvc, novnc_service, desired_state, source, region, status, generation, observed_gen, provision_err, browser_status, current_job_id, last_heartbeat, last_action_at, last_error, queue_depth, restart_count, image_version, created_at, location, latitude, longitude
`

type CreateWorkerParams struct {
	Name           string       `json:"name"`
	ContainerID    *string      `json:"container_id"`
	ControlChannel *string      `json:"control_channel"`
	ActionQueue    *string      `json:"action_queue"`
	SessionPvc     *string      `json:"session_pvc"`
	NovncService   *string      `json:"novnc_service"`
	DesiredState   DesiredState `json:"desired_state"`
	Source         WorkerSource `json:"source"`
	Region         string       `json:"region"`
	Status         WorkerStatus `json:"status"`
	Generation     int32        `json:"generation"`
	ImageVersion   string       `json:"image_version"`
	Location       *string      `json:"location"`
	Latitude       *float64     `json:"latitude"`
	Longitude      *float64     `json:"longitude"`
}

func (q *Queries) CreateWorker(ctx context.Context, arg CreateWorkerParams) (Worker, error) {
	row := q.db.QueryRow(ctx, createWorker,
		arg.Name,
		arg.ContainerID,
		arg.ControlChannel,
		arg.ActionQueue,
		arg.SessionPvc,
		arg.NovncService,
		arg.DesiredState,
		arg.Source,
		arg.Region,
		arg.Status,
		arg.Generation,
		arg.ImageVersion,
		arg.Location,
		arg.Latitude,
		arg.Longitude,
	)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContainerID,
		&i.ControlChannel,
		&i.ActionQueue,
		&i.SessionPvc,
		&i.NovncService,
		&i.DesiredState,
		&i.Source,
		&i.Region,
		&i.Status,
		&i.Generation,
		&i.ObservedGen,
		&i.ProvisionErr,
		&i.BrowserStatus,
		&i.CurrentJobID,
		&i.LastHeartbeat,
		&i.LastActionAt,
		&i.LastError,
		&i.QueueDepth,
		&i.RestartCount,
		&i.ImageVersion,
		&i.CreatedAt,
		&i.Location,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const deleteWorker = `-- name: DeleteWorker :exec
DELETE FROM worker WHERE id = $1
`

func (q *Queries) DeleteWorker(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorker, id)
	return err
}

const getWorkerByID = `-- name: GetWorkerByID :one

SELECT id, name, container_id, control_channel, action_queue, session_pvc, novnc_service, desired_state, source, region, status, generation, observed_gen, provision_err, browser_status, current_job_id, last_heartbeat, last_action_at, last_error, queue_depth, restart_count, image_version, created_at, location, latitude, longitude FROM worker WHERE id = $1
`

// Worker (container) lifecycle queries. One worker = one container hosting
// at most one account per platform (UNIQUE(worker_id, platform) on account).
// generation guards idempotent reconcile (pod label smm.generation).
func (q *Queries) GetWorkerByID(ctx context.Context, id pgtype.UUID) (Worker, error) {
	row := q.db.QueryRow(ctx, getWorkerByID, id)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContainerID,
		&i.ControlChannel,
		&i.ActionQueue,
		&i.SessionPvc,
		&i.NovncService,
		&i.DesiredState,
		&i.Source,
		&i.Region,
		&i.Status,
		&i.Generation,
		&i.ObservedGen,
		&i.ProvisionErr,
		&i.BrowserStatus,
		&i.CurrentJobID,
		&i.LastHeartbeat,
		&i.LastActionAt,
		&i.LastError,
		&i.QueueDepth,
		&i.RestartCount,
		&i.ImageVersion,
		&i.CreatedAt,
		&i.Location,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const getWorkerByName = `-- name: GetWorkerByName :one
SELECT id, name, container_id, control_channel, action_queue, session_pvc, novnc_service, desired_state, source, region, status, generation, observed_gen, provision_err, browser_status, current_job_id, last_heartbeat, last_action_at, last_error, queue_depth, restart_count, image_version, created_at, location, latitude, longitude FROM worker WHERE name = $1
`

func (q *Queries) GetWorkerByName(ctx context.Context, name string) (Worker, error) {
	row := q.db.QueryRow(ctx, getWorkerByName, name)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContainerID,
		&i.ControlChannel,
		&i.ActionQueue,
		&i.SessionPvc,
		&i.NovncService,
		&i.DesiredState,
		&i.Source,
		&i.Region,
		&i.Status,
		&i.Generation,
		&i.ObservedGen,
		&i.ProvisionErr,
		&i.BrowserStatus,
		&i.CurrentJobID,
		&i.LastHeartbeat,
		&i.LastActionAt,
		&i.LastError,
		&i.QueueDepth,
		&i.RestartCount,
		&i.ImageVersion,
		&i.CreatedAt,
		&i.Location,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const insertHeartbeat = `-- name: InsertHeartbeat :exec
INSERT INTO heartbeat (worker_id, ts, cpu, mem, jobs_done)
VALUES ($1, $2, $3, $4, $5)
`

type InsertHeartbeatParams struct {
	WorkerID pgtype.UUID        `json:"worker_id"`
	Ts       pgtype.Timestamptz `json:"ts"`
	Cpu      float64            `json:"cpu"`
	Mem      float64            `json:"mem"`
	JobsDone int32              `json:"jobs_done"`
}

func (q *Queries) InsertHeartbeat(ctx context.Context, arg InsertHeartbeatParams) error {
	_, err := q.db.Exec(ctx, insertHeartbeat,
		arg.WorkerID,
		arg.Ts,
		arg.Cpu,
		arg.Mem,
		arg.JobsDone,
	)
	return err
}

const listWorkers = `-- name: ListWorkers :many
SELECT id, name, container_id, control_channel, action_queue, session_pvc, novnc_service, desired_state, source, region, status, generation, observed_gen, provision_err, browser_status, current_job_id, last_heartbeat, last_action_at, last_error, queue_depth, restart_count, image_version, created_at, location, latitude, longitude FROM worker
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListWorkersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListWorkers(ctx context.Context, arg ListWorkersParams) ([]Worker, error) {
	rows, err := q.db.Query(ctx, listWorkers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Worker{}
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ContainerID,
			&i.ControlChannel,
			&i.ActionQueue,
			&i.SessionPvc,
			&i.NovncService,
			&i.DesiredState,
			&i.Source,
			&i.Region,
			&i.Status,
			&i.Generation,
			&i.ObservedGen,
			&i.ProvisionErr,
			&i.BrowserStatus,
			&i.CurrentJobID,
			&i.LastHeartbeat,
			&i.LastActionAt,
			&i.LastError,
			&i.QueueDepth,
			&i.RestartCount,
			&i.ImageVersion,
			&i.CreatedAt,
			&i.Location,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchWorkerHeartbeat = `-- name: TouchWorkerHeartbeat :one
UPDATE worker SET
    last_heartbeat = $2,
    status         = $3,
    browser_status = $4,
    queue_depth    = $5,
    current_job_id = $6,
    novnc_service  = $7
WHERE id = $1
RETURNING id, name, container_id, control_channel, action_queue, session_pvc, novnc_service, desired_state, source, region, status, generation, observed_gen, provision_err, browser_status, current_job_id, last_heartbeat, last_action_at, last_error, queue_depth, restart_count, image_version, created_at, location, latitude, longitude
`

type TouchWorkerHeartbeatParams struct {
	ID            pgtype.UUID        `json:"id"`
	LastHeartbeat pgtype.Timestamptz `json:"last_heartbeat"`
	Status        WorkerStatus       `json:"status"`
	BrowserStatus string             `json:"browser_status"`
	QueueDepth    int32              `json:"queue_depth"`
	CurrentJobID  pgtype.UUID        `json:"current_job_id"`
	NovncService  *string            `json:"novnc_service"`
}

func (q *Queries) TouchWorkerHeartbeat(ctx context.Context, arg TouchWorkerHeartbeatParams) (Worker, error) {
	row := q.db.QueryRow(ctx, touchWorkerHeartbeat,
		arg.ID,
		arg.LastHeartbeat,
		arg.Status,
		arg.BrowserStatus,
		arg.QueueDepth,
		arg.CurrentJobID,
		arg.NovncService,
	)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContainerID,
		&i.ControlChannel,
		&i.ActionQueue,
		&i.SessionPvc,
		&i.NovncService,
		&i.DesiredState,
		&i.Source,
		&i.Region,
		&i.Status,
		&i.Generation,
		&i.ObservedGen,
		&i.ProvisionErr,
		&i.BrowserStatus,
		&i.CurrentJobID,
		&i.LastHeartbeat,
		&i.LastActionAt,
		&i.LastError,
		&i.QueueDepth,
		&i.RestartCount,
		&i.ImageVersion,
		&i.CreatedAt,
		&i.Location,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const updateWorker = `-- name: UpdateWorker :one
UPDATE worker SET
    container_id   = $2,
    desired_state  = $3,
    status         = $4,
    generation     = $5,
    observed_gen   = $6,
    provision_err  = $7,
    browser_status = $8,
    current_job_id = $9,
    last_heartbeat = $10,
    last_action_at = $11,
    last_error     = $12,
    queue_depth    = $13,
    restart_count  = $14
WHERE id = $1
RETURNING id, name, container_id, control_channel, action_queue, session_pvc, novnc_service, desired_state, source, region, status, generation, observed_gen, provision_err, browser_status, current_job_id, last_heartbeat, last_action_at, last_error, queue_depth, restart_count, image_version, created_at, location, latitude, longitude
`

type UpdateWorkerParams struct {
	ID            pgtype.UUID        `json:"id"`
	ContainerID   *string            `json:"container_id"`
	DesiredState  DesiredState       `json:"desired_state"`
	Status        WorkerStatus       `json:"status"`
	Generation    int32              `json:"generation"`
	ObservedGen   *int32             `json:"observed_gen"`
	ProvisionErr  *string            `json:"provision_err"`
	BrowserStatus string             `json:"browser_status"`
	CurrentJobID  pgtype.UUID        `json:"current_job_id"`
	LastHeartbeat pgtype.Timestamptz `json:"last_heartbeat"`
	LastActionAt  pgtype.Timestamptz `json:"last_action_at"`
	LastError     *string            `json:"last_error"`
	QueueDepth    int32              `json:"queue_depth"`
	RestartCount  int32              `json:"restart_count"`
}

func (q *Queries) UpdateWorker(ctx context.Context, arg UpdateWorkerParams) (Worker, error) {
	row := q.db.QueryRow(ctx, updateWorker,
		arg.ID,
		arg.ContainerID,
		arg.DesiredState,
		arg.Status,
		arg.Generation,
		arg.ObservedGen,
		arg.ProvisionErr,
		arg.BrowserStatus,
		arg.CurrentJobID,
		arg.LastHeartbeat,
		arg.LastActionAt,
		arg.LastError,
		arg.QueueDepth,
		arg.RestartCount,
	)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContainerID,
		&i.ControlChannel,
		&i.ActionQueue,
		&i.SessionPvc,
		&i.NovncService,
		&i.DesiredState,
		&i.Source,
		&i.Region,
		&i.Status,
		&i.Generation,
		&i.ObservedGen,
		&i.ProvisionErr,
		&i.BrowserStatus,
		&i.CurrentJobID,
		&i.LastHeartbeat,
		&i.LastActionAt,
		&i.LastError,
		&i.QueueDepth,
		&i.RestartCount,
		&i.ImageVersion,
		&i.CreatedAt,
		&i.Location,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}
