// Package oapigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package oapigen

import (
	"time"

	"github.com/oapi-codegen/nullable"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	AccessCookieScopes = "accessCookie.Scopes"
)

// Defines values for AccountAuthStatus.
const (
	AccountAuthStatusAUTHENTICATED  AccountAuthStatus = "AUTHENTICATED"
	AccountAuthStatusAUTHENTICATING AccountAuthStatus = "AUTHENTICATING"
	AccountAuthStatusFAILED         AccountAuthStatus = "FAILED"
	AccountAuthStatusNEEDSINPUT     AccountAuthStatus = "NEEDS_INPUT"
	AccountAuthStatusQUARANTINED    AccountAuthStatus = "QUARANTINED"
)

// Defines values for AccountPlatform.
const (
	AccountPlatformFacebook  AccountPlatform = "facebook"
	AccountPlatformInstagram AccountPlatform = "instagram"
	AccountPlatformLinkedin  AccountPlatform = "linkedin"
	AccountPlatformThreads   AccountPlatform = "threads"
	AccountPlatformTiktok    AccountPlatform = "tiktok"
	AccountPlatformX         AccountPlatform = "x"
	AccountPlatformYoutube   AccountPlatform = "youtube"
)

// Defines values for AccountStatus.
const (
	AccountStatusACTIVE   AccountStatus = "ACTIVE"
	AccountStatusARCHIVED AccountStatus = "ARCHIVED"
	AccountStatusDEAD     AccountStatus = "DEAD"
	AccountStatusPAUSED   AccountStatus = "PAUSED"
)

// Defines values for AttemptStatus.
const (
	AttemptStatusCANCELLED AttemptStatus = "CANCELLED"
	AttemptStatusFAILED    AttemptStatus = "FAILED"
	AttemptStatusRETRY     AttemptStatus = "RETRY"
	AttemptStatusSUCCESS   AttemptStatus = "SUCCESS"
)

// Defines values for AuthStatus.
const (
	AuthStatusAUTHENTICATED  AuthStatus = "AUTHENTICATED"
	AuthStatusAUTHENTICATING AuthStatus = "AUTHENTICATING"
	AuthStatusFAILED         AuthStatus = "FAILED"
	AuthStatusNEEDSINPUT     AuthStatus = "NEEDS_INPUT"
)

// Defines values for ContainerDesiredState.
const (
	RUNNING ContainerDesiredState = "RUNNING"
	STOPPED ContainerDesiredState = "STOPPED"
)

// Defines values for ContainerSource.
const (
	AUTO   ContainerSource = "AUTO"
	MANUAL ContainerSource = "MANUAL"
)

// Defines values for ContainerStatus.
const (
	ContainerStatusBUSY        ContainerStatus = "BUSY"
	ContainerStatusDEAD        ContainerStatus = "DEAD"
	ContainerStatusDRAINING    ContainerStatus = "DRAINING"
	ContainerStatusERROR       ContainerStatus = "ERROR"
	ContainerStatusIDLE        ContainerStatus = "IDLE"
	ContainerStatusPENDING     ContainerStatus = "PENDING"
	ContainerStatusQUARANTINED ContainerStatus = "QUARANTINED"
	ContainerStatusREADY       ContainerStatus = "READY"
)

// Defines values for ContainerAccountAuthStatus.
const (
	ContainerAccountAuthStatusAUTHENTICATED  ContainerAccountAuthStatus = "AUTHENTICATED"
	ContainerAccountAuthStatusAUTHENTICATING ContainerAccountAuthStatus = "AUTHENTICATING"
	ContainerAccountAuthStatusFAILED         ContainerAccountAuthStatus = "FAILED"
	ContainerAccountAuthStatusNEEDSINPUT     ContainerAccountAuthStatus = "NEEDS_INPUT"
	ContainerAccountAuthStatusQUARANTINED    ContainerAccountAuthStatus = "QUARANTINED"
)

// Defines values for ContainerAccountPlatform.
const (
	ContainerAccountPlatformFacebook  ContainerAccountPlatform = "facebook"
	ContainerAccountPlatformInstagram ContainerAccountPlatform = "instagram"
	ContainerAccountPlatformLinkedin  ContainerAccountPlatform = "linkedin"
	ContainerAccountPlatformThreads   ContainerAccountPlatform = "threads"
	ContainerAccountPlatformTiktok    ContainerAccountPlatform = "tiktok"
	ContainerAccountPlatformX         ContainerAccountPlatform = "x"
	ContainerAccountPlatformYoutube   ContainerAccountPlatform = "youtube"
)

// Defines values for ContainerAccountStatus.
const (
	ContainerAccountStatusACTIVE   ContainerAccountStatus = "ACTIVE"
	ContainerAccountStatusARCHIVED ContainerAccountStatus = "ARCHIVED"
	ContainerAccountStatusDEAD     ContainerAccountStatus = "DEAD"
	ContainerAccountStatusPAUSED   ContainerAccountStatus = "PAUSED"
)

// Defines values for CreateAccountRequestPlatform.
const (
	Facebook  CreateAccountRequestPlatform = "facebook"
	Instagram CreateAccountRequestPlatform = "instagram"
	Linkedin  CreateAccountRequestPlatform = "linkedin"
	Threads   CreateAccountRequestPlatform = "threads"
	Tiktok    CreateAccountRequestPlatform = "tiktok"
	X         CreateAccountRequestPlatform = "x"
	Youtube   CreateAccountRequestPlatform = "youtube"
)

// Defines values for HeartbeatBrowserStatus.
const (
	HeartbeatBrowserStatusBusy  HeartbeatBrowserStatus = "busy"
	HeartbeatBrowserStatusCold  HeartbeatBrowserStatus = "cold"
	HeartbeatBrowserStatusError HeartbeatBrowserStatus = "error"
	HeartbeatBrowserStatusReady HeartbeatBrowserStatus = "ready"
)

// Defines values for ReadinessStatusStatus.
const (
	Degraded ReadinessStatusStatus = "degraded"
	Ok       ReadinessStatusStatus = "ok"
)

// Defines values for Role.
const (
	ANALYST    Role = "ANALYST"
	OPERATOR   Role = "OPERATOR"
	OWNER      Role = "OWNER"
	STRATEGIST Role = "STRATEGIST"
)

// Defines values for SetAccountStatusRequestStatus.
const (
	SetAccountStatusRequestStatusACTIVE SetAccountStatusRequestStatus = "ACTIVE"
	SetAccountStatusRequestStatusPAUSED SetAccountStatusRequestStatus = "PAUSED"
)

// Defines values for StreamEventKind.
const (
	AccountUpdated   StreamEventKind = "account-updated"
	ProvisionUpdated StreamEventKind = "provision-updated"
	WorkerHealth     StreamEventKind = "worker-health"
)

// Account defines model for Account.
type Account struct {
	AuthStatus AccountAuthStatus         `json:"authStatus"`
	Handle     nullable.Nullable[string] `json:"handle,omitempty"`
	Id         string                    `json:"id"`
	LastError  nullable.Nullable[string] `json:"lastError,omitempty"`
	Platform   AccountPlatform           `json:"platform"`
	Status     AccountStatus             `json:"status"`
	Tags       *[]string                 `json:"tags,omitempty"`
	Username   string                    `json:"username"`
	WorkerId   nullable.Nullable[string] `json:"workerId,omitempty"`
}

// AccountAuthStatus defines model for Account.AuthStatus.
type AccountAuthStatus string

// AccountPlatform defines model for Account.Platform.
type AccountPlatform string

// AccountStatus defines model for Account.Status.
type AccountStatus string

// AccountCallback defines model for AccountCallback.
type AccountCallback struct {
	AccountId  string     `json:"accountId"`
	AuthStatus AuthStatus `json:"authStatus"`
	Error      *string    `json:"error,omitempty"`

	// Handle Verified platform handle, set after a successful login.
	Handle *string `json:"handle,omitempty"`
}

// AccountList defines model for AccountList.
type AccountList struct {
	Accounts []Account `json:"accounts"`
}

// ActionCallback defines model for ActionCallback.
type ActionCallback struct {
	// ActionType e.g. like, comment, report.
	ActionType *string `json:"actionType,omitempty"`
	AttemptId  string  `json:"attemptId"`
	Error      *string `json:"error,omitempty"`

	// ScreenshotPath File name only; the server applies path.Base and requires .png.
	ScreenshotPath *string       `json:"screenshotPath,omitempty"`
	Status         AttemptStatus `json:"status"`
	TargetUrl      *string       `json:"targetUrl,omitempty"`
	WorkerId       *string       `json:"workerId,omitempty"`
}

// AttemptStatus defines model for AttemptStatus.
type AttemptStatus string

// AuthStatus defines model for AuthStatus.
type AuthStatus string

// CallbackAck defines model for CallbackAck.
type CallbackAck struct {
	Accepted bool `json:"accepted"`
}

// Container defines model for Container.
type Container struct {
	Accounts           *[]ContainerAccount    `json:"accounts,omitempty"`
	CreatedAt          time.Time              `json:"createdAt"`
	DesiredState       ContainerDesiredState  `json:"desiredState"`
	Generation         int                    `json:"generation"`
	Id                 string                 `json:"id"`
	Name               string                 `json:"name"`
	ObservedGeneration nullable.Nullable[int] `json:"observedGeneration,omitempty"`
	Region             string                 `json:"region"`
	Source             ContainerSource        `json:"source"`
	Status             ContainerStatus        `json:"status"`
}

// ContainerDesiredState defines model for Container.DesiredState.
type ContainerDesiredState string

// ContainerSource defines model for Container.Source.
type ContainerSource string

// ContainerStatus defines model for Container.Status.
type ContainerStatus string

// ContainerAccount defines model for ContainerAccount.
type ContainerAccount struct {
	AuthStatus ContainerAccountAuthStatus `json:"authStatus"`
	Id         string                     `json:"id"`
	Platform   ContainerAccountPlatform   `json:"platform"`
	Status     ContainerAccountStatus     `json:"status"`
	Username   string                     `json:"username"`
}

// ContainerAccountAuthStatus defines model for ContainerAccount.AuthStatus.
type ContainerAccountAuthStatus string

// ContainerAccountPlatform defines model for ContainerAccount.Platform.
type ContainerAccountPlatform string

// ContainerAccountStatus defines model for ContainerAccount.Status.
type ContainerAccountStatus string

// ContainerList defines model for ContainerList.
type ContainerList struct {
	Containers []Container `json:"containers"`
}

// CreateAccountRequest defines model for CreateAccountRequest.
type CreateAccountRequest struct {
	// Password Sealed at rest; never returned or logged.
	Password     string                       `json:"password"`
	Platform     CreateAccountRequestPlatform `json:"platform"`
	ProxyGroupId nullable.Nullable[string]    `json:"proxyGroupId,omitempty"`
	Tags         *[]string                    `json:"tags,omitempty"`
	Username     string                       `json:"username"`
}

// CreateAccountRequestPlatform defines model for CreateAccountRequest.Platform.
type CreateAccountRequestPlatform string

// CreateContainerRequest defines model for CreateContainerRequest.
type CreateContainerRequest struct {
	// Name Optional display name. Omit to get a generated name.
	Name *string `json:"name,omitempty"`

	// Region ISO 3166-1 alpha-2 region for proxy placement.
	Region string `json:"region"`
}

// ErrorBody defines model for ErrorBody.
type ErrorBody struct {
	Error ErrorDetail `json:"error"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	Status string `json:"status"`
}

// Heartbeat defines model for Heartbeat.
type Heartbeat struct {
	BrowserStatus *HeartbeatBrowserStatus `json:"browserStatus,omitempty"`
	Cpu           *float64                `json:"cpu,omitempty"`
	CurrentJobId  *string                 `json:"currentJobId,omitempty"`
	JobsDone      *int                    `json:"jobsDone,omitempty"`
	LastActionAt  *time.Time              `json:"lastActionAt,omitempty"`
	Mem           *float64                `json:"mem,omitempty"`
	QueueDepth    *int                    `json:"queueDepth,omitempty"`
	WorkerId      string                  `json:"workerId"`
}

// HeartbeatBrowserStatus defines model for Heartbeat.BrowserStatus.
type HeartbeatBrowserStatus string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	AccessExpiry time.Time `json:"accessExpiry"`
	User         User      `json:"user"`
}

// MeResponse defines model for MeResponse.
type MeResponse struct {
	Role   Role   `json:"role"`
	UserId string `json:"userId"`
}

// ReadinessStatus defines model for ReadinessStatus.
type ReadinessStatus struct {
	Checks *map[string]string    `json:"checks,omitempty"`
	Status ReadinessStatusStatus `json:"status"`
}

// ReadinessStatusStatus defines model for ReadinessStatus.Status.
type ReadinessStatusStatus string

// Role defines model for Role.
type Role string

// SetAccountStatusRequest defines model for SetAccountStatusRequest.
type SetAccountStatusRequest struct {
	Status SetAccountStatusRequestStatus `json:"status"`
}

// SetAccountStatusRequestStatus defines model for SetAccountStatusRequest.Status.
type SetAccountStatusRequestStatus string

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	Status string `json:"status"`
}

// StreamEvent One server-sent events frame.
type StreamEvent struct {
	// Data The full entity payload, sent on the `data:` line as JSON.
	Data map[string]interface{} `json:"data"`

	// Kind The SSE `event:` line; the client dispatches on this.
	Kind StreamEventKind `json:"kind"`
}

// StreamEventKind The SSE `event:` line; the client dispatches on this.
type StreamEventKind string

// User defines model for User.
type User struct {
	Email openapi_types.Email `json:"email"`
	Id    string              `json:"id"`
	Name  string              `json:"name"`
	Role  Role                `json:"role"`
}

// AccountId defines model for AccountId.
type AccountId = string

// ContainerId defines model for ContainerId.
type ContainerId = string

// Error defines model for Error.
type Error = ErrorBody

// CreateAccountJSONRequestBody defines body for CreateAccount for application/json ContentType.
type CreateAccountJSONRequestBody = CreateAccountRequest

// SetAccountStatusJSONRequestBody defines body for SetAccountStatus for application/json ContentType.
type SetAccountStatusJSONRequestBody = SetAccountStatusRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// CreateContainerJSONRequestBody defines body for CreateContainer for application/json ContentType.
type CreateContainerJSONRequestBody = CreateContainerRequest

// PostAccountCallbackJSONRequestBody defines body for PostAccountCallback for application/json ContentType.
type PostAccountCallbackJSONRequestBody = AccountCallback

// PostActionCallbackJSONRequestBody defines body for PostActionCallback for application/json ContentType.
type PostActionCallbackJSONRequestBody = ActionCallback

// PostHeartbeatJSONRequestBody defines body for PostHeartbeat for application/json ContentType.
type PostHeartbeatJSONRequestBody = Heartbeat

type ErrorJSONResponse ErrorBody
