// Package oapigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package oapigen

import (
	"time"

	"github.com/oapi-codegen/nullable"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	AccessCookieScopes = "accessCookie.Scopes"
)

// Defines values for AccountAuthStatus.
const (
	AccountAuthStatusAUTHENTICATED  AccountAuthStatus = "AUTHENTICATED"
	AccountAuthStatusAUTHENTICATING AccountAuthStatus = "AUTHENTICATING"
	AccountAuthStatusFAILED         AccountAuthStatus = "FAILED"
	AccountAuthStatusNEEDSINPUT     AccountAuthStatus = "NEEDS_INPUT"
	AccountAuthStatusQUARANTINED    AccountAuthStatus = "QUARANTINED"
)

// Defines values for AccountPlatform.
const (
	AccountPlatformFacebook  AccountPlatform = "facebook"
	AccountPlatformInstagram AccountPlatform = "instagram"
	AccountPlatformLinkedin  AccountPlatform = "linkedin"
	AccountPlatformThreads   AccountPlatform = "threads"
	AccountPlatformTiktok    AccountPlatform = "tiktok"
	AccountPlatformX         AccountPlatform = "x"
	AccountPlatformYoutube   AccountPlatform = "youtube"
)

// Defines values for AccountStatus.
const (
	AccountStatusACTIVE   AccountStatus = "ACTIVE"
	AccountStatusARCHIVED AccountStatus = "ARCHIVED"
	AccountStatusDEAD     AccountStatus = "DEAD"
	AccountStatusPAUSED   AccountStatus = "PAUSED"
)

// Defines values for ActionItemActionType.
const (
	ActionItemActionTypeActionComment      ActionItemActionType = "action_comment"
	ActionItemActionTypeActionLike         ActionItemActionType = "action_like"
	ActionItemActionTypeActionReplyComment ActionItemActionType = "action_reply_comment"
	ActionItemActionTypeActionReport       ActionItemActionType = "action_report"
)

// Defines values for ActionJobActionType.
const (
	ActionJobActionTypeActionComment      ActionJobActionType = "action_comment"
	ActionJobActionTypeActionLike         ActionJobActionType = "action_like"
	ActionJobActionTypeActionReplyComment ActionJobActionType = "action_reply_comment"
	ActionJobActionTypeActionReport       ActionJobActionType = "action_report"
)

// Defines values for ActionReportRowActionType.
const (
	ActionReportRowActionTypeActionComment      ActionReportRowActionType = "action_comment"
	ActionReportRowActionTypeActionLike         ActionReportRowActionType = "action_like"
	ActionReportRowActionTypeActionReplyComment ActionReportRowActionType = "action_reply_comment"
	ActionReportRowActionTypeActionReport       ActionReportRowActionType = "action_report"
)

// Defines values for AttemptStatus.
const (
	AttemptStatusCANCELLED AttemptStatus = "CANCELLED"
	AttemptStatusFAILED    AttemptStatus = "FAILED"
	AttemptStatusRETRY     AttemptStatus = "RETRY"
	AttemptStatusSUCCESS   AttemptStatus = "SUCCESS"
)

// Defines values for AuthStatus.
const (
	AuthStatusAUTHENTICATED  AuthStatus = "AUTHENTICATED"
	AuthStatusAUTHENTICATING AuthStatus = "AUTHENTICATING"
	AuthStatusFAILED         AuthStatus = "FAILED"
	AuthStatusNEEDSINPUT     AuthStatus = "NEEDS_INPUT"
)

// Defines values for ContainerDesiredState.
const (
	ContainerDesiredStateRUNNING ContainerDesiredState = "RUNNING"
	ContainerDesiredStateSTOPPED ContainerDesiredState = "STOPPED"
)

// Defines values for ContainerSource.
const (
	AUTO   ContainerSource = "AUTO"
	MANUAL ContainerSource = "MANUAL"
)

// Defines values for ContainerStatus.
const (
	ContainerStatusBUSY        ContainerStatus = "BUSY"
	ContainerStatusDEAD        ContainerStatus = "DEAD"
	ContainerStatusDRAINING    ContainerStatus = "DRAINING"
	ContainerStatusERROR       ContainerStatus = "ERROR"
	ContainerStatusIDLE        ContainerStatus = "IDLE"
	ContainerStatusPENDING     ContainerStatus = "PENDING"
	ContainerStatusQUARANTINED ContainerStatus = "QUARANTINED"
	ContainerStatusREADY       ContainerStatus = "READY"
)

// Defines values for ContainerAccountAuthStatus.
const (
	ContainerAccountAuthStatusAUTHENTICATED  ContainerAccountAuthStatus = "AUTHENTICATED"
	ContainerAccountAuthStatusAUTHENTICATING ContainerAccountAuthStatus = "AUTHENTICATING"
	ContainerAccountAuthStatusFAILED         ContainerAccountAuthStatus = "FAILED"
	ContainerAccountAuthStatusNEEDSINPUT     ContainerAccountAuthStatus = "NEEDS_INPUT"
	ContainerAccountAuthStatusQUARANTINED    ContainerAccountAuthStatus = "QUARANTINED"
)

// Defines values for ContainerAccountPlatform.
const (
	ContainerAccountPlatformFacebook  ContainerAccountPlatform = "facebook"
	ContainerAccountPlatformInstagram ContainerAccountPlatform = "instagram"
	ContainerAccountPlatformLinkedin  ContainerAccountPlatform = "linkedin"
	ContainerAccountPlatformThreads   ContainerAccountPlatform = "threads"
	ContainerAccountPlatformTiktok    ContainerAccountPlatform = "tiktok"
	ContainerAccountPlatformX         ContainerAccountPlatform = "x"
	ContainerAccountPlatformYoutube   ContainerAccountPlatform = "youtube"
)

// Defines values for ContainerAccountStatus.
const (
	ContainerAccountStatusACTIVE   ContainerAccountStatus = "ACTIVE"
	ContainerAccountStatusARCHIVED ContainerAccountStatus = "ARCHIVED"
	ContainerAccountStatusDEAD     ContainerAccountStatus = "DEAD"
	ContainerAccountStatusPAUSED   ContainerAccountStatus = "PAUSED"
)

// Defines values for CreateAccountRequestPlatform.
const (
	CreateAccountRequestPlatformFacebook  CreateAccountRequestPlatform = "facebook"
	CreateAccountRequestPlatformInstagram CreateAccountRequestPlatform = "instagram"
	CreateAccountRequestPlatformLinkedin  CreateAccountRequestPlatform = "linkedin"
	CreateAccountRequestPlatformThreads   CreateAccountRequestPlatform = "threads"
	CreateAccountRequestPlatformTiktok    CreateAccountRequestPlatform = "tiktok"
	CreateAccountRequestPlatformX         CreateAccountRequestPlatform = "x"
	CreateAccountRequestPlatformYoutube   CreateAccountRequestPlatform = "youtube"
)

// Defines values for ErrorClass.
const (
	AUTH      ErrorClass = "AUTH"
	BANNED    ErrorClass = "BANNED"
	RATELIMIT ErrorClass = "RATE_LIMIT"
	TRANSIENT ErrorClass = "TRANSIENT"
	UNKNOWN   ErrorClass = "UNKNOWN"
)

// Defines values for HeartbeatBrowserStatus.
const (
	HeartbeatBrowserStatusBusy  HeartbeatBrowserStatus = "busy"
	HeartbeatBrowserStatusCold  HeartbeatBrowserStatus = "cold"
	HeartbeatBrowserStatusError HeartbeatBrowserStatus = "error"
	HeartbeatBrowserStatusReady HeartbeatBrowserStatus = "ready"
)

// Defines values for JobStatus.
const (
	JobStatusCANCELLED JobStatus = "CANCELLED"
	JobStatusFAILED    JobStatus = "FAILED"
	JobStatusPENDING   JobStatus = "PENDING"
	JobStatusRUNNING   JobStatus = "RUNNING"
	JobStatusSUCCESS   JobStatus = "SUCCESS"
)

// Defines values for OfficialAccountStatus.
const (
	Active   OfficialAccountStatus = "active"
	Archived OfficialAccountStatus = "archived"
	Paused   OfficialAccountStatus = "paused"
)

// Defines values for Platform.
const (
	PlatformFacebook  Platform = "facebook"
	PlatformInstagram Platform = "instagram"
	PlatformLinkedin  Platform = "linkedin"
	PlatformThreads   Platform = "threads"
	PlatformTiktok    Platform = "tiktok"
	PlatformX         Platform = "x"
	PlatformYoutube   Platform = "youtube"
)

// Defines values for ProvisionLogEntryOp.
const (
	CREATE ProvisionLogEntryOp = "CREATE"
	DELETE ProvisionLogEntryOp = "DELETE"
)

// Defines values for ProvisionLogEntryStatus.
const (
	APPLIED ProvisionLogEntryStatus = "APPLIED"
	FAILED  ProvisionLogEntryStatus = "FAILED"
)

// Defines values for ReadinessStatusStatus.
const (
	Degraded ReadinessStatusStatus = "degraded"
	Ok       ReadinessStatusStatus = "ok"
)

// Defines values for Role.
const (
	ANALYST    Role = "ANALYST"
	OPERATOR   Role = "OPERATOR"
	OWNER      Role = "OWNER"
	STRATEGIST Role = "STRATEGIST"
)

// Defines values for SetAccountStatusRequestStatus.
const (
	SetAccountStatusRequestStatusACTIVE SetAccountStatusRequestStatus = "ACTIVE"
	SetAccountStatusRequestStatusPAUSED SetAccountStatusRequestStatus = "PAUSED"
)

// Defines values for StreamEventKind.
const (
	AccountUpdated   StreamEventKind = "account-updated"
	ProvisionUpdated StreamEventKind = "provision-updated"
	WorkerHealth     StreamEventKind = "worker-health"
)

// Defines values for ReportExportParamsKind.
const (
	Actions   ReportExportParamsKind = "actions"
	Analytics ReportExportParamsKind = "analytics"
	Targets   ReportExportParamsKind = "targets"
)

// Defines values for ReportExportParamsFormat.
const (
	Csv  ReportExportParamsFormat = "csv"
	Json ReportExportParamsFormat = "json"
)

// Account defines model for Account.
type Account struct {
	AuthStatus AccountAuthStatus         `json:"authStatus"`
	Handle     nullable.Nullable[string] `json:"handle,omitempty"`
	Id         string                    `json:"id"`
	LastError  nullable.Nullable[string] `json:"lastError,omitempty"`
	Platform   AccountPlatform           `json:"platform"`
	Status     AccountStatus             `json:"status"`
	Tags       *[]string                 `json:"tags,omitempty"`
	Username   string                    `json:"username"`
	WorkerId   nullable.Nullable[string] `json:"workerId,omitempty"`
}

// AccountAuthStatus defines model for Account.AuthStatus.
type AccountAuthStatus string

// AccountPlatform defines model for Account.Platform.
type AccountPlatform string

// AccountStatus defines model for Account.Status.
type AccountStatus string

// AccountCallback defines model for AccountCallback.
type AccountCallback struct {
	AccountId  string     `json:"accountId"`
	AuthStatus AuthStatus `json:"authStatus"`
	Error      *string    `json:"error,omitempty"`

	// Handle Verified platform handle, set after a successful login.
	Handle *string `json:"handle,omitempty"`
}

// AccountList defines model for AccountList.
type AccountList struct {
	Accounts []Account `json:"accounts"`
}

// ActionCallback defines model for ActionCallback.
type ActionCallback struct {
	// ActionType e.g. like, comment, report.
	ActionType *string `json:"actionType,omitempty"`
	AttemptId  string  `json:"attemptId"`

	// DurationMs Measured run time of the attempt.
	DurationMs *int64  `json:"durationMs,omitempty"`
	Error      *string `json:"error,omitempty"`

	// RenderedText The final comment text the worker posted (template already rendered), stored on the attempt so a verdict replays without the pool.
	RenderedText *string `json:"renderedText,omitempty"`

	// ResponseExcerpt First runes of the platform response; the debug trail behind a verdict.
	ResponseExcerpt *string `json:"responseExcerpt,omitempty"`

	// ScreenshotPath File name only; the server applies path.Base and requires .png.
	ScreenshotPath *string       `json:"screenshotPath,omitempty"`
	Status         AttemptStatus `json:"status"`
	TargetUrl      *string       `json:"targetUrl,omitempty"`
	WorkerId       *string       `json:"workerId,omitempty"`
}

// ActionItem defines model for ActionItem.
type ActionItem struct {
	// AccountId The worker account that will perform the action.
	AccountId string `json:"accountId"`

	// ActionType The queue JobType; a like needs no text.
	ActionType ActionItemActionType `json:"actionType"`

	// TargetUrl Permalink of the post to act on. SSRF-guarded server-side.
	TargetUrl string `json:"targetUrl"`
}

// ActionItemActionType The queue JobType; a like needs no text.
type ActionItemActionType string

// ActionJob One enqueued action and its live status.
type ActionJob struct {
	AccountId  string                        `json:"accountId"`
	ActionType ActionJobActionType           `json:"actionType"`
	Attempts   int                           `json:"attempts"`
	Error      nullable.Nullable[string]     `json:"error,omitempty"`
	ErrorClass nullable.Nullable[ErrorClass] `json:"errorClass,omitempty"`
	Id         string                        `json:"id"`

	// RenderedText The comment text of the latest attempt, once dispatched.
	RenderedText nullable.Nullable[string] `json:"renderedText,omitempty"`
	ScheduledAt  time.Time                 `json:"scheduledAt"`

	// Status The queue-side status; the verdict lives on the attempt.
	Status   JobStatus `json:"status"`
	TargetId string    `json:"targetId"`

	// TargetUrl Resolved at dispatch from the target; null until then.
	TargetUrl nullable.Nullable[string] `json:"targetUrl,omitempty"`
}

// ActionJobActionType defines model for ActionJob.ActionType.
type ActionJobActionType string

// ActionJobList defines model for ActionJobList.
type ActionJobList struct {
	Actions []ActionJob `json:"actions"`
}

// ActionReport defines model for ActionReport.
type ActionReport struct {
	Rows []ActionReportRow `json:"rows"`

	// Series Per-day totals across the whole selection, for the chart.
	Series []TrendPoint `json:"series"`
}

// ActionReportRow One day × account × action type in the action report.
type ActionReportRow struct {
	AccountId  string                    `json:"accountId"`
	ActionType ActionReportRowActionType `json:"actionType"`
	Day        openapi_types.Date        `json:"day"`
	Failed     int                       `json:"failed"`

	// Platform The social platform. MVP active set is Instagram + Threads.
	Platform  Platform `json:"platform"`
	Succeeded int      `json:"succeeded"`
	Total     int      `json:"total"`
	Username  string   `json:"username"`
}

// ActionReportRowActionType defines model for ActionReportRow.ActionType.
type ActionReportRowActionType string

// AnalyticsFreshness Backs the dashboard's stale badge (P2-15 AC: stale when older than 60 minutes).
type AnalyticsFreshness struct {
	LastRunAt        nullable.Nullable[time.Time] `json:"lastRunAt,omitempty"`
	LastRunStatus    nullable.Nullable[string]    `json:"lastRunStatus,omitempty"`
	Stale            bool                         `json:"stale"`
	ThresholdSeconds *int                         `json:"thresholdSeconds,omitempty"`
}

// AnalyticsIngestRun defines model for AnalyticsIngestRun.
type AnalyticsIngestRun struct {
	AccountsErr *int                         `json:"accountsErr,omitempty"`
	AccountsOk  *int                         `json:"accountsOk,omitempty"`
	Error       nullable.Nullable[string]    `json:"error,omitempty"`
	ErrorClass  nullable.Nullable[string]    `json:"errorClass,omitempty"`
	FinishedAt  nullable.Nullable[time.Time] `json:"finishedAt,omitempty"`
	Id          string                       `json:"id"`
	Provider    string                       `json:"provider"`
	Scope       string                       `json:"scope"`
	StartedAt   time.Time                    `json:"startedAt"`
	Status      string                       `json:"status"`
}

// AnalyticsKpi One scalar KPI for one account.
type AnalyticsKpi struct {
	Handle            *string                  `json:"handle,omitempty"`
	Metric            string                   `json:"metric"`
	OfficialAccountId string                   `json:"officialAccountId"`
	Value             nullable.Nullable[int64] `json:"value"`
}

// AnalyticsOverview defines model for AnalyticsOverview.
type AnalyticsOverview struct {
	// Freshness Backs the dashboard's stale badge (P2-15 AC: stale when older than 60 minutes).
	Freshness AnalyticsFreshness `json:"freshness"`
	Kpis      []AnalyticsKpi     `json:"kpis"`
}

// AnalyticsReport defines model for AnalyticsReport.
type AnalyticsReport struct {
	AccountId string       `json:"accountId"`
	Metric    string       `json:"metric"`
	Series    []TrendPoint `json:"series"`
}

// AttemptStatus defines model for AttemptStatus.
type AttemptStatus string

// AuditLog One immutable audit-trail entry.
type AuditLog struct {
	// Action e.g. `account.create`.
	Action string `json:"action"`

	// Actor The user's email, or `system`.
	Actor *string `json:"actor,omitempty"`

	// ActorId Empty for system-initiated rows.
	ActorId *string `json:"actorId,omitempty"`

	// Entity e.g. `account`, `worker`, `template`.
	Entity   string `json:"entity"`
	EntityId string `json:"entityId"`
	Id       string `json:"id"`

	// Ip The request IP; empty when unknown.
	Ip *string `json:"ip,omitempty"`

	// Result `ok`, or the failure reason.
	Result string    `json:"result"`
	Ts     time.Time `json:"ts"`
}

// AuditLogList defines model for AuditLogList.
type AuditLogList struct {
	Limit  int        `json:"limit"`
	Offset int        `json:"offset"`
	Rows   []AuditLog `json:"rows"`

	// Total Entries matching the same filter, for pagination.
	Total int `json:"total"`
}

// AuthStatus defines model for AuthStatus.
type AuthStatus string

// CallbackAck defines model for CallbackAck.
type CallbackAck struct {
	Accepted bool `json:"accepted"`
}

// CommentTemplate defines model for CommentTemplate.
type CommentTemplate struct {
	BannedWords *[]string `json:"bannedWords,omitempty"`
	CreatedAt   time.Time `json:"createdAt"`
	Id          string    `json:"id"`
	IsActive    bool      `json:"isActive"`

	// Platform The social platform. MVP active set is Instagram + Threads.
	Platform Platform `json:"platform"`
	Text     string   `json:"text"`
	Vars     []string `json:"vars"`
	Weight   int      `json:"weight"`
}

// Container defines model for Container.
type Container struct {
	Accounts     *[]ContainerAccount   `json:"accounts,omitempty"`
	CreatedAt    time.Time             `json:"createdAt"`
	DesiredState ContainerDesiredState `json:"desiredState"`
	Generation   int                   `json:"generation"`
	Id           string                `json:"id"`

	// Latitude Frozen GPS latitude inside the city radius.
	Latitude nullable.Nullable[float64] `json:"latitude,omitempty"`

	// Location City the worker is anchored to; null on pre-geolocation rows.
	Location nullable.Nullable[string] `json:"location,omitempty"`

	// Longitude Frozen GPS longitude inside the city radius.
	Longitude nullable.Nullable[float64] `json:"longitude,omitempty"`
	Name      string                     `json:"name"`

	// NovncUrl Browser-reachable noVNC view URL (P4-08); null when unpublished.
	NovncUrl           nullable.Nullable[string] `json:"novncUrl,omitempty"`
	ObservedGeneration nullable.Nullable[int]    `json:"observedGeneration,omitempty"`

	// Region ISO 3166-1 alpha-2 country code the worker operates in.
	Region string          `json:"region"`
	Source ContainerSource `json:"source"`
	Status ContainerStatus `json:"status"`
}

// ContainerDesiredState defines model for Container.DesiredState.
type ContainerDesiredState string

// ContainerSource defines model for Container.Source.
type ContainerSource string

// ContainerStatus defines model for Container.Status.
type ContainerStatus string

// ContainerAccount defines model for ContainerAccount.
type ContainerAccount struct {
	AuthStatus ContainerAccountAuthStatus `json:"authStatus"`
	Id         string                     `json:"id"`
	Platform   ContainerAccountPlatform   `json:"platform"`
	Status     ContainerAccountStatus     `json:"status"`
	Username   string                     `json:"username"`
}

// ContainerAccountAuthStatus defines model for ContainerAccount.AuthStatus.
type ContainerAccountAuthStatus string

// ContainerAccountPlatform defines model for ContainerAccount.Platform.
type ContainerAccountPlatform string

// ContainerAccountStatus defines model for ContainerAccount.Status.
type ContainerAccountStatus string

// ContainerList defines model for ContainerList.
type ContainerList struct {
	Containers []Container `json:"containers"`
}

// CreateAccountRequest defines model for CreateAccountRequest.
type CreateAccountRequest struct {
	// Password Sealed at rest; never returned or logged.
	Password     string                       `json:"password"`
	Platform     CreateAccountRequestPlatform `json:"platform"`
	ProxyGroupId nullable.Nullable[string]    `json:"proxyGroupId,omitempty"`
	Tags         *[]string                    `json:"tags,omitempty"`
	Username     string                       `json:"username"`
}

// CreateAccountRequestPlatform defines model for CreateAccountRequest.Platform.
type CreateAccountRequestPlatform string

// CreateContainerRequest defines model for CreateContainerRequest.
type CreateContainerRequest struct {
	// Location City the worker operates from; picks the GPS radius to randomize a frozen coordinate from. One of GET /api/locations.
	Location string `json:"location"`

	// Name Optional display name. Omit to get a generated name.
	Name *string `json:"name,omitempty"`

	// NovncPort Optional host port to publish the live view on (127.0.0.1 only). Omit to let the API allocate one from NOVNC_PORT_MIN..NOVNC_PORT_MAX. Out-of-range or taken ports are a 400.
	NovncPort nullable.Nullable[int] `json:"novncPort,omitempty"`

	// Region ISO 3166-1 alpha-2 region for proxy placement.
	Region string `json:"region"`
}

// CreateOfficialAccountRequest defines model for CreateOfficialAccountRequest.
type CreateOfficialAccountRequest struct {
	AvatarUrl   *string `json:"avatarUrl,omitempty"`
	DisplayName *string `json:"displayName,omitempty"`
	Handle      string  `json:"handle"`

	// Platform The social platform. MVP active set is Instagram + Threads.
	Platform   Platform  `json:"platform"`
	ProfileUrl *string   `json:"profileUrl,omitempty"`
	Provider   *string   `json:"provider,omitempty"`
	Tags       *[]string `json:"tags,omitempty"`
}

// CreateProxyGroupRequest defines model for CreateProxyGroupRequest.
type CreateProxyGroupRequest struct {
	DailyBudgetMb  int    `json:"dailyBudgetMb"`
	MaxConcurrency int    `json:"maxConcurrency"`
	Name           string `json:"name"`

	// PoolKey Write-only; sealed at rest, never returned.
	PoolKey  string `json:"poolKey"`
	Provider string `json:"provider"`

	// Region ISO 3166-1 alpha-2.
	Region string `json:"region"`
}

// CreateTemplateRequest One pool variant. Every banned-word entry must compile as a regex
// (P3-03); a literal word is a valid regex, so the common case is free.
type CreateTemplateRequest struct {
	// BannedWords Regex denylist screened before a comment is queued.
	BannedWords *[]string `json:"bannedWords,omitempty"`
	IsActive    *bool     `json:"isActive,omitempty"`

	// Platform The social platform. MVP active set is Instagram + Threads.
	Platform Platform `json:"platform"`

	// Text The variant body. {topic} forms are rendered from vars.
	Text string `json:"text"`

	// Vars Every {var} used in text must be declared here, and used.
	Vars []string `json:"vars"`

	// Weight Relative pick probability (weight 3 is 3x weight 1).
	Weight int `json:"weight"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	Email openapi_types.Email `json:"email"`
	Name  string              `json:"name"`

	// Password Write-only; argon2id-hashed, never returned.
	Password string `json:"password"`
	Role     Role   `json:"role"`
}

// EnqueueActionsRequest A batch of intents. Comment text is deliberately absent: it is composed
// from the template pool at dispatch (P3-02) and denylist-screened before
// the queue (P3-03), so an enqueue only records WHAT to do and WHERE.
type EnqueueActionsRequest struct {
	// Items One job per target; the cap is the queue batch size.
	Items []ActionItem `json:"items"`
}

// ErrorBody defines model for ErrorBody.
type ErrorBody struct {
	Error ErrorDetail `json:"error"`
}

// ErrorClass Coarse failure classification (P3-12). Only TRANSIENT and RATE_LIMIT are
// retryable: AUTH/BANNED cannot be fixed by running it again.
type ErrorClass string

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	Status string `json:"status"`
}

// Heartbeat defines model for Heartbeat.
type Heartbeat struct {
	BrowserStatus *HeartbeatBrowserStatus `json:"browserStatus,omitempty"`
	Cpu           *float64                `json:"cpu,omitempty"`
	CurrentJobId  *string                 `json:"currentJobId,omitempty"`
	JobsDone      *int                    `json:"jobsDone,omitempty"`
	LastActionAt  *time.Time              `json:"lastActionAt,omitempty"`
	Mem           *float64                `json:"mem,omitempty"`

	// NovncUrl Browser-reachable noVNC view URL (P4-08); null when unpublished.
	NovncUrl   nullable.Nullable[string] `json:"novncUrl,omitempty"`
	QueueDepth *int                      `json:"queueDepth,omitempty"`
	WorkerId   string                    `json:"workerId"`
}

// HeartbeatBrowserStatus defines model for Heartbeat.BrowserStatus.
type HeartbeatBrowserStatus string

// ImportAccountsRequest defines model for ImportAccountsRequest.
type ImportAccountsRequest struct {
	// Rows One row per account; the cap is the import batch.
	Rows []CreateAccountRequest `json:"rows"`
}

// ImportResult The import verdict. `queued` counts created rows; `invalid` lists the
// rows rejected by validation or a duplicate; `rateLimited` is true when
// the caller exceeded the import rate budget and rows were refused.
type ImportResult struct {
	// Invalid One entry per rejected row, with a reason.
	Invalid []struct {
		Reason string `json:"reason"`

		// Row Zero-based index into the request rows.
		Row int `json:"row"`
	} `json:"invalid"`

	// Queued Accounts created (and packed when a slot exists).
	Queued      int  `json:"queued"`
	RateLimited bool `json:"rateLimited"`
}

// JobStatus The queue-side status; the verdict lives on the attempt.
type JobStatus string

// Location defines model for Location.
type Location struct {
	// Latitude City centre latitude.
	Latitude float64 `json:"latitude"`

	// Longitude City centre longitude.
	Longitude float64 `json:"longitude"`

	// Name City name; the value CreateContainerRequest.location takes.
	Name string `json:"name"`

	// RadiusKm Radius the API randomizes a worker's frozen point within.
	RadiusKm float64 `json:"radiusKm"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	AccessExpiry time.Time `json:"accessExpiry"`
	User         User      `json:"user"`
}

// MeResponse defines model for MeResponse.
type MeResponse struct {
	Role   Role   `json:"role"`
	UserId string `json:"userId"`
}

// OfficialAccount A monitored brand/client account (read-only). NOT a worker account: no
// credentials, no actions. The subject of 3rd-party analytics.
type OfficialAccount struct {
	AvatarUrl   nullable.Nullable[string] `json:"avatarUrl,omitempty"`
	CreatedAt   *time.Time                `json:"createdAt,omitempty"`
	DisplayName nullable.Nullable[string] `json:"displayName,omitempty"`
	Handle      string                    `json:"handle"`
	Id          string                    `json:"id"`

	// LastFetchedAt Null until the first successful ingest — the freshness signal.
	LastFetchedAt nullable.Nullable[time.Time] `json:"lastFetchedAt,omitempty"`

	// Platform The social platform. MVP active set is Instagram + Threads.
	Platform   Platform                  `json:"platform"`
	ProfileUrl nullable.Nullable[string] `json:"profileUrl,omitempty"`
	Provider   string                    `json:"provider"`

	// Stale True when lastFetchedAt is older than the 60-minute threshold.
	Stale  *bool                 `json:"stale,omitempty"`
	Status OfficialAccountStatus `json:"status"`
	Tags   *[]string             `json:"tags,omitempty"`
}

// OfficialAccountStatus defines model for OfficialAccount.Status.
type OfficialAccountStatus string

// OfficialAccountList defines model for OfficialAccountList.
type OfficialAccountList struct {
	OfficialAccounts []OfficialAccount `json:"officialAccounts"`
}

// Platform The social platform. MVP active set is Instagram + Threads.
type Platform string

// PlatformAnalytics defines model for PlatformAnalytics.
type PlatformAnalytics struct {
	// Freshness Backs the dashboard's stale badge (P2-15 AC: stale when older than 60 minutes).
	Freshness AnalyticsFreshness `json:"freshness"`
	Kpis      []AnalyticsKpi     `json:"kpis"`

	// Platform The social platform. MVP active set is Instagram + Threads.
	Platform Platform     `json:"platform"`
	Trend    []TrendPoint `json:"trend"`
}

// ProvisionLogEntry defines model for ProvisionLogEntry.
type ProvisionLogEntry struct {
	// Error The daemon or driver error when status is FAILED.
	Error      nullable.Nullable[string] `json:"error,omitempty"`
	Generation int                       `json:"generation"`
	Id         string                    `json:"id"`

	// K8sRef Platform-side reference (container id locally).
	K8sRef nullable.Nullable[string] `json:"k8sRef,omitempty"`

	// Op The provisioner operation.
	Op       ProvisionLogEntryOp     `json:"op"`
	Status   ProvisionLogEntryStatus `json:"status"`
	Ts       time.Time               `json:"ts"`
	WorkerId string                  `json:"workerId"`
}

// ProvisionLogEntryOp The provisioner operation.
type ProvisionLogEntryOp string

// ProvisionLogEntryStatus defines model for ProvisionLogEntry.Status.
type ProvisionLogEntryStatus string

// ProvisionLogList defines model for ProvisionLogList.
type ProvisionLogList struct {
	Logs []ProvisionLogEntry `json:"logs"`
}

// ProxyGroup A residential proxy pool. The pool key is write-only and never present
// in a response.
type ProxyGroup struct {
	CreatedAt      *time.Time `json:"createdAt,omitempty"`
	DailyBudgetMb  int        `json:"dailyBudgetMb"`
	Id             string     `json:"id"`
	MaxConcurrency int        `json:"maxConcurrency"`
	Name           string     `json:"name"`
	Provider       string     `json:"provider"`

	// Region ISO 3166-1 alpha-2.
	Region string `json:"region"`
}

// ProxyGroupList defines model for ProxyGroupList.
type ProxyGroupList struct {
	ProxyGroups []ProxyGroup `json:"proxyGroups"`
}

// ReadinessStatus defines model for ReadinessStatus.
type ReadinessStatus struct {
	Checks *map[string]string    `json:"checks,omitempty"`
	Status ReadinessStatusStatus `json:"status"`
}

// ReadinessStatusStatus defines model for ReadinessStatus.Status.
type ReadinessStatusStatus string

// Role defines model for Role.
type Role string

// SetAccountStatusRequest defines model for SetAccountStatusRequest.
type SetAccountStatusRequest struct {
	Status SetAccountStatusRequestStatus `json:"status"`
}

// SetAccountStatusRequestStatus defines model for SetAccountStatusRequest.Status.
type SetAccountStatusRequestStatus string

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	Status string `json:"status"`
}

// StreamEvent One server-sent events frame.
type StreamEvent struct {
	// Data The full entity payload, sent on the `data:` line as JSON.
	Data map[string]interface{} `json:"data"`

	// Kind The SSE `event:` line; the client dispatches on this.
	Kind StreamEventKind `json:"kind"`
}

// StreamEventKind The SSE `event:` line; the client dispatches on this.
type StreamEventKind string

// TargetReport defines model for TargetReport.
type TargetReport struct {
	Rows []TargetReportRow `json:"rows"`
}

// TargetReportRow One target (post) with its action outcome counts.
type TargetReportRow struct {
	Failed int    `json:"failed"`
	Id     string `json:"id"`

	// Platform The social platform. MVP active set is Instagram + Threads.
	Platform  Platform `json:"platform"`
	Succeeded int      `json:"succeeded"`
	Total     int      `json:"total"`
	Url       string   `json:"url"`
}

// TemplateList defines model for TemplateList.
type TemplateList struct {
	Templates []CommentTemplate `json:"templates"`
}

// TrendPoint defines model for TrendPoint.
type TrendPoint struct {
	Bucket time.Time `json:"bucket"`
	Value  int64     `json:"value"`
}

// UpdateUserRequest defines model for UpdateUserRequest.
type UpdateUserRequest struct {
	Name *string `json:"name,omitempty"`
	Role *Role   `json:"role,omitempty"`
}

// User defines model for User.
type User struct {
	Email openapi_types.Email `json:"email"`
	Id    string              `json:"id"`
	Name  string              `json:"name"`
	Role  Role                `json:"role"`
}

// UserList defines model for UserList.
type UserList struct {
	Users []User `json:"users"`
}

// WorkerGeolocation defines model for WorkerGeolocation.
type WorkerGeolocation struct {
	Latitude float64 `json:"latitude"`

	// Location The city the point was randomized within.
	Location  *string `json:"location,omitempty"`
	Longitude float64 `json:"longitude"`
}

// AccountId defines model for AccountId.
type AccountId = string

// ContainerId defines model for ContainerId.
type ContainerId = string

// LogLimit defines model for LogLimit.
type LogLimit = int

// OfficialAccountId defines model for OfficialAccountId.
type OfficialAccountId = string

// ProxyGroupId defines model for ProxyGroupId.
type ProxyGroupId = string

// TemplateId defines model for TemplateId.
type TemplateId = string

// UserId defines model for UserId.
type UserId = string

// Error defines model for Error.
type Error = ErrorBody

// ListActionsParams defines parameters for ListActions.
type ListActionsParams struct {
	Status *JobStatus `form:"status,omitempty" json:"status,omitempty"`
	Limit  *int       `form:"limit,omitempty" json:"limit,omitempty"`
}

// AnalyticsOverviewParams defines parameters for AnalyticsOverview.
type AnalyticsOverviewParams struct {
	WindowDays *int `form:"windowDays,omitempty" json:"windowDays,omitempty"`
}

// AnalyticsByPlatformParams defines parameters for AnalyticsByPlatform.
type AnalyticsByPlatformParams struct {
	Metric     *string `form:"metric,omitempty" json:"metric,omitempty"`
	WindowDays *int    `form:"windowDays,omitempty" json:"windowDays,omitempty"`
}

// ListAuditParams defines parameters for ListAudit.
type ListAuditParams struct {
	// ActorId Filter to one user's actions.
	ActorId *string `form:"actorId,omitempty" json:"actorId,omitempty"`

	// Action e.g. `account.create`.
	Action *string `form:"action,omitempty" json:"action,omitempty"`

	// Entity e.g. `account`, `worker`, `template`.
	Entity *string `form:"entity,omitempty" json:"entity,omitempty"`

	// From Inclusive lower bound on the entry time.
	From *time.Time `form:"from,omitempty" json:"from,omitempty"`

	// To Exclusive upper bound on the entry time.
	To *time.Time `form:"to,omitempty" json:"to,omitempty"`

	// Limit Page size.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Page offset.
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListContainerLogsParams defines parameters for ListContainerLogs.
type ListContainerLogsParams struct {
	// Limit How many log entries to return (newest first).
	Limit *LogLimit `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListOfficialAccountsParams defines parameters for ListOfficialAccounts.
type ListOfficialAccountsParams struct {
	Platform *Platform `form:"platform,omitempty" json:"platform,omitempty"`
}

// ReportActionsParams defines parameters for ReportActions.
type ReportActionsParams struct {
	From      *openapi_types.Date `form:"from,omitempty" json:"from,omitempty"`
	To        *openapi_types.Date `form:"to,omitempty" json:"to,omitempty"`
	Platform  *Platform           `form:"platform,omitempty" json:"platform,omitempty"`
	AccountId *string             `form:"accountId,omitempty" json:"accountId,omitempty"`
}

// ReportAnalyticsParams defines parameters for ReportAnalytics.
type ReportAnalyticsParams struct {
	AccountId string              `form:"accountId" json:"accountId"`
	Metric    *string             `form:"metric,omitempty" json:"metric,omitempty"`
	From      *openapi_types.Date `form:"from,omitempty" json:"from,omitempty"`
	To        *openapi_types.Date `form:"to,omitempty" json:"to,omitempty"`
}

// ReportExportParams defines parameters for ReportExport.
type ReportExportParams struct {
	Kind      ReportExportParamsKind    `form:"kind" json:"kind"`
	Format    *ReportExportParamsFormat `form:"format,omitempty" json:"format,omitempty"`
	From      *openapi_types.Date       `form:"from,omitempty" json:"from,omitempty"`
	To        *openapi_types.Date       `form:"to,omitempty" json:"to,omitempty"`
	Platform  *Platform                 `form:"platform,omitempty" json:"platform,omitempty"`
	AccountId *string                   `form:"accountId,omitempty" json:"accountId,omitempty"`
	Metric    *string                   `form:"metric,omitempty" json:"metric,omitempty"`
}

// ReportExportParamsKind defines parameters for ReportExport.
type ReportExportParamsKind string

// ReportExportParamsFormat defines parameters for ReportExport.
type ReportExportParamsFormat string

// ReportTargetsParams defines parameters for ReportTargets.
type ReportTargetsParams struct {
	From     *openapi_types.Date `form:"from,omitempty" json:"from,omitempty"`
	To       *openapi_types.Date `form:"to,omitempty" json:"to,omitempty"`
	Platform *Platform           `form:"platform,omitempty" json:"platform,omitempty"`
}

// ListTemplatesParams defines parameters for ListTemplates.
type ListTemplatesParams struct {
	Platform        *Platform `form:"platform,omitempty" json:"platform,omitempty"`
	IncludeInactive *bool     `form:"includeInactive,omitempty" json:"includeInactive,omitempty"`
}

// CreateAccountJSONRequestBody defines body for CreateAccount for application/json ContentType.
type CreateAccountJSONRequestBody = CreateAccountRequest

// ImportAccountsJSONRequestBody defines body for ImportAccounts for application/json ContentType.
type ImportAccountsJSONRequestBody = ImportAccountsRequest

// SetAccountStatusJSONRequestBody defines body for SetAccountStatus for application/json ContentType.
type SetAccountStatusJSONRequestBody = SetAccountStatusRequest

// EnqueueActionsJSONRequestBody defines body for EnqueueActions for application/json ContentType.
type EnqueueActionsJSONRequestBody = EnqueueActionsRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// CreateContainerJSONRequestBody defines body for CreateContainer for application/json ContentType.
type CreateContainerJSONRequestBody = CreateContainerRequest

// CreateOfficialAccountJSONRequestBody defines body for CreateOfficialAccount for application/json ContentType.
type CreateOfficialAccountJSONRequestBody = CreateOfficialAccountRequest

// CreateProxyGroupJSONRequestBody defines body for CreateProxyGroup for application/json ContentType.
type CreateProxyGroupJSONRequestBody = CreateProxyGroupRequest

// CreateTemplateJSONRequestBody defines body for CreateTemplate for application/json ContentType.
type CreateTemplateJSONRequestBody = CreateTemplateRequest

// UpdateTemplateJSONRequestBody defines body for UpdateTemplate for application/json ContentType.
type UpdateTemplateJSONRequestBody = CreateTemplateRequest

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UpdateUserRequest

// PostAccountCallbackJSONRequestBody defines body for PostAccountCallback for application/json ContentType.
type PostAccountCallbackJSONRequestBody = AccountCallback

// PostActionCallbackJSONRequestBody defines body for PostActionCallback for application/json ContentType.
type PostActionCallbackJSONRequestBody = ActionCallback

// PostHeartbeatJSONRequestBody defines body for PostHeartbeat for application/json ContentType.
type PostHeartbeatJSONRequestBody = Heartbeat

type ErrorJSONResponse ErrorBody
