// Package oapigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package oapigen

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	AccessCookieScopes = "accessCookie.Scopes"
)

// Defines values for ReadinessStatusStatus.
const (
	Degraded ReadinessStatusStatus = "degraded"
	Ok       ReadinessStatusStatus = "ok"
)

// Defines values for Role.
const (
	ANALYST    Role = "ANALYST"
	OPERATOR   Role = "OPERATOR"
	OWNER      Role = "OWNER"
	STRATEGIST Role = "STRATEGIST"
)

// ErrorBody defines model for ErrorBody.
type ErrorBody struct {
	Error ErrorDetail `json:"error"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	Status string `json:"status"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	AccessExpiry time.Time `json:"accessExpiry"`
	User         User      `json:"user"`
}

// MeResponse defines model for MeResponse.
type MeResponse struct {
	Role   Role   `json:"role"`
	UserId string `json:"userId"`
}

// ReadinessStatus defines model for ReadinessStatus.
type ReadinessStatus struct {
	Checks *map[string]string    `json:"checks,omitempty"`
	Status ReadinessStatusStatus `json:"status"`
}

// ReadinessStatusStatus defines model for ReadinessStatus.Status.
type ReadinessStatusStatus string

// Role defines model for Role.
type Role string

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	Status string `json:"status"`
}

// User defines model for User.
type User struct {
	Email openapi_types.Email `json:"email"`
	Id    string              `json:"id"`
	Name  string              `json:"name"`
	Role  Role                `json:"role"`
}

// Error defines model for Error.
type Error = ErrorBody

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

type ErrorJSONResponse ErrorBody
